aniyomiorg/aniyomi-extensions

- src/ar/witanime/build.gradle
- src/ar/witanime/src/eu/kanade/tachiyomi/animeextension/ar/witanime/WitAnime.kt
fix some special episodes don't show up
> witanime: some fixes

- src/ar/xsanime/build.gradle
- src/ar/xsanime/src/eu/kanade/tachiyomi/animeextension/ar/xsanime/XsAnime.kt
Add some Filters but not all of them i'll add them later
> xsanime: Add Filters

- src/en/tenshimoe/build.gradle
- src/en/tenshimoe/src/eu/kanade/tachiyomi/animeextension/en/tenshimoe/TenshiMoe.kt
Fix not all of episodes are showing
Closes #68
> tenshimoe: fix episodes

- src/ar/animeblkom/build.gradle
- src/ar/animeblkom/src/eu/kanade/tachiyomi/animeextension/ar/animeblkom/AnimeBlkom.kt
- src/ar/mycima/build.gradle
- src/ar/mycima/src/eu/kanade/tachiyomi/animeextension/ar/mycima/MyCima.kt
- src/ar/witanime/build.gradle
- src/ar/witanime/src/eu/kanade/tachiyomi/animeextension/ar/witanime/WitAnime.kt
- src/ar/xsanime/build.gradle
- src/ar/xsanime/src/eu/kanade/tachiyomi/animeextension/ar/xsanime/XsAnime.kt
fix new episodes don't appear in update tab
> Arabic sources some fixes

- src/ar/animeblkom/build.gradle
- src/ar/animeblkom/src/eu/kanade/tachiyomi/animeextension/ar/animeblkom/AnimeBlkom.kt
- src/ar/mycima/build.gradle
- src/ar/mycima/src/eu/kanade/tachiyomi/animeextension/ar/mycima/MyCima.kt
- src/ar/mycimamovies/build.gradle
- src/ar/mycimamovies/src/eu/kanade/tachiyomi/animeextension/ar/mycimamovie/MyCimaMovie.kt
add preferred quality settings to:
animeblkom
mycima
mycimaMovies
> add preferred quality settings to 3 sources

- src/en/gogoanime/build.gradle
- src/en/gogoanime/src/eu/kanade/tachiyomi/animeextension/en/gogoanime/GogoAnime.kt
Didn't notice this mistake, idk if I shud bump the version again. Lmk.
> fixes one filter in gogo

- src/id/otakudesu/build.gradle
- src/id/otakudesu/src/eu/kanade/tachiyomi/animeextension/id/otakudesu/OtakuDesu.kt
> otakudesu fix epsnum and added Genre filter

- src/id/oploverz/build.gradle
- src/id/oploverz/src/eu/kanade/tachiyomi/animeextension/id/oploverz/Oploverz.kt
> added zippyshare as a services - Oploverz

- src/en/hahomoe/src/eu/kanade/tachiyomi/animeextension/en/hahomoe/HahoMoe.kt
> haho: check for included tags

- src/es/animeflv/build.gradle
- src/es/animeflv/src/eu/kanade/tachiyomi/animeextension/es/animeflv/AnimeFlv.kt
> animeflv: add streamtape extractor

- src/id/oploverz/src/eu/kanade/tachiyomi/animeextension/id/oploverz/Oploverz.kt
Change domain Oploverz from .eu to .fan
> oploverz: update domain

- src/id/neonime/src/eu/kanade/tachiyomi/animeextension/id/neonime/NeoNime.kt
> neonime: change domain from .cc to .co

- src/id/neonime/build.gradle
> neonime: update extVersionCode

- src/es/animeflv/build.gradle
- src/es/animeflv/src/eu/kanade/tachiyomi/animeextension/es/animeflv/AnimeFlv.kt
- src/es/animeflv/src/eu/kanade/tachiyomi/animeextension/es/animeflv/extractors/FembedExtractor.kt
> animeflv: add fembed extractor

- src/id/otakudesu/build.gradle
- src/id/otakudesu/src/eu/kanade/tachiyomi/animeextension/id/otakudesu/OtakuDesu.kt
> Changing otakudesu domain to .info

- src/id/otakudesu/build.gradle
- src/id/otakudesu/src/eu/kanade/tachiyomi/animeextension/id/otakudesu/OtakuDesu.kt
> otakudesu: update zippy parser

- src/id/neonime/build.gradle
- src/id/neonime/src/eu/kanade/tachiyomi/animeextension/id/neonime/NeoNime.kt
- src/id/oploverz/build.gradle
- src/id/oploverz/src/eu/kanade/tachiyomi/animeextension/id/oploverz/Oploverz.kt
> fixed zippy scraper on NN and OL

- src/id/neonime/build.gradle
- src/id/neonime/src/eu/kanade/tachiyomi/animeextension/id/neonime/NeoNime.kt
If you are updating extensions, please remember to:
- Update the `extVersionCode` value in `build.gradle` yep
- Annotate `Source` or `SourceFactory` classes with `@Nsfw` when appropriate yep
- Add the `containsNsfw = true` flag in `build.gradle` when appropriate yep
Please also mention the related issues, e.g.:
Closes #156
> neonime: fix unparseable date

- src/ar/mycima/build.gradle
- src/ar/mycima/src/eu/kanade/tachiyomi/animeextension/ar/mycima/MyCima.kt
- src/ar/mycimamovie/build.gradle
- src/ar/mycimamovie/src/eu/kanade/tachiyomi/animeextension/ar/mycimamovie/MyCimaMovie.kt
fix video selectors if script has no video links
> mycima: fix video selectors

- src/en/genoanime/build.gradle
- src/en/genoanime/src/eu/kanade/tachiyomi/animeextension/en/genoanime/GenoAnime.kt
This update fixes the video loading error which was occurring due to a change made in the website also it throws error if a video is not available in a site.
> genoanime: fix video loading

- src/es/monoschinos/build.gradle
- src/es/monoschinos/src/eu/kanade/tachiyomi/animeextension/es/monoschinos/MonosChinos.kt
> add filter Monoschinos 

- src/ar/akwam/build.gradle
- src/ar/akwam/src/eu/kanade/tachiyomi/animeextension/ar/akwam/Akwam.kt
- src/ar/akwams/build.gradle
- src/ar/akwams/src/eu/kanade/tachiyomi/animeextension/ar/akwams/AkwamS.kt
- src/ar/anime4up/build.gradle
- src/ar/anime4up/src/eu/kanade/tachiyomi/animeextension/ar/anime4up/Anime4Up.kt
- src/ar/animeblkom/build.gradle
- src/ar/animeblkom/src/eu/kanade/tachiyomi/animeextension/ar/animeblkom/AnimeBlkom.kt
- src/ar/mycima/build.gradle
- src/ar/mycima/src/eu/kanade/tachiyomi/animeextension/ar/mycima/MyCima.kt
- src/ar/xsanime/build.gradle
- src/ar/xsanime/src/eu/kanade/tachiyomi/animeextension/ar/xsanime/XsAnime.kt
animeblkom: add support for animes that don't have episodes in them and add filters
anime4up: add episode_number and fix genre filters
akwam: update domain URL and fix viedos
mycima: add episode_number
xsanime: add episode_number
> update some arabic extensions

- src/en/wcofun/build.gradle
- src/en/wcofun/src/eu/kanade/tachiyomi/animeextension/en/wcofun/Wcofun.kt
Added filter for wcofun extension
> wcofun: add Filter 

- src/en/wcofun/build.gradle
- src/en/wcofun/src/eu/kanade/tachiyomi/animeextension/en/wcofun/Wcofun.kt
fixed wrong selector for search
> wcofun: fix search

- src/ar/witanime/build.gradle
- src/ar/witanime/src/eu/kanade/tachiyomi/animeextension/ar/witanime/WitAnime.kt
> WitAnime: Add new server

- src/en/asianload/build.gradle
- src/en/asianload/src/eu/kanade/tachiyomi/animeextension/en/asianload/AsianLoad.kt
> asianload: fix episode_number selectors

- src/en/dramacool/src/eu/kanade/tachiyomi/animeextension/en/dramacool/DramaCool.kt
> Fix Fembed extractor [dramacool]

- src/en/dramacool/build.gradle
> updating versión bruh [Dramacool]

- src/en/asianload/build.gradle
- src/en/asianload/src/eu/kanade/tachiyomi/animeextension/en/asianload/AsianLoad.kt
- src/en/asianload/src/eu/kanade/tachiyomi/animeextension/en/asianload/extractors/DoodExtractor.kt
- src/en/asianload/src/eu/kanade/tachiyomi/animeextension/en/asianload/extractors/FembedExtractor.kt
- src/en/asianload/src/eu/kanade/tachiyomi/animeextension/en/asianload/extractors/StreamSBExtractor.kt
- src/en/asianload/src/eu/kanade/tachiyomi/animeextension/en/asianload/extractors/StreamTapeExtractor.kt
- src/en/dramacool/build.gradle
- src/en/dramacool/src/eu/kanade/tachiyomi/animeextension/en/dramacool/DramaCool.kt
- src/en/dramacool/src/eu/kanade/tachiyomi/animeextension/en/dramacool/extractors/DoodExtractor.kt
- src/en/dramacool/src/eu/kanade/tachiyomi/animeextension/en/dramacool/extractors/FembedExtractor.kt
- src/en/dramacool/src/eu/kanade/tachiyomi/animeextension/en/dramacool/extractors/StreamSBExtractor.kt
- src/en/dramacool/src/eu/kanade/tachiyomi/animeextension/en/dramacool/extractors/StreamTapeExtractor.kt
> asianload, dramacool: fix streamsb extractor and other modifications 

- src/en/vidembed/build.gradle
- src/en/vidembed/src/eu/kanade/tachiyomi/animeextension/en/vidembed/Vidembed.kt
- src/en/vidembed/src/eu/kanade/tachiyomi/animeextension/en/vidembed/extractors/StreamSBExtractor.kt
> Vidembed: Fix server

- src/en/allmovies/build.gradle
- src/en/allmovies/src/eu/kanade/tachiyomi/animeextension/en/allmovies/AllMovies.kt
> allmovies: add doodstream extractor

- src/ar/witanime/build.gradle
- src/ar/witanime/src/eu/kanade/tachiyomi/animeextension/ar/witanime/extractors/FembedExtractor.kt
- src/en/asianload/build.gradle
- src/en/asianload/src/eu/kanade/tachiyomi/animeextension/en/asianload/extractors/FembedExtractor.kt
- src/en/dramacool/build.gradle
- src/en/dramacool/src/eu/kanade/tachiyomi/animeextension/en/dramacool/extractors/FembedExtractor.kt
- src/en/genoanime/build.gradle
- src/en/genoanime/src/eu/kanade/tachiyomi/animeextension/en/genoanime/extractors/FembedExtractor.kt
- src/es/animeflv/build.gradle
- src/es/animeflv/src/eu/kanade/tachiyomi/animeextension/es/animeflv/extractors/FembedExtractor.kt
- src/es/jkhentai/build.gradle
- src/es/jkhentai/src/eu/kanade/tachiyomi/animeextension/es/jkhentai/extractors/FembedExtractor.kt
- src/es/monoschinos/build.gradle
- src/es/monoschinos/src/eu/kanade/tachiyomi/animeextension/es/monoschinos/extractors/FembedExtractor.kt
fix for fembed extractor gives error when there is no video to parse
> fix for FembedExtractor

- src/es/animeflv/build.gradle
- src/es/animeflv/src/eu/kanade/tachiyomi/animeextension/es/animeflv/AnimeFlv.kt
- src/es/animeflv/src/eu/kanade/tachiyomi/animeextension/es/animeflv/extractors/StreamSBExtractor.kt
- src/it/animeworld/build.gradle
> add StreamSbExtractor to animeflv and fix it on animeworld

- src/en/animixplay/build.gradle
- src/en/animixplay/src/eu/kanade/tachiyomi/animeextension/en/animixplay/Animixplay.kt
Add setting for selecting sub or dub preference
> add audio preference

- src/en/animixplay/build.gradle
- src/en/animixplay/src/eu/kanade/tachiyomi/animeextension/en/animixplay/Animixplay.kt
Add new media server parser
remove audio pref for sub/dub
> Animixplay: vrv server

- src/pt/anitube/build.gradle
- src/pt/anitube/src/eu/kanade/tachiyomi/animeextension/pt/anitube/Anitube.kt
Some changes to `hasNextPage()` to fix the error.
> Anitube: Fix incomplete episodes list

- src/id/otakudesu/build.gradle
- src/id/otakudesu/src/eu/kanade/tachiyomi/animeextension/id/otakudesu/OtakuDesu.kt
> Change otakudesu domain because the old one are slow, and need to redirected first

- src/id/otakudesu/build.gradle
Fix libver changing to ext ver changing
> Revert libVer changing and change the ext ver

- src/en/gogoanime/build.gradle
- src/en/gogoanime/src/eu/kanade/tachiyomi/animeextension/en/gogoanime/GogoAnime.kt
- src/en/gogoanime/src/eu/kanade/tachiyomi/animeextension/en/gogoanime/extractors/DoodExtractor.kt
- src/en/gogoanime/src/eu/kanade/tachiyomi/animeextension/en/gogoanime/extractors/GogoCdnExtractor.kt
Loading of Anime via gogoplay is bugged. They changed their encryption method. 
This has to be fixed, but I am not able to do this.
But I fixed the loading of anime via dood.
> gogoanime: fix dood extractor

- src/ar/animerco/build.gradle
- src/ar/animerco/src/eu/kanade/tachiyomi/animeextension/ar/animerco/Animerco.kt
animerco : fix the video url method of getting video urls to POST
> animerco : fix the video url method

- src/es/animeflv/build.gradle
- src/es/animeflv/src/eu/kanade/tachiyomi/animeextension/es/animeflv/AnimeFlv.kt
- src/es/animeflv/src/eu/kanade/tachiyomi/animeextension/es/animeflv/extractors/FembedExtractor.kt
- src/es/animeflv/src/eu/kanade/tachiyomi/animeextension/es/animeflv/extractors/OkruExtractor.kt
> Add DUB option [AnimeFLV]

- src/en/gogoanime/build.gradle
- src/en/gogoanime/src/eu/kanade/tachiyomi/animeextension/en/gogoanime/extractors/GogoCdnExtractor.kt
Fixed GogoCDN ajax link & update ext version
> gogo: update encrypt-ajax domain

- src/pt/anitube/build.gradle
- src/pt/anitube/src/eu/kanade/tachiyomi/animeextension/pt/anitube/Anitube.kt
> anitube: fix season filter and black images

- src/es/pelisplushd/build.gradle
- src/es/pelisplushd/src/eu/kanade/tachiyomi/animeextension/es/pelisplushd/Pelisplushd.kt
> [PelisPlusHD] new domain

- src/es/animeflv/build.gradle
- src/es/animeflv/src/eu/kanade/tachiyomi/animeextension/es/animeflv/AnimeFlv.kt
> animeflv: update domain link

- src/en/gogoanime/build.gradle
My bad, I accidently forgot to update the number, hence it hasn't rolled out properly!
> Update gogo version number

- src/ru/animevost/build.gradle
- src/ru/animevost/src/eu/kanade/tachiyomi/animeextension/ru/animevost/Animevost.kt
animevost.org removes download buttons for some European regions
> fix(animevost): video link parser

- src/es/monoschinos/src/eu/kanade/tachiyomi/animeextension/es/monoschinos/MonosChinos.kt
Fuck alliance4creativity
closes #488
> [Monoschinos] Fix error in some links

- src/ar/anime4up/build.gradle
- src/ar/anime4up/src/eu/kanade/tachiyomi/animeextension/ar/anime4up/Anime4Up.kt
- src/ar/animerco/build.gradle
- src/ar/animerco/src/eu/kanade/tachiyomi/animeextension/ar/animerco/Animerco.kt
- src/ar/arabseed/build.gradle
- src/ar/arabseed/src/eu/kanade/tachiyomi/animeextension/ar/arabseed/ArabSeed.kt
anime4up: update domain link and referer
arabseed: update video extractor function
animerco: update selectors
> fix for some arabic extensions

- src/es/pelisplushd/build.gradle
- src/es/pelisplushd/src/eu/kanade/tachiyomi/animeextension/es/pelisplushd/Pelisplushd.kt
> fixed not showing the last chapter

- src/en/dramacool/build.gradle
- src/en/dramacool/src/eu/kanade/tachiyomi/animeextension/en/dramacool/DramaCool.kt
> Add Option to change dramacool baseurl

- src/en/dopebox/build.gradle
- src/en/dopebox/src/eu/kanade/tachiyomi/animeextension/en/dopebox/DopeBox.kt
- src/en/sflix/build.gradle
- src/en/sflix/src/eu/kanade/tachiyomi/animeextension/en/sflix/SFlix.kt
> sflix, dopebox: minor fix for video server

- src/ar/akwam/build.gradle
- src/ar/akwam/src/eu/kanade/tachiyomi/animeextension/ar/akwam/Akwam.kt
- src/ar/akwams/build.gradle
- src/ar/akwams/src/eu/kanade/tachiyomi/animeextension/ar/akwams/AkwamS.kt
- src/ar/animerco/build.gradle
- src/ar/animerco/src/eu/kanade/tachiyomi/animeextension/ar/animerco/Animerco.kt
> some fixes to arabic extensions

- .gitignore
- src/id/oploverz/build.gradle
- src/id/oploverz/src/eu/kanade/tachiyomi/animeextension/id/oploverz/Oploverz.kt
- src/id/otakudesu/build.gradle
- src/id/otakudesu/src/eu/kanade/tachiyomi/animeextension/id/otakudesu/OtakuDesu.kt
If you are updating extensions, please remember to:
- Update the `extVersionCode` value in `build.gradle` [x]
- Annotate `Source` or `SourceFactory` classes with `@Nsfw` when appropriate
- Add the `containsNsfw = true` flag in `build.gradle` when appropriate
Please also mention the related issues, e.g.:
Closes #522 issue 1 and 6
> OtakuDesu - Oploverz domain update

- src/en/sflix/build.gradle
- src/en/sflix/src/eu/kanade/tachiyomi/animeextension/en/sflix/SFlix.kt
Added sflix.se domain in this pull request.
related to #492
> Added one more domain to sflix

- src/pt/anitube/build.gradle
- src/pt/anitube/src/eu/kanade/tachiyomi/animeextension/pt/anitube/Anitube.kt
- src/pt/anitube/src/eu/kanade/tachiyomi/animeextension/pt/anitube/AnitubeFilters.kt
- src/pt/anitube/src/eu/kanade/tachiyomi/animeextension/pt/anitube/extractors/AnitubeExtractor.kt
> Anitube: Fix player and genres list + refactor

- src/ar/anime4up/build.gradle
- src/ar/anime4up/src/eu/kanade/tachiyomi/animeextension/ar/anime4up/Anime4Up.kt
- src/ar/animerco/build.gradle
- src/ar/animerco/src/eu/kanade/tachiyomi/animeextension/ar/animerco/Animerco.kt
- src/ar/witanime/build.gradle
- src/ar/witanime/src/eu/kanade/tachiyomi/animeextension/ar/witanime/WitAnime.kt
- src/ar/witanime/src/eu/kanade/tachiyomi/animeextension/ar/witanime/extractors/StreamSBExtractor.kt
anime4up: fix video extractor
witanime: dood stream name
animerco: fix thumbnails in populer page
> fix to arabic extensions

- src/pt/betteranime/AndroidManifest.xml
- src/pt/betteranime/build.gradle
- src/pt/betteranime/src/eu/kanade/tachiyomi/animeextension/pt/betteranime/BAUrlActivity.kt
- src/pt/betteranime/src/eu/kanade/tachiyomi/animeextension/pt/betteranime/BetterAnime.kt
> BetterAnime: add URL intent handler

- src/ar/asia2tv/build.gradle
- src/ar/asia2tv/src/eu/kanade/tachiyomi/animeextension/ar/asia2tv/Asia2TV.kt
> asia2tv fix search 

- src/pt/animefire/AndroidManifest.xml
- src/pt/animefire/build.gradle
- src/pt/animefire/src/eu/kanade/tachiyomi/animeextension/pt/animefire/AFConstants.kt
- src/pt/animefire/src/eu/kanade/tachiyomi/animeextension/pt/animefire/AFUrlActivity.kt
- src/pt/animefire/src/eu/kanade/tachiyomi/animeextension/pt/animefire/AnimeFire.kt
- src/pt/animefire/src/eu/kanade/tachiyomi/animeextension/pt/animefire/extractors/AnimeFireExtractor.kt
- src/pt/animefire/src/eu/kanade/tachiyomi/animeextension/pt/animefire/extractors/IframeExtractor.kt
> AnimeFire: Add new extractor and a URL intent handler

- src/it/animesaturn/build.gradle
- src/it/animesaturn/src/eu/kanade/tachiyomi/animeextension/it/animesaturn/AnimeSaturn.kt
AnimeSaturn recently changed their domain, so I modified the links for their extension accordingly.
> Updated AnimeSaturn's extension links

- src/de/aniflix/src/eu/kanade/tachiyomi/animeextension/de/aniflix/Aniflix.kt
- src/de/aniflix/src/eu/kanade/tachiyomi/animeextension/de/aniflix/extractors/VoeExtractor.kt
Second attempt. Made a mistake in the first Pull Request
> add Aniflix Voe Extractor

- src/de/aniflix/build.gradle
Forgot to set extVersionCode to right Version. Was still 9 set it to 10
> Set Aniflix extVersionCode right

- src/id/neonime/build.gradle
- src/id/neonime/src/eu/kanade/tachiyomi/animeextension/id/neonime/NeoNime.kt
- src/id/otakudesu/build.gradle
- src/id/otakudesu/src/eu/kanade/tachiyomi/animeextension/id/otakudesu/OtakuDesu.kt
Closes #481
Closes #511
Closes #584
> Update Indonesian NeoNime & OtakuDesu base URL

- src/es/hentaila/build.gradle
- src/es/hentaila/src/eu/kanade/tachiyomi/animeextension/es/hentaila/Hentaila.kt
> quick fix and remove filters for now [HentaiLa]

- src/es/animeflv/build.gradle
- src/es/animeflv/src/eu/kanade/tachiyomi/animeextension/es/animeflv/AnimeFlv.kt
- src/es/animeid/build.gradle
- src/es/animeid/src/eu/kanade/tachiyomi/animeextension/es/animeid/AnimeID.kt
AnimeID: bug in the chapter dates
AnimeFLV: filters added
Closes #477
> AnimeFLV and AnimeID updated

- src/de/aniflix/build.gradle
- src/de/aniflix/src/eu/kanade/tachiyomi/animeextension/de/aniflix/Aniflix.kt
- src/de/aniflix/src/eu/kanade/tachiyomi/animeextension/de/aniflix/extractors/StreamlareExtractor.kt
-Streamlist now contains all availeble resolutions of Streamlare if Streamlare is selected 
-removed Preferred Resolution (not needed anymore)
> Anflix Streamlare Update

- src/es/hentaijk/build.gradle
- src/es/jkhentai/build.gradle
Some corrections about extensions with Nsfw content.
> nsfw status: updated

- src/es/animeflv/build.gradle
- src/es/animeflv/src/eu/kanade/tachiyomi/animeextension/es/animeflv/AnimeFlv.kt
- src/es/animeonlineninja/build.gradle
- src/es/animeonlineninja/src/eu/kanade/tachiyomi/animeextension/es/animeonlineninja/AnimeonlineNinja.kt
- src/es/animeonlineninja/src/eu/kanade/tachiyomi/animeextension/es/animeonlineninja/extractors/FembedExtractor.kt
- src/es/animeonlineninja/src/eu/kanade/tachiyomi/animeextension/es/animeonlineninja/extractors/uploadExtractor.kt
- src/es/monoschinos/build.gradle
- src/es/monoschinos/src/eu/kanade/tachiyomi/animeextension/es/monoschinos/MonosChinos.kt
- src/es/monoschinos/src/eu/kanade/tachiyomi/animeextension/es/monoschinos/extractors/uploadExtractor.kt
- src/es/tioanime/build.gradle
- src/es/tioanime/src/eu/kanade/tachiyomi/animeextension/es/tioanimeh/TioanimeH.kt
- src/es/tioanime/src/eu/kanade/tachiyomi/animeextension/es/tioanimeh/TioanimeHFactory.kt
closes #652 
closes #637 
closes #618
> Some changes and fixes [Tioanime] [MonosChinos] [AnimeOnlineNinja] [AnimeFLV]

- src/de/filmpalast/build.gradle
- src/de/filmpalast/src/eu/kanade/tachiyomi/animeextension/de/filmpalast/FilmPalast.kt
- src/de/filmpalast/src/eu/kanade/tachiyomi/animeextension/de/filmpalast/extractors/EvoloadExtractor.kt
> add Filmpalast Evoload extractor

- src/ar/arabseed/build.gradle
- src/ar/arabseed/src/eu/kanade/tachiyomi/animeextension/ar/arabseed/ArabSeed.kt
update site domain and referer to fix video list empty
> arabseed: update domain and referer 

- src/de/filmpalast/build.gradle
- src/de/filmpalast/src/eu/kanade/tachiyomi/animeextension/de/filmpalast/FilmPalast.kt
- src/de/filmpalast/src/eu/kanade/tachiyomi/animeextension/de/filmpalast/extractors/EvoloadExtractor.kt
- src/de/filmpalast/src/eu/kanade/tachiyomi/animeextension/de/filmpalast/extractors/VoeExtractor.kt
> Filmpalast Evoload Extractor update

- src/pt/animesvision/AndroidManifest.xml
- src/pt/animesvision/build.gradle
- src/pt/animesvision/src/eu/kanade/tachiyomi/animeextension/pt/animesvision/AVUrlActivity.kt
- src/pt/animesvision/src/eu/kanade/tachiyomi/animeextension/pt/animesvision/AnimesVision.kt
- src/pt/animesvision/src/eu/kanade/tachiyomi/animeextension/pt/animesvision/extractors/DoodExtractor.kt
- src/pt/animesvision/src/eu/kanade/tachiyomi/animeextension/pt/animesvision/extractors/GlobalVisionExtractor.kt
- src/pt/animesvision/src/eu/kanade/tachiyomi/animeextension/pt/animesvision/extractors/VoeExtractor.kt
> AnimesVision: Fix GlobalVision extractor and add URL intent handler

- src/pt/animeyabu/AndroidManifest.xml
- src/pt/animeyabu/build.gradle
- src/pt/animeyabu/src/eu/kanade/tachiyomi/animeextension/pt/animeyabu/AYConstants.kt
- src/pt/animeyabu/src/eu/kanade/tachiyomi/animeextension/pt/animeyabu/AYUrlActivity.kt
- src/pt/animeyabu/src/eu/kanade/tachiyomi/animeextension/pt/animeyabu/AnimeYabu.kt
- src/pt/animeyabu/src/eu/kanade/tachiyomi/animeextension/pt/animeyabu/extractors/PlayerOneExtractor.kt
> AnimeYabu: Fix video extractor and add URL intent handler

- src/es/animeflv/build.gradle
- src/es/animeflv/src/eu/kanade/tachiyomi/animeextension/es/animeflv/AnimeFlv.kt
- src/es/animeflv/src/eu/kanade/tachiyomi/animeextension/es/animeflv/extractors/StreamSBExtractor.kt
- src/es/animeflv/src/eu/kanade/tachiyomi/animeextension/es/animeflv/extractors/YourUploadExtractor.kt
> Animeflv updates

- src/pt/puraymoe/build.gradle
- src/pt/puraymoe/src/eu/kanade/tachiyomi/animeextension/pt/puraymoe/PurayMoe.kt
- src/pt/puraymoe/src/eu/kanade/tachiyomi/animeextension/pt/puraymoe/dto/PurayMoeDto.kt
> PurayMoe: Fix latest episodes page

- src/ar/animelek/build.gradle
- src/ar/animelek/src/eu/kanade/tachiyomi/animeextension/ar/animelek/AnimeLek.kt
- src/ar/animerco/build.gradle
- src/ar/animerco/src/eu/kanade/tachiyomi/animeextension/ar/animerco/Animerco.kt
- src/ar/witanime/build.gradle
- src/ar/witanime/src/eu/kanade/tachiyomi/animeextension/ar/witanime/WitAnime.kt
- src/en/asianload/build.gradle
- src/en/asianload/src/eu/kanade/tachiyomi/animeextension/en/asianload/AsianLoad.kt
- src/en/dramacool/build.gradle
- src/en/dramacool/src/eu/kanade/tachiyomi/animeextension/en/dramacool/DramaCool.kt
- src/en/genoanime/build.gradle
- src/en/genoanime/src/eu/kanade/tachiyomi/animeextension/en/genoanime/GenoAnime.kt
- src/en/vidembed/build.gradle
- src/en/vidembed/src/eu/kanade/tachiyomi/animeextension/en/vidembed/Vidembed.kt
- src/hi/animeWorld/build.gradle
- src/hi/animeWorld/src/eu/kanade/tachiyomi/animeextension/hi/animeWorld/AnimeWorld.kt
- src/it/animeworld/build.gradle
- src/it/animeworld/src/eu/kanade/tachiyomi/animeextension/it/animeworld/ANIMEWORLD.kt
add new streamsb domains as some extensions use the new ones and broke the streamsbextractor
> add new streamsb domains

- src/all/onepace/build.gradle
- src/all/onepace/src/eu/kanade/tachiyomi/animeextension/all/onepace/Onepace.kt
I made the thumbnails optional because the one pace page is down and makes the extension not work
> fix specials(EN), thumbnails now is optional [OnePace]

- src/en/dopebox/build.gradle
- src/en/dopebox/src/eu/kanade/tachiyomi/animeextension/en/dopebox/DopeBox.kt
- src/en/sflix/build.gradle
- src/en/sflix/src/eu/kanade/tachiyomi/animeextension/en/sflix/SFlix.kt
Closes #674
Closes #628
Closes #546
> sflix,dopebox: add subs support

- src/en/nineanime/build.gradle
- src/en/nineanime/src/eu/kanade/tachiyomi/animeextension/en/nineanime/NineAnime.kt
Add `Preferred language` setting
Add Sub/Dub to video qualities
Closes #710
> 9anime: Add Dub

- src/en/nineanime/build.gradle
- src/en/nineanime/src/eu/kanade/tachiyomi/animeextension/en/nineanime/NineAnime.kt
Credit goes to [Saikou](https://github.com/saikou-app/saikou/)
- Closes #717
- Closes #716
> Fix 9anime Key

- src/es/pelisplushd/build.gradle
- src/es/pelisplushd/src/eu/kanade/tachiyomi/animeextension/es/pelisplushd/Pelisplushd.kt
- src/es/pelisplushd/src/eu/kanade/tachiyomi/animeextension/es/pelisplushd/extractors/YourUploadExtractor.kt
fixes and updates
filters added, video extraction method update.
Closes #518
> PelisPlusHD: fixes and updates

- src/en/gogoanime/build.gradle
- src/en/gogoanime/src/eu/kanade/tachiyomi/animeextension/en/gogoanime/GogoAnime.kt
> Fix gogo domains

- src/es/mundodonghua/build.gradle
- src/es/mundodonghua/src/eu/kanade/tachiyomi/animeextension/es/mundodonghua/MundoDonghua.kt
- src/es/mundodonghua/src/eu/kanade/tachiyomi/animeextension/es/mundodonghua/extractors/JsUnpacker.kt
- src/es/mundodonghua/src/eu/kanade/tachiyomi/animeextension/es/mundodonghua/extractors/ProteaExtractor.kt
- src/es/pelisplushd/build.gradle
- src/es/pelisplushd/src/eu/kanade/tachiyomi/animeextension/es/pelisplushd/Pelisplushd.kt
- PelisplusHD: bug solved
- MundoDonghua fixes
Closes #680
> Extension fixes

- src/fr/vostfree/build.gradle
- src/fr/vostfree/src/eu/kanade/tachiyomi/animeextension/fr/vostfree/Vostfree.kt
- src/fr/vostfree/src/eu/kanade/tachiyomi/animeextension/fr/vostfree/extractors/VudeoExtractor.kt
> Fix Search and Video Extractor [VostFree]]

- src/es/animeyt/build.gradle
- src/es/animeyt/src/eu/kanade/tachiyomi/animeextension/es/animeyt/Animeyt.kt
- src/es/animeyt/src/eu/kanade/tachiyomi/animeextension/es/animeyt/extractors/FastreamExtractor.kt
- src/es/animeyt/src/eu/kanade/tachiyomi/animeextension/es/animeyt/extractors/JsUnpacker.kt
> AnimeYT fixes

- src/id/kuronime/build.gradle
- src/id/kuronime/src/eu/kanade/tachiyomi/animeextension/id/kuronime/Kuronime.kt
> Kuronime: Update baseUrl

- src/en/kickassanime/build.gradle
- src/en/kickassanime/src/eu/kanade/tachiyomi/animeextension/en/kickassanime/KickAssAnime.kt
- src/en/kickassanime/src/eu/kanade/tachiyomi/animeextension/en/kickassanime/MasterPlaylistInterceptor.kt
- src/en/kickassanime/src/eu/kanade/tachiyomi/animeextension/en/kickassanime/extractors/DoodExtractor.kt
- src/en/kickassanime/src/eu/kanade/tachiyomi/animeextension/en/kickassanime/extractors/GogoCdnExtractor.kt
- src/en/kickassanime/src/eu/kanade/tachiyomi/animeextension/en/kickassanime/extractors/StreamSBExtractor.kt
Checklist:
Handle gogo redirects for old anime (used extractors from gogo extension)
Extract more reliable from MAVERICKKI api source
Wait a bit more when intercepting playlists to mitigate slow networks
> KickAssAnime: Fixes

- src/ar/anime4up/build.gradle
- src/ar/anime4up/src/eu/kanade/tachiyomi/animeextension/ar/anime4up/Anime4Up.kt
> anime4up : update referer headers

- src/en/kickassanime/build.gradle
- src/en/kickassanime/src/eu/kanade/tachiyomi/animeextension/en/kickassanime/KickAssAnime.kt
Checklist:
closes #766
Keeping up with the sites weirdness
> KickassAnime: check gogo url structure

- src/pt/goyabu/build.gradle
- src/pt/goyabu/src/eu/kanade/tachiyomi/animeextension/pt/goyabu/GYConstants.kt
- src/pt/goyabu/src/eu/kanade/tachiyomi/animeextension/pt/goyabu/Goyabu.kt
- src/pt/goyabu/src/eu/kanade/tachiyomi/animeextension/pt/goyabu/extractors/PlayerOneExtractor.kt
> Goyabu: Fix extractor operation 

- src/en/kickassanime/build.gradle
- src/en/kickassanime/src/eu/kanade/tachiyomi/animeextension/en/kickassanime/KickAssAnime.kt
> KickassAnime: ignore more dead servers and handle new working ones

- src/en/rule34video/build.gradle
- src/en/rule34video/src/eu/kanade/tachiyomi/animeextension/en/rule34video/Rule34Video.kt
> Added Filters [Rule34Video]

- src/fr/nekosama/build.gradle
- src/fr/nekosama/src/eu/kanade/tachiyomi/animeextension/fr/nekosama/NekoSama.kt
> Fix episodes and added search [Neko-Sama]

- src/en/kickassanime/build.gradle
- src/en/kickassanime/src/eu/kanade/tachiyomi/animeextension/en/kickassanime/KickAssAnime.kt
> KickMyassAnime: handle links when link1 is blank

- src/en/superstream/src/eu/kanade/tachiyomi/animeextension/en/superstream/SuperStreamAPI.kt
> Add license to SuperstreamAPI as per gplv3

- src/en/dramacool/build.gradle
- src/en/dramacool/src/eu/kanade/tachiyomi/animeextension/en/dramacool/DramaCool.kt
> added new extractor domains

- src/all/onepace/build.gradle
- src/all/onepace/src/eu/kanade/tachiyomi/animeextension/all/onepace/Onepace.kt
> fixes [OnePace]

- src/es/monoschinos/build.gradle
- src/es/monoschinos/src/eu/kanade/tachiyomi/animeextension/es/monoschinos/MonosChinos.kt
> monoschinos: fix episode list

- src/es/animefenix/build.gradle
- src/es/animefenix/src/eu/kanade/tachiyomi/animeextension/es/animefenix/Animefenix.kt
> Fixes [AnimeFenix]

- src/all/onepace/build.gradle
- src/all/onepace/src/eu/kanade/tachiyomi/animeextension/all/onepace/Onepace.kt
- src/fr/vostfree/build.gradle
- src/fr/vostfree/src/eu/kanade/tachiyomi/animeextension/fr/vostfree/Vostfree.kt
> fixes [OnePace] [VostFree]

- src/en/kickassanime/build.gradle
- src/en/kickassanime/src/eu/kanade/tachiyomi/animeextension/en/kickassanime/KickAssAnime.kt
> KickAssAnime: add server preference setting from working servers

- src/es/animefenix/build.gradle
- src/es/animefenix/src/eu/kanade/tachiyomi/animeextension/es/animefenix/Animefenix.kt
> new server (FireLoad) and fixes [AnimeFenix]

- src/en/animension/build.gradle
- src/en/animension/src/eu/kanade/tachiyomi/animeextension/en/animension/Animension.kt
> animension: added latest support

- src/en/superstream/build.gradle
- src/en/superstream/src/eu/kanade/tachiyomi/animeextension/en/superstream/SuperStreamAPI.kt
> SuperStream: Number subtitles and add points available from source

- src/en/dramacool/build.gradle
- src/en/dramacool/src/eu/kanade/tachiyomi/animeextension/en/dramacool/DramaCool.kt
> dramacool: added latest support and code clean up

- src/en/superstream/build.gradle
- src/en/superstream/src/eu/kanade/tachiyomi/animeextension/en/superstream/DataModel.kt
- src/en/superstream/src/eu/kanade/tachiyomi/animeextension/en/superstream/SuperStream.kt
- src/en/superstream/src/eu/kanade/tachiyomi/animeextension/en/superstream/SuperStreamAPI.kt
> SuperStream: Remove jackson dependency to reduce size significantly

- src/pt/pifansubs/build.gradle
- src/pt/pifansubs/src/eu/kanade/tachiyomi/animeextension/pt/pifansubs/PiFansubs.kt
> PiFansubs: Fix Latest episodes screen

- src/en/animension/build.gradle
- src/en/animension/src/eu/kanade/tachiyomi/animeextension/en/animension/Animension.kt
- src/en/dramacool/build.gradle
- src/en/dramacool/src/eu/kanade/tachiyomi/animeextension/en/dramacool/DramaCool.kt
- src/en/dramacool/src/eu/kanade/tachiyomi/animeextension/en/dramacool/extractors/FembedExtractor.kt
> updates on animension and dramacool

- src/es/monoschinos/build.gradle
- src/es/monoschinos/src/eu/kanade/tachiyomi/animeextension/es/monoschinos/MonosChinos.kt
- src/es/monoschinos/src/eu/kanade/tachiyomi/animeextension/es/monoschinos/extractors/Mp4uploadExtractor.kt
- src/es/monoschinos/src/eu/kanade/tachiyomi/animeextension/es/monoschinos/extractors/UploadExtractor.kt
> New server (Mp4Upload) [MonosChinos]

- src/pt/cinevision/build.gradle
- src/pt/cinevision/src/eu/kanade/tachiyomi/animeextension/pt/cinevision/CVConstants.kt
- src/pt/cinevision/src/eu/kanade/tachiyomi/animeextension/pt/cinevision/CineVision.kt
- src/pt/cinevision/src/eu/kanade/tachiyomi/animeextension/pt/cinevision/extractors/StreamlareExtractor.kt
> CineVision: Some improvements

- src/en/dopebox/build.gradle
- src/en/dopebox/src/eu/kanade/tachiyomi/animeextension/en/dopebox/DopeBox.kt
> Dopebox: Add one more domain

- src/en/dopebox/build.gradle
- src/en/dopebox/src/eu/kanade/tachiyomi/animeextension/en/dopebox/DopeBox.kt
- src/en/sflix/build.gradle
- src/en/sflix/src/eu/kanade/tachiyomi/animeextension/en/sflix/SFlix.kt
> Sflix & DopeBox: Added Subtitle preference

- src/es/animefenix/build.gradle
- src/es/animefenix/src/eu/kanade/tachiyomi/animeextension/es/animefenix/Animefenix.kt
- src/es/animefenix/src/eu/kanade/tachiyomi/animeextension/es/animefenix/extractors/Mp4uploadExtractor.kt
> Fixes and added filters [AnimeFenix]

- src/pt/pifansubs/build.gradle
- src/pt/pifansubs/src/eu/kanade/tachiyomi/animeextension/pt/pifansubs/PiFansubs.kt
- src/pt/pifansubs/src/eu/kanade/tachiyomi/animeextension/pt/pifansubs/extractors/GdrivePlayerExtractor.kt
> PiFansubs: add Gdriveplayer extractor

- src/all/onepace/build.gradle
- src/all/onepace/src/eu/kanade/tachiyomi/animeextension/all/onepace/Onepace.kt
- src/all/onepace/src/eu/kanade/tachiyomi/animeextension/all/onepace/ZippyExtractor.kt
> fix [OnePace]

- src/ar/faselhd/build.gradle
- src/ar/faselhd/src/eu/kanade/tachiyomi/animeextension/ar/faselhd/FASELHD.kt
- src/ar/faselhd/src/eu/kanade/tachiyomi/animeextension/ar/faselhd/GetSourcesInterceptor.kt
- src/ar/faselhdmovies/build.gradle
- src/ar/faselhdmovies/src/eu/kanade/tachiyomi/animeextension/ar/faselhdmovies/FASELHDMOVIES.kt
- src/ar/faselhdmovies/src/eu/kanade/tachiyomi/animeextension/ar/faselhdmovies/GetSourcesInterceptor.kt
> finally fix faselhd source

- src/pt/animeshouse/build.gradle
- src/pt/animeshouse/src/eu/kanade/tachiyomi/animeextension/pt/animeshouse/AnimesHouse.kt
- src/pt/animeshouse/src/eu/kanade/tachiyomi/animeextension/pt/animeshouse/extractors/EdifierExtractor.kt
- src/pt/animeshouse/src/eu/kanade/tachiyomi/animeextension/pt/animeshouse/extractors/RedplayBypasser.kt
> AnimesHouse: Fix NPE and video extractor operation

- src/es/jkanime/build.gradle
- src/es/jkanime/src/eu/kanade/tachiyomi/animeextension/es/jkanime/Jkanime.kt
- src/es/jkanime/src/eu/kanade/tachiyomi/animeextension/es/jkanime/extractors/JkanimeExtractor.kt
> Fixes [JkAnime]

- src/de/kinoking/build.gradle
- src/de/kinoking/src/eu/kanade/tachiyomi/animeextension/de/kinoking/CloudflareInterceptor.kt
- src/de/kinoking/src/eu/kanade/tachiyomi/animeextension/de/kinoking/Kinoking.kt
using webview to bypass cloudflare
> kinoking cloudflare fix

- src/en/zoro/AndroidManifest.xml
- src/en/zoro/build.gradle
- src/en/zoro/src/eu/kanade/tachiyomi/animeextension/en/zoro/Zoro.kt
- src/en/zoro/src/eu/kanade/tachiyomi/animeextension/en/zoro/ZoroFilters.kt
- src/en/zoro/src/eu/kanade/tachiyomi/animeextension/en/zoro/ZoroUrlActivity.kt
- src/en/zoro/src/eu/kanade/tachiyomi/animeextension/en/zoro/extractors/ZoroExtractor.kt
> Zoro: add search filters and URL intent handler

- src/id/otakudesu/build.gradle
- src/id/otakudesu/src/eu/kanade/tachiyomi/animeextension/id/otakudesu/OtakuDesu.kt
> Cleared some text and changed base domain

- src/id/otakudesu/build.gradle
- src/id/otakudesu/src/eu/kanade/tachiyomi/animeextension/id/otakudesu/OtakuDesu.kt
> Fix errors

- src/en/dopebox/build.gradle
- src/en/dopebox/src/eu/kanade/tachiyomi/animeextension/en/dopebox/DopeBox.kt
- src/en/dopebox/src/eu/kanade/tachiyomi/animeextension/en/dopebox/DopeBoxFilters.kt
- src/en/dopebox/src/eu/kanade/tachiyomi/animeextension/en/dopebox/extractors/DoodExtractor.kt
- src/en/dopebox/src/eu/kanade/tachiyomi/animeextension/en/dopebox/extractors/DopeBoxExtractor.kt
- src/en/dopebox/src/eu/kanade/tachiyomi/animeextension/en/dopebox/utils/Decryptor.kt
- src/en/dopebox/src/eu/kanade/tachiyomi/animeextension/en/dopebox/utils/FindPassword.kt
Closes #880 
Yes,  the PR message is almost the same as in #881 , the source itself looks really like zoro. Clone or template?
Checklist:
> Dopebox: Fix video extractor and do small improvements

- src/es/pelisflix/build.gradle
- src/es/pelisflix/src/eu/kanade/tachiyomi/animeextension/es/pelisflix/Pelisflix.kt
- src/es/pelisflix/src/eu/kanade/tachiyomi/animeextension/es/pelisflix/PelisflixFactory.kt
> pelisflix and seriesflix fixes

- src/de/anime24/build.gradle
- src/de/anime24/src/eu/kanade/tachiyomi/animeextension/de/anime24/Anime24.kt
-dub & sub are separate now
- video list isn't empty anymore
> Anime24: fix & update

- src/en/zoro/build.gradle
- src/en/zoro/src/eu/kanade/tachiyomi/animeextension/en/zoro/Zoro.kt
- src/en/zoro/src/eu/kanade/tachiyomi/animeextension/en/zoro/extractors/StreamSBExtractor.kt
- src/en/zoro/src/eu/kanade/tachiyomi/animeextension/en/zoro/extractors/StreamTapeExtractor.kt
- src/en/zoro/src/eu/kanade/tachiyomi/animeextension/en/zoro/utils/FindPassword.kt
> Zoro: Fix video extractors. again.

- src/en/sflix/build.gradle
- src/en/sflix/src/eu/kanade/tachiyomi/animeextension/en/sflix/SFlix.kt
- src/en/sflix/src/eu/kanade/tachiyomi/animeextension/en/sflix/SFlixFilters.kt
- src/en/sflix/src/eu/kanade/tachiyomi/animeextension/en/sflix/extractors/DoodExtractor.kt
- src/en/sflix/src/eu/kanade/tachiyomi/animeextension/en/sflix/extractors/SFlixExtractor.kt
- src/en/sflix/src/eu/kanade/tachiyomi/animeextension/en/sflix/utils/Decryptor.kt
- src/en/sflix/src/eu/kanade/tachiyomi/animeextension/en/sflix/utils/FindPassword.kt
> SFlix: quick-fix

- src/pt/animesvision/build.gradle
- src/pt/animesvision/src/eu/kanade/tachiyomi/animeextension/pt/animesvision/AnimesVision.kt
- src/pt/animesvision/src/eu/kanade/tachiyomi/animeextension/pt/animesvision/dto/AnimesVisionDto.kt
- src/pt/animesvision/src/eu/kanade/tachiyomi/animeextension/pt/animesvision/extractors/VisionExtractor.kt
> AnimesVision: Fix video extractor

- src/ar/shahid4u/build.gradle
- src/ar/shahid4u/src/eu/kanade/tachiyomi/animeextension/ar/shahid4u/Shahid4U.kt
- src/ar/shahid4u/src/eu/kanade/tachiyomi/animeextension/ar/shahid4u/extractors/OkruExtractor.kt
> fix shahid4u

- lib/okru-extractor/build.gradle.kts
- lib/okru-extractor/src/main/AndroidManifest.xml
- lib/okru-extractor/src/main/java/eu/kanade/tachiyomi/lib/okruextractor/OkruExtractor.kt
Tested on DoramasYT(ES) and Animelek (AR).
> Convert OkruExtractor to shared lib

- src/ar/mycima/build.gradle
- src/ar/mycima/src/eu/kanade/tachiyomi/animeextension/ar/mycima/MyCima.kt
> mycima update url

- lib/streamtape-extractor/build.gradle.kts
- lib/streamtape-extractor/src/main/AndroidManifest.xml
- lib/streamtape-extractor/src/main/java/eu/kanade/tachiyomi/lib/streamtapeextractor/StreamTapeExtractor.kt
Tested on Moviedream(DE) and Animesonline.Ninja(ES).
> Convert StreamTape to shared lib

- src/pt/anitube/build.gradle
- src/pt/anitube/src/eu/kanade/tachiyomi/animeextension/pt/anitube/extractors/AnitubeExtractor.kt
> Anitube: Fix video extractor

- lib/fembed-extractor/build.gradle.kts
- lib/fembed-extractor/src/main/AndroidManifest.xml
- lib/fembed-extractor/src/main/java/eu/kanade/tachiyomi/lib/fembedextractor/FembedExtractor.kt
- lib/fembed-extractor/src/main/java/eu/kanade/tachiyomi/lib/fembedextractor/FembedExtractorDto.kt
Tested on Asia2TV (AR), Animesonline.Ninja (ES) and Animension (EN).
> Convert FembedExtractor to shared lib

- src/pt/puraymoe/build.gradle
- src/pt/puraymoe/src/eu/kanade/tachiyomi/animeextension/pt/puraymoe/PurayMoe.kt
- src/pt/puraymoe/src/eu/kanade/tachiyomi/animeextension/pt/puraymoe/dto/PurayMoeDto.kt
> PurayMoe: Fix video extractor

- src/pt/animesonlinex/build.gradle
- src/pt/animesonlinex/src/eu/kanade/tachiyomi/animeextension/pt/animesonlinex/AnimesOnlineX.kt
> AnimesOnlineX: Update domain

- src/ar/movizland/build.gradle
- src/ar/movizland/src/eu/kanade/tachiyomi/animeextension/ar/movizland/Movizland.kt
> minor-fix movizland

- src/en/animeowl/build.gradle
- src/en/animeowl/src/eu/kanade/tachiyomi/animeextension/en/animeowl/AnimeOwl.kt
> AnimeOwl: Fix preferred quality and language 

- src/ar/animerco/build.gradle
- src/ar/animerco/src/eu/kanade/tachiyomi/animeextension/ar/animerco/Animerco.kt
> animerco: fix vedio extractor and series

- src/en/vidembed/build.gradle
- src/en/vidembed/src/eu/kanade/tachiyomi/animeextension/en/vidembed/Vidembed.kt
- src/en/vidembed/src/eu/kanade/tachiyomi/animeextension/en/vidembed/extractors/MixDropExtractor.kt
- src/en/vidembed/src/eu/kanade/tachiyomi/animeextension/en/vidembed/extractors/XstreamcdnExtractor.kt
> Vidembed: fix broken extractors and add new ones

- src/pt/vizer/build.gradle
- src/pt/vizer/src/eu/kanade/tachiyomi/animeextension/pt/vizer/Vizer.kt
> Feat(Vizer.tv): Add video and language preferences

- src/ar/anime4up/build.gradle
- src/ar/anime4up/src/eu/kanade/tachiyomi/animeextension/ar/anime4up/Anime4Up.kt
- src/ar/anime4up/src/eu/kanade/tachiyomi/animeextension/ar/anime4up/extractors/GdrivePlayerExtractor.kt
- src/ar/anime4up/src/eu/kanade/tachiyomi/animeextension/ar/anime4up/extractors/MoshahdaExtractor.kt
- src/ar/anime4up/src/eu/kanade/tachiyomi/animeextension/ar/anime4up/extractors/SharedExtractor.kt
- src/ar/anime4up/src/eu/kanade/tachiyomi/animeextension/ar/anime4up/extractors/VidBomExtractor.kt
- src/ar/anime4up/src/eu/kanade/tachiyomi/animeextension/ar/anime4up/extractors/VidYardExtractor.kt
- src/ar/animetitans/build.gradle
- src/ar/animetitans/src/eu/kanade/tachiyomi/animeextension/ar/animetitans/AnimeTitans.kt
- src/ar/animetitans/src/eu/kanade/tachiyomi/animeextension/ar/animetitans/extractors/GdrivePlayerExtractor.kt
- src/ar/animetitans/src/eu/kanade/tachiyomi/animeextension/ar/animetitans/extractors/VidYardExtractor.kt
add new extractor for anime4up and animetitans
add vidyard extractor 
Checklist:
> update foe anime4up, animetitans

- src/ar/animerco/build.gradle
- src/ar/animerco/src/eu/kanade/tachiyomi/animeextension/ar/animerco/Animerco.kt
- src/ar/animerco/src/eu/kanade/tachiyomi/animeextension/ar/animerco/extractors/GdrivePlayerExtractor.kt
big fix as the site changed their layout and video url method
add GdrivePlayerExtractor
Checklist:
> animerco : update layout selectors and video extractor

- src/en/superstream/build.gradle
- src/en/superstream/src/eu/kanade/tachiyomi/animeextension/en/superstream/SuperStream.kt
- src/en/superstream/src/eu/kanade/tachiyomi/animeextension/en/superstream/SuperStreamAPI.kt
- remove redundant writer names
- add distinct directors as artist
- fix lint warning
Checklist:
> SuperStream: Add Latest

- src/es/legionanime/build.gradle
- src/es/legionanime/src/eu/kanade/tachiyomi/animeextension/es/legionanime/LegionAnime.kt
> Added preferences [LegionAnime]

- src/ar/movizland/build.gradle
- src/ar/movizland/src/eu/kanade/tachiyomi/animeextension/ar/movizland/Movizland.kt
- src/ar/tuktukcinema/build.gradle
- src/ar/tuktukcinema/src/eu/kanade/tachiyomi/animeextension/ar/tuktukcinema/Tuktukcinema.kt
> fix movizland and tuktukcinema

- src/en/putlocker/build.gradle
- src/en/putlocker/src/eu/kanade/tachiyomi/animeextension/en/putlocker/PutLocker.kt
And optimize some code
Checklist:
> PutLocker: fix full episodes not listing

- src/pt/animesup/build.gradle
- src/pt/animesup/src/eu/kanade/tachiyomi/animeextension/pt/animesup/AnimesUp.kt
> AnimesUp: Add quality pref

- src/ar/tuktukcinema/build.gradle
- src/ar/tuktukcinema/src/eu/kanade/tachiyomi/animeextension/ar/tuktukcinema/Tuktukcinema.kt
> optimize tuktukcinema series search

- src/en/wcofun/build.gradle
- src/en/wcofun/src/eu/kanade/tachiyomi/animeextension/en/wcofun/Wcofun.kt
> Fixed #1031 and #1030

- src/en/sflix/build.gradle
- src/en/sflix/src/eu/kanade/tachiyomi/animeextension/en/sflix/extractors/SFlixExtractor.kt
- src/en/sflix/src/eu/kanade/tachiyomi/animeextension/en/sflix/utils/Decryptor.kt
> Fixed #1026

- src/pt/animesonlinex/build.gradle
- src/pt/animesonlinex/src/eu/kanade/tachiyomi/animeextension/pt/animesonlinex/AnimesOnlineX.kt
> fix(animesonlinex): Update base url

- src/en/superstream/src/eu/kanade/tachiyomi/animeextension/en/superstream/DataModel.kt
- src/en/superstream/src/eu/kanade/tachiyomi/animeextension/en/superstream/SuperStreamAPI.kt
Fix from cloudstream
closes #1061
Checklist:
> SuperStream: Change search url

- src/en/putlocker/build.gradle
- src/en/putlocker/src/eu/kanade/tachiyomi/animeextension/en/putlocker/PutLocker.kt
- src/en/superstream/build.gradle
- src/en/superstream/src/eu/kanade/tachiyomi/animeextension/en/superstream/DataModel.kt
- src/en/superstream/src/eu/kanade/tachiyomi/animeextension/en/superstream/SuperStreamAPI.kt
> SuperStream: Revert sub point type & Putlocker: Fix Search

- src/id/kuramanime/src/eu/kanade/tachiyomi/animeextension/id/kuramanime/Kuramanime.kt
> Kuramanime: Update baseUrl

- src/es/cuevana/build.gradle
- src/es/cuevana/src/eu/kanade/tachiyomi/animeextension/es/cuevana/Cuevana.kt
> Change Cuevana extension baseUrl

- src/es/cuevana/build.gradle
- src/es/cuevana/src/eu/kanade/tachiyomi/animeextension/es/cuevana/Cuevana.kt
> Revert Cuevana extension changes

- lib/fembed-extractor/src/main/java/eu/kanade/tachiyomi/lib/fembedextractor/FembedExtractor.kt
- lib/streamsb-extractor/src/main/java/eu/kanade/tachiyomi/lib/streamsbextractor/StreamSBExtractor.kt
- lib/voe-extractor/src/main/java/eu/kanade/tachiyomi/lib/voeextractor/VoeExtractor.kt
- src/es/animeflv/build.gradle
- src/es/animeflv/src/eu/kanade/tachiyomi/animeextension/es/animeflv/AnimeFlv.kt
- src/es/animelatinohd/build.gradle
- src/es/animelatinohd/src/eu/kanade/tachiyomi/animeextension/es/animelatinohd/AnimeLatinoHD.kt
- src/es/pelisplushd/build.gradle
- src/es/pelisplushd/src/eu/kanade/tachiyomi/animeextension/es/pelisplushd/Pelisplushd.kt
- src/es/pelisplushd/src/eu/kanade/tachiyomi/animeextension/es/pelisplushd/extractors/StreamlareExtractor.kt
> Fixes and Updates (Extensions: AnimeFlv, Animelatinohd, Pelisplushd)

- src/pt/animesup/build.gradle
- src/pt/animesup/src/eu/kanade/tachiyomi/animeextension/pt/animesup/AnimesUp.kt
- src/pt/animesup/src/eu/kanade/tachiyomi/animeextension/pt/animesup/extractors/AnimesUpExtractor.kt
- src/pt/animesup/src/eu/kanade/tachiyomi/animeextension/pt/animesup/extractors/LegacyFunExtractor.kt
> AnimesUp: Fix NPE on video list

- src/es/legionanime/build.gradle
- src/es/legionanime/src/eu/kanade/tachiyomi/animeextension/es/legionanime/LegionAnime.kt
> fix [legionanime]

- src/es/jkanime/build.gradle
- src/es/jkanime/src/eu/kanade/tachiyomi/animeextension/es/jkanime/Jkanime.kt
> fix episode 0 not appear [Jkanime]

- src/es/jkanime/build.gradle
- src/es/jkanime/src/eu/kanade/tachiyomi/animeextension/es/jkanime/Jkanime.kt
- src/es/jkanime/src/eu/kanade/tachiyomi/animeextension/es/jkanime/extractors/JkanimeExtractor.kt
> Jkanime filters and updates

- src/en/rule34video/build.gradle
- src/en/rule34video/src/eu/kanade/tachiyomi/animeextension/en/rule34video/Rule34Video.kt
Tag Filter now works with search, Category Filter and Sort Filter.
Tag Filter can fetch all tags by clicking reset without text.
Fixed Category Filter.
Rewritten some codes.
> Rule34video update

- src/all/kamyroll/build.gradle
- src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/Kamyroll.kt
> Add subtitle preferences for KamyRoll

- src/all/kamyroll/build.gradle
- src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/DataModel.kt
- src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/Kamyroll.kt
> Kamyroll: Fix an error when episode number is a fraction

- src/all/kamyroll/build.gradle
- src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/Kamyroll.kt
> Fix default value for sub type

- src/en/ask4movie/build.gradle
- src/en/ask4movie/src/eu/kanade/tachiyomi/animeextension/en/ask4movie/Ask4Movie.kt
- src/en/ask4movie/src/eu/kanade/tachiyomi/animeextension/en/ask4movie/extractors/CinegrabberExtractor.kt
- src/en/ask4movie/src/eu/kanade/tachiyomi/animeextension/en/ask4movie/extractors/FilemoonExtractor.kt
> Fix ask4movie

- src/en/gogoanime/build.gradle
- src/en/gogoanime/src/eu/kanade/tachiyomi/animeextension/en/gogoanime/GogoAnime.kt
> Add server preference for gogo

- src/en/nineanime/build.gradle
- src/en/nineanime/src/eu/kanade/tachiyomi/animeextension/en/nineanime/JsInterceptor.kt
- src/en/nineanime/src/eu/kanade/tachiyomi/animeextension/en/nineanime/JsVizInterceptor.kt
- src/en/nineanime/src/eu/kanade/tachiyomi/animeextension/en/nineanime/NineAnime.kt
http error depends on how good your network is but with the new js it should be fixed for the most people
> 9Anime: Json error fix & http error fix

- src/pt/animesvision/build.gradle
- src/pt/animesvision/src/eu/kanade/tachiyomi/animeextension/pt/animesvision/AVFilters.kt
> Update years & seasons for AnimesVision

- src/en/zoro/build.gradle
- src/en/zoro/src/eu/kanade/tachiyomi/animeextension/en/zoro/Zoro.kt
- src/en/zoro/src/eu/kanade/tachiyomi/animeextension/en/zoro/ZoroFilters.kt
Checklist:
- Fixes filters for empty search
- Bumps year to 2023
- Add filters for start/end day
- Fixes order for years
> Update filters for zoro

- src/es/animeonlineninja/build.gradle
- src/es/animeonlineninja/src/eu/kanade/tachiyomi/animeextension/es/animeonlineninja/AnimeonlineNinja.kt
> fix anime episodes dont appear [AnimeOnlineNinja]

- src/en/gogoanime/build.gradle
- src/en/gogoanime/src/eu/kanade/tachiyomi/animeextension/en/gogoanime/GogoAnime.kt
Checklist:
Changes
- Updated domain names
- Updated genre filters
Added
- Added filters for recent episode releases
- Added filters for seasons
> Updated domains, added filters for Gogoanime

- src/pt/puraymoe/build.gradle
- src/pt/puraymoe/src/eu/kanade/tachiyomi/animeextension/pt/puraymoe/PurayMoe.kt
- src/pt/puraymoe/src/eu/kanade/tachiyomi/animeextension/pt/puraymoe/dto/PurayMoeDto.kt
> PurayMoe: fix video list

- src/en/marinmoe/build.gradle
- src/en/marinmoe/src/eu/kanade/tachiyomi/animeextension/en/marinmoe/DataModel.kt
- src/en/marinmoe/src/eu/kanade/tachiyomi/animeextension/en/marinmoe/MarinMoe.kt
- src/en/marinmoe/src/eu/kanade/tachiyomi/animeextension/en/marinmoe/MarinMoeFilters.kt
Checklist:
Adds source filter & includes source in anime description.
> Add source filter to marin.moe

- src/en/marinmoe/build.gradle
- src/en/marinmoe/src/eu/kanade/tachiyomi/animeextension/en/marinmoe/DataModel.kt
- src/en/marinmoe/src/eu/kanade/tachiyomi/animeextension/en/marinmoe/MarinMoe.kt
> Add source in video quality for marin.moe

- src/all/kamyroll/build.gradle
- src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/Kamyroll.kt
> Kamyroll: update locale of de-DE

- src/pt/hinatasoul/build.gradle
- src/pt/hinatasoul/src/eu/kanade/tachiyomi/animeextension/pt/hinatasoul/HinataSoul.kt
- src/pt/hinatasoul/src/eu/kanade/tachiyomi/animeextension/pt/hinatasoul/extractors/HinataSoulExtractor.kt
> HinataSoul: fix episode list and video qualities

- src/pt/betteranime/build.gradle
- src/pt/betteranime/src/eu/kanade/tachiyomi/animeextension/pt/betteranime/extractors/BetterAnimeExtractor.kt
> BetterAnime: fix crash at video extractor

- src/all/jellyfin/build.gradle
- src/all/jellyfin/src/eu/kanade/tachiyomi/animeextension/all/jellyfin/Jellyfin.kt
> Fix animedetails for jellyfin

- src/en/nineanime/build.gradle
- src/en/nineanime/src/eu/kanade/tachiyomi/animeextension/en/nineanime/NineAnime.kt
- src/en/nineanime/src/eu/kanade/tachiyomi/animeextension/en/nineanime/NineAnimeFilters.kt
> Add filters to 9anime

- src/en/marinmoe/build.gradle
- src/en/marinmoe/src/eu/kanade/tachiyomi/animeextension/en/marinmoe/DataModel.kt
- src/en/marinmoe/src/eu/kanade/tachiyomi/animeextension/en/marinmoe/MarinMoe.kt
Checklist:
Adds toggle to include/exclude special episodes
> Add toggle for special episodes for marin.moe

- src/it/toonitalia/build.gradle
- src/it/toonitalia/src/eu/kanade/tachiyomi/animeextension/it/toonitalia/Toonitalia.kt
Checklist:
Fixes error on stable preventing details from being loaded
> Fix Toonitalia animedetails on stable

- lib/streamsb-extractor/src/main/java/eu/kanade/tachiyomi/lib/streamsbextractor/StreamSBExtractor.kt
- src/ar/arabseed/build.gradle
- src/ar/arabseed/src/eu/kanade/tachiyomi/animeextension/ar/arabseed/ArabSeed.kt
- src/ar/shahid4u/build.gradle
- src/ar/shahid4u/src/eu/kanade/tachiyomi/animeextension/ar/shahid4u/Shahid4U.kt
> fix arabseed, update base url for Shahed4u , fix streamsb Extractor

- src/en/pactedanime/build.gradle
- src/en/pactedanime/src/eu/kanade/tachiyomi/animeextension/en/pactedanime/pactedanime.kt
> Pactedanime: fixes popular, episode order & images, adds note if filler

- src/en/allanime/build.gradle
- src/en/allanime/src/eu/kanade/tachiyomi/animeextension/en/allanime/AllAnime.kt
> Update hashes for allanime

- src/en/nineanime/build.gradle
- src/en/nineanime/src/eu/kanade/tachiyomi/animeextension/en/nineanime/JsInterceptor.kt
- src/en/nineanime/src/eu/kanade/tachiyomi/animeextension/en/nineanime/JsVizInterceptor.kt
- src/en/nineanime/src/eu/kanade/tachiyomi/animeextension/en/nineanime/JsVrfInterceptor.kt
> 9anime: fix & more reliable

- src/en/bestdubbedanime/build.gradle
- src/en/bestdubbedanime/src/eu/kanade/tachiyomi/animeextension/en/bestdubbedanime/BestDubbedAnime.kt
> BestDubbedAnime: Add support for episodes loaded from cache

- src/it/animeunity/build.gradle
- src/it/animeunity/src/eu/kanade/tachiyomi/animeextension/it/animeunity/AnimeUnity.kt
- src/it/animeunity/src/eu/kanade/tachiyomi/animeextension/it/animeunity/AnimeUnityFilters.kt
- src/it/animeunity/src/eu/kanade/tachiyomi/animeextension/it/animeunity/DataModel.kt
> AnimeUnity: Sort quality, add null check, and update filters

- src/all/kamyroll/build.gradle
- src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/Kamyroll.kt
> Kamyroll: Remove softsub when hardsub is available

- src/id/neonime/build.gradle
- src/id/neonime/src/eu/kanade/tachiyomi/animeextension/id/neonime/NeoNime.kt
- src/id/oploverz/build.gradle
- src/id/oploverz/src/eu/kanade/tachiyomi/animeextension/id/oploverz/Oploverz.kt
- src/id/otakudesu/build.gradle
- src/id/otakudesu/src/eu/kanade/tachiyomi/animeextension/id/otakudesu/OtakuDesu.kt
> [Indonesian extensions] Update baseUrl

- src/id/oploverz/build.gradle
- src/id/oploverz/src/eu/kanade/tachiyomi/animeextension/id/oploverz/Oploverz.kt
> [Oploverz extensions] Update baseUrl

- src/pt/puraymoe/build.gradle
- src/pt/puraymoe/src/eu/kanade/tachiyomi/animeextension/pt/puraymoe/PurayMoe.kt
- src/pt/puraymoe/src/eu/kanade/tachiyomi/animeextension/pt/puraymoe/dto/PurayMoeDto.kt
> PurayMoe: Add support to soft subs

- src/en/allanime/build.gradle
- src/en/allanime/src/eu/kanade/tachiyomi/animeextension/en/allanime/AllAnime.kt
- src/en/allanime/src/eu/kanade/tachiyomi/animeextension/en/allanime/extractors/AllAnimeExtractor.kt
> AllAnime: Add source - AC

- src/en/allanime/build.gradle
- src/en/allanime/src/eu/kanade/tachiyomi/animeextension/en/allanime/extractors/AllAnimeExtractor.kt
> AllAnime: Fix audio for ac-hls

- src/pt/hinatasoul/build.gradle
- src/pt/hinatasoul/src/eu/kanade/tachiyomi/animeextension/pt/hinatasoul/extractors/HinataSoulExtractor.kt
> HinataSoul: Fix video links

- src/en/ask4movie/build.gradle
- src/en/ask4movie/src/eu/kanade/tachiyomi/animeextension/en/ask4movie/Ask4Movie.kt
- src/en/ask4movie/src/eu/kanade/tachiyomi/animeextension/en/ask4movie/extractors/FilemoonExtractor.kt
Checklist:
Fixed episode extraction to work with "new" ui
Added support for subtitles embedded in m3u8 file
Fixed video extraction
> Ask4movie: Fix stuff

- src/es/animeonlineninja/build.gradle
- src/es/animeonlineninja/src/eu/kanade/tachiyomi/animeextension/es/animeonlineninja/AnimeonlineNinja.kt
- src/es/legionanime/build.gradle
- src/es/legionanime/src/eu/kanade/tachiyomi/animeextension/es/legionanime/LegionAnime.kt
- src/es/legionanime/src/eu/kanade/tachiyomi/animeextension/es/legionanime/extractors/Mp4uploadExtractor.kt
- src/es/monoschinos/build.gradle
- src/es/monoschinos/src/eu/kanade/tachiyomi/animeextension/es/monoschinos/MonosChinos.kt
- src/es/monoschinos/src/eu/kanade/tachiyomi/animeextension/es/monoschinos/extractors/Mp4uploadExtractor.kt
- src/es/monoschinos/src/eu/kanade/tachiyomi/animeextension/es/monoschinos/extractors/UploadExtractor.kt
> fixes in [MonosChinos] , [AnimeOnlineNinja] and [LegionAnime]

- src/en/nineanime/build.gradle
- src/en/nineanime/src/eu/kanade/tachiyomi/animeextension/en/nineanime/JsInterceptor.kt
> Nine: Remove timeout

- src/fr/animevostfr/build.gradle
- src/fr/animevostfr/src/eu/kanade/tachiyomi/animeextension/fr/animevostfr/AnimeVostFr.kt
- src/fr/animevostfr/src/eu/kanade/tachiyomi/animeextension/fr/animevostfr/extractors/CdopeExtractor.kt
> AnimeVostFR: Update video extraction, add extractor for Cdope

- src/en/uhdmovies/build.gradle
- src/en/uhdmovies/src/eu/kanade/tachiyomi/animeextension/en/uhdmovies/UHDMovies.kt
Checklist:
Fixes errors occuring sometimes when loading series
Updated selectors for collections
> UHDMovies: Update xss selectors

- src/en/allanime/build.gradle
- src/en/allanime/src/eu/kanade/tachiyomi/animeextension/en/allanime/AllAnime.kt
> AllAnime: Update hashes

- src/id/kuramanime/build.gradle
- src/id/kuramanime/src/eu/kanade/tachiyomi/animeextension/id/kuramanime/Kuramanime.kt
Checklist:
probably fixes #930
> Kuramanime: Update video extraction

- src/id/neonime/build.gradle
- src/id/neonime/src/eu/kanade/tachiyomi/animeextension/id/neonime/NeoNime.kt
- src/id/neonime/src/eu/kanade/tachiyomi/animeextension/id/neonime/extractors/BloggerExtractor.kt
- src/id/neonime/src/eu/kanade/tachiyomi/animeextension/id/neonime/extractors/GdrivePlayerExtractor.kt
- src/id/neonime/src/eu/kanade/tachiyomi/animeextension/id/neonime/extractors/LinkBoxExtractor.kt
- src/id/neonime/src/eu/kanade/tachiyomi/animeextension/id/neonime/extractors/YourUploadExtractor.kt
Checklist:
Most likely fixes #649
> Neonime: Fix video extraction

- src/id/kuronime/build.gradle
- src/id/kuronime/src/eu/kanade/tachiyomi/animeextension/id/kuronime/Kuronime.kt
- src/id/kuronime/src/eu/kanade/tachiyomi/animeextension/id/kuronime/extractors/AnimekuExtractor.kt
- src/id/kuronime/src/eu/kanade/tachiyomi/animeextension/id/kuronime/extractors/HxFileExtractor.kt
- src/id/kuronime/src/eu/kanade/tachiyomi/animeextension/id/kuronime/extractors/LinkBoxExtractor.kt
- src/id/kuronime/src/eu/kanade/tachiyomi/animeextension/id/kuronime/extractors/Mp4uploadExtractor.kt
- src/id/kuronime/src/eu/kanade/tachiyomi/animeextension/id/kuronime/extractors/StreamlareExtractor.kt
- src/id/kuronime/src/eu/kanade/tachiyomi/animeextension/id/kuronime/extractors/YourUploadExtractor.kt
Checklist:
Probably fixes #611 #650
> Kuronime: Fix video extraction

- src/all/jellyfin/build.gradle
- src/all/jellyfin/src/eu/kanade/tachiyomi/animeextension/all/jellyfin/Jellyfin.kt
> Jellyfin: Fix title in details

- src/en/uhdmovies/build.gradle
- src/en/uhdmovies/src/eu/kanade/tachiyomi/animeextension/en/uhdmovies/UHDMovies.kt
> UHDMovies: fix post link

- src/all/kamyroll/build.gradle
- src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/AccessTokenInterceptor.kt
- src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/Consumyroll.kt
- src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/DataModel.kt
> Consumyroll: list dubs versions in scanlator

- src/all/animexin/build.gradle
- src/all/animexin/src/eu/kanade/tachiyomi/animeextension/all/animexin/AnimeXin.kt
- src/all/animexin/src/eu/kanade/tachiyomi/animeextension/all/animexin/extractors/VidstreamingExtractor.kt
> AnimeXin: Add gogo extractor

- src/es/animeflv/build.gradle
- src/es/animeflv/src/eu/kanade/tachiyomi/animeextension/es/animeflv/AnimeFlv.kt
> AnimeFlv: Fix json parsing

- src/all/kamyroll/build.gradle
- src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/Consumyroll.kt
- src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/DataModel.kt
> Consumyroll: apply fixes for stable and fix anime with no versions

- src/de/aniworld/build.gradle
- src/de/aniworld/src/eu/kanade/tachiyomi/animeextension/de/aniworld/AniWorld.kt
- src/de/aniworld/src/eu/kanade/tachiyomi/animeextension/de/aniworld/JsInterceptor.kt
- src/de/aniworld/src/eu/kanade/tachiyomi/animeextension/de/aniworld/RedirectInterceptor.kt
First version of my recaptcha bypasser. Total early stage version.
> AniWorld: add reCapBypass v0.1

- src/en/uhdmovies/build.gradle
- src/en/uhdmovies/src/eu/kanade/tachiyomi/animeextension/en/uhdmovies/UHDMovies.kt
> UHDMovies: update domain & remove domain pref

- src/en/animepahe/build.gradle
- src/en/animepahe/src/eu/kanade/tachiyomi/animeextension/en/animepahe/AnimePahe.kt
- src/en/animepahe/src/eu/kanade/tachiyomi/animeextension/en/animepahe/KwikExtractor.kt
Checklist:
Fix video extraction & video ordering
closes #1277
> Fix animepahe

- src/ar/mycima/build.gradle
- src/ar/mycima/src/eu/kanade/tachiyomi/animeextension/ar/mycima/MyCima.kt
> fix mycima

- src/en/allanime/build.gradle
- src/en/allanime/src/eu/kanade/tachiyomi/animeextension/en/allanime/AllAnime.kt
> AllAnime: Update url

- lib/streamsb-extractor/src/main/java/eu/kanade/tachiyomi/lib/streamsbextractor/StreamSBExtractor.kt
- src/en/allanime/build.gradle
- src/en/allanime/src/eu/kanade/tachiyomi/animeextension/en/allanime/AllAnime.kt
- src/en/allanime/src/eu/kanade/tachiyomi/animeextension/en/allanime/extractors/AllAnimeExtractor.kt
- src/en/allanime/src/eu/kanade/tachiyomi/animeextension/en/allanime/extractors/StreamlareExtractor.kt
Checklist:
Gogo: add url & support if m3u8 isnt a playlist
> AllAnime: Fix gogo, streamlare, add parallel map for external hosts and update streamsb (again)

- src/all/kamyroll/build.gradle
- src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/AccessTokenInterceptor.kt
- src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/Consumyroll.kt
fetch only subbed, english dub (if available) and preferred dub (if available) versions only
Checklist:
> Consumyroll: fix broken token caching

- src/en/nineanime/build.gradle
- src/en/nineanime/src/eu/kanade/tachiyomi/animeextension/en/nineanime/NineAnime.kt
9anime.to domain was blocked for many devices so changed it to 9anime.id
> Updated 9anime.to domains to  9anime.id

- src/pt/vizer/build.gradle
- src/pt/vizer/src/eu/kanade/tachiyomi/animeextension/pt/vizer/Vizer.kt
- src/pt/vizer/src/eu/kanade/tachiyomi/animeextension/pt/vizer/VizerFilters.kt
> Fix vizer.tv search results

- src/pt/subanimes/build.gradle
- src/pt/subanimes/src/eu/kanade/tachiyomi/animeextension/pt/subanimes/SubAnimes.kt
- src/pt/subanimes/src/eu/kanade/tachiyomi/animeextension/pt/subanimes/extractors/SubAnimesExtractor.kt
This PR only fixes unfiltered searches, since the search filter system of the source itself is currently broken.
Checklist:
> Fix subanimes search and video extractor

- src/pt/animeshouse/build.gradle
- src/pt/animeshouse/src/eu/kanade/tachiyomi/animeextension/pt/animeshouse/AnimesHouse.kt
- src/pt/animeshouse/src/eu/kanade/tachiyomi/animeextension/pt/animeshouse/extractors/GenericExtractor.kt
- src/pt/animeshouse/src/eu/kanade/tachiyomi/animeextension/pt/animeshouse/extractors/MpFourDooExtractor.kt
- src/pt/animeshouse/src/eu/kanade/tachiyomi/animeextension/pt/animeshouse/extractors/RedplayBypasser.kt
Checklist:
... and in the tests, i found that this source sometimes provides links to videos that the beta player does not support, playing well only in stable
Good luck to the users of this extension
> AnimesHouse: Show all video qualities + small refactor

- src/en/wcofun/build.gradle
- src/en/wcofun/src/eu/kanade/tachiyomi/animeextension/en/wcofun/RedirectInterceptor.kt
- src/en/wcofun/src/eu/kanade/tachiyomi/animeextension/en/wcofun/Wcofun.kt
> WcoFun: Fix url(s)

- src/en/pactedanime/build.gradle
- src/en/pactedanime/src/eu/kanade/tachiyomi/animeextension/en/pactedanime/pactedanime.kt
> PactedAnime: Update selectors

- lib/yourupload-extractor/build.gradle.kts
- lib/yourupload-extractor/src/main/java/eu/kanade/tachiyomi/lib/youruploadextractor/YourUploadExtractor.kt
> Convert YourUploadExtractor to shared lib

- src/ar/animeblkom/build.gradle
- src/ar/animeblkom/src/eu/kanade/tachiyomi/animeextension/ar/animeblkom/AnimeBlkom.kt
> Animeblkom: Fix video

- src/en/animepahe/build.gradle
- src/en/animepahe/src/eu/kanade/tachiyomi/animeextension/en/animepahe/AnimePahe.kt
Checklist:
Lots of people have reported lag loading popular page. This pr probably fixes this
> AnimePahe: Fix lag for some people

- src/es/animeonlineninja/build.gradle
- src/es/animeonlineninja/src/eu/kanade/tachiyomi/animeextension/es/animeonlineninja/AnimeonlineNinja.kt
- src/es/animeonlineninja/src/eu/kanade/tachiyomi/animeextension/es/animeonlineninja/VrfInterceptor.kt
> AnimeonlineNinja: add js verification bypasser

- src/all/kamyroll/build.gradle
- src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/AccessTokenInterceptor.kt
> Yomiroll: change token location

- src/en/hanime/build.gradle
- src/en/hanime/src/eu/kanade/tachiyomi/animeextension/en/hanime/Hanime.kt
Checklist:
Ugly code but i couldnt care less about this extension
> HAnime: Add login support

- src/en/hanime/build.gradle
- src/en/hanime/src/eu/kanade/tachiyomi/animeextension/en/hanime/Hanime.kt
> HAnime: Add 1080p preference

- src/en/allanime/build.gradle
- src/en/allanime/src/eu/kanade/tachiyomi/animeextension/en/allanime/AllAnime.kt
Checklist:
Still haven't managed to reverse engineer the hashes 😔
> AllAnime: Update hashes & url

- src/en/nineanime/build.gradle
- src/en/nineanime/src/eu/kanade/tachiyomi/animeextension/en/nineanime/NineAnime.kt
and fix some warnings
Checklist:
> Nine: Fix sorting and filter masterplaylist

- src/en/uhdmovies/build.gradle
- src/en/uhdmovies/src/eu/kanade/tachiyomi/animeextension/en/uhdmovies/UHDMovies.kt
> UHDMovies: handle errors and fix some warnings and inconsistencies

- src/all/kamyroll/build.gradle
- src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/AccessTokenInterceptor.kt
- src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/Yomiroll.kt
- src/en/uhdmovies/build.gradle
- src/en/uhdmovies/src/eu/kanade/tachiyomi/animeextension/en/uhdmovies/UHDMovies.kt
> Yomiroll: Fix crash when using new pref

- src/en/rule34video/build.gradle
- src/en/rule34video/src/eu/kanade/tachiyomi/animeextension/en/rule34video/DdosGuardInterceptor.kt
- src/en/rule34video/src/eu/kanade/tachiyomi/animeextension/en/rule34video/Rule34Video.kt
Added DDoSGuardInterceptor
Fixed video playback in Aniyomi MPV Beta
> Added DDoSGuardInterceptor

- .github/scripts/bump-versions.sh
- .github/workflows/build_push.yml
This pr also reapplies the changes on [this commit](https://github.com/jmir1/aniyomi-extensions/commit/3cc19933bf7f79027c2a1fa34491b5a410800d2a), because I accidentally reverted it [here](https://github.com/jmir1/aniyomi-extensions/commit/6572205982ddaa2a1a556ba9cb06d9717bf21a20) xD
> feat(bump-versions.sh): Add support to multisrc

- src/en/hentaimama/build.gradle
- src/en/hentaimama/src/eu/kanade/tachiyomi/animeextension/en/hentaimama/HentaiMama.kt
- src/en/rule34video/build.gradle
- src/en/rule34video/src/eu/kanade/tachiyomi/animeextension/en/rule34video/DdosGuardInterceptor.kt
- src/en/rule34video/src/eu/kanade/tachiyomi/animeextension/en/rule34video/Rule34Video.kt
> Fixed episode list order

- src/all/kamyroll/build.gradle
- src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/DataModel.kt
- src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/Yomiroll.kt
as it is creating more problems than the tracker issue and cr is fixing their duplicate season stuff anyway
Checklist:
> Yomiroll: Remove season grouping

- src/es/pelisplushd/build.gradle
- src/es/pelisplushd/src/eu/kanade/tachiyomi/animeextension/es/pelisplushd/Pelisplushd.kt
> PelisplusHD fixes

- src/en/nineanime/build.gradle
- src/en/nineanime/src/eu/kanade/tachiyomi/animeextension/en/nineanime/NineAnime.kt
and catch any extractor errors
Checklist:
> Nine: Add referer to vizcloud

- src/es/pelisplushd/build.gradle
- src/es/pelisplushd/src/eu/kanade/tachiyomi/animeextension/es/pelisplushd/Pelisplushd.kt
- src/es/pelisplushd/src/eu/kanade/tachiyomi/animeextension/es/pelisplushd/PelisplushdFactory.kt
- src/es/pelisplushd/src/eu/kanade/tachiyomi/animeextension/es/pelisplushd/Pelisplusto.kt
> Pelisplushd updates

- lib/streamsb-extractor/build.gradle.kts
- lib/streamsb-extractor/src/main/AndroidManifest.xml
- lib/streamsb-extractor/src/main/java/eu/kanade/tachiyomi/lib/streamsbextractor/StreamSBExtractor.kt
Tested on AnimeDao(en) and PiFansubs(pt-BR).
> Fix streamsb-extractor lib 

- src/all/netfilm/build.gradle
- src/all/netfilm/src/eu/kanade/tachiyomi/animeextension/all/netfilm/DataModel.kt
- src/all/netfilm/src/eu/kanade/tachiyomi/animeextension/all/netfilm/NetFilm.kt
> Netfilm: Add headers so the extension works

- src/en/nineanime/build.gradle
- src/en/nineanime/src/eu/kanade/tachiyomi/animeextension/en/nineanime/NineAnime.kt
> 9anime: fix vrf name and clean up code

- src/en/allanime/build.gradle
- src/en/allanime/src/eu/kanade/tachiyomi/animeextension/en/allanime/AllAnime.kt
Checklist:
Fixes problem where title would change language on fetchAnimeDetails if user set preferred language
> AllAnime Don't update title on fetchAnimeDetails

- src/en/nineanime/build.gradle
- src/en/nineanime/src/eu/kanade/tachiyomi/animeextension/en/nineanime/NineAnime.kt
> 9anime: add MyCloud server

- src/en/animepahe/build.gradle
- src/en/animepahe/src/eu/kanade/tachiyomi/animeextension/en/animepahe/AnimePahe.kt
- src/en/animepahe/src/eu/kanade/tachiyomi/animeextension/en/animepahe/dto/AnimePaheDto.kt
> AnimePahe: Add fix for non-integer episode numbers

- src/en/nineanime/build.gradle
- src/en/nineanime/src/eu/kanade/tachiyomi/animeextension/en/nineanime/NineAnime.kt
> here kitty kitty kitty (9anime)

- multisrc/overrides/dooplay/cinevision/src/CineVision.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/dooplay/DooPlay.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/dooplay/DooPlayGenerator.kt
Closes #1430 
Checklist:
Note that i havent updated `baseVersionCode` of the DooPlay module, as this PR does not change the existing overrides behaviour.
> feat(multisrc/DooPlay): Make new filters implementation easier

- src/en/allanime/build.gradle
- src/en/allanime/src/eu/kanade/tachiyomi/animeextension/en/allanime/AllAnime.kt
- src/en/allanime/src/eu/kanade/tachiyomi/animeextension/en/allanime/DataModel.kt
Checklist:
🦀 Hashes are gone 🦀
> AllAnime: Remove hashes in favour of queries

- src/all/googledriveindex/build.gradle
- src/all/googledriveindex/src/eu/kanade/tachiyomi/animeextension/all/googledriveindex/GoogleDriveIndex.kt
Checklist:
Properly encode referer url so it doesn't crash on weird utf-8 characters (woops)
Move season text from title to scanlator, makes it easier to read on portrait mode
Add support for sites needing username & password
> GoogleDriveIndex: Fix/add stuff

- src/ar/faselhd/build.gradle
- src/ar/faselhd/src/eu/kanade/tachiyomi/animeextension/ar/faselhd/FASELHD.kt
- src/ar/mycima/build.gradle
- src/ar/mycima/src/eu/kanade/tachiyomi/animeextension/ar/mycima/MyCima.kt
fix Faselhd EpisodeList
Update my cima domain link and add settings for changing the url
Checklist:
> fix Faselhd and mycima

- src/pt/vizer/build.gradle
- src/pt/vizer/src/eu/kanade/tachiyomi/animeextension/pt/vizer/Vizer.kt
- src/pt/vizer/src/eu/kanade/tachiyomi/animeextension/pt/vizer/dto/VizerDto.kt
> Vizer.tv(pt): Fix episode list + refactor

- src/pt/betteranime/build.gradle
- src/pt/betteranime/src/eu/kanade/tachiyomi/animeextension/pt/betteranime/BAFilters.kt
- src/pt/betteranime/src/eu/kanade/tachiyomi/animeextension/pt/betteranime/BetterAnime.kt
> BetterAnime: Change pseudo popular page

- src/es/animeonlineninja/build.gradle
- src/es/animeonlineninja/src/eu/kanade/tachiyomi/animeextension/es/animeonlineninja/AnimeonlineNinja.kt
- src/es/animeonlineninja/src/eu/kanade/tachiyomi/animeextension/es/animeonlineninja/VrfInterceptor.kt
Checklist:
<@585998985261613242>
> fixes in AnimeOnlineNinja

- multisrc/src/main/java/generator/ThemeSourceGenerator.kt
What no proper testing does to a-
> fix: Fix multisrc generation under Windows

- src/all/googledriveindex/build.gradle
- src/all/googledriveindex/src/eu/kanade/tachiyomi/animeextension/all/googledriveindex/DataModel.kt
- src/all/googledriveindex/src/eu/kanade/tachiyomi/animeextension/all/googledriveindex/GoogleDriveIndex.kt
> GoogleDriveIndex: Add support for info & remove accidental ddos

- src/en/hstream/build.gradle
- src/en/hstream/src/eu/kanade/tachiyomi/animeextension/en/hstream/Hstream.kt
> Hstream : Fixed not showing in series format.

- src/all/googledriveindex/build.gradle
- src/all/googledriveindex/src/eu/kanade/tachiyomi/animeextension/all/googledriveindex/GoogleDriveIndex.kt
> GoogleDriveIndex: More fixes

- lib/vidbom-extractor/build.gradle.kts
- lib/vidbom-extractor/src/main/java/eu/kanade/tachiyomi/lib/vidbomextractor/VidBomExtractor.kt
> feat: Convert VidBomExtractor to shared lib

- lib/streamsb-extractor/src/main/java/eu/kanade/tachiyomi/lib/streamsbextractor/StreamSBExtractor.kt
> fix(StreamSB): Update API endpoint

- src/en/superstream/build.gradle
- src/en/superstream/src/eu/kanade/tachiyomi/animeextension/en/superstream/SuperStream.kt
> SuperStream: Clean up writers and directors

- src/ar/anime4up/build.gradle
- src/ar/anime4up/src/eu/kanade/tachiyomi/animeextension/ar/anime4up/Anime4Up.kt
> minor fixes for anime4up

- src/en/uhdmovies/build.gradle
- src/en/uhdmovies/src/eu/kanade/tachiyomi/animeextension/en/uhdmovies/UHDMovies.kt
> UHDMovies: Re add the redirect shenanigan

- src/es/cuevana/build.gradle
- src/es/cuevana/src/eu/kanade/tachiyomi/animeextension/es/cuevana/Cuevana.kt
- src/es/pelisplushd/build.gradle
- src/es/pelisplushd/src/eu/kanade/tachiyomi/animeextension/es/pelisplushd/Pelisplushd.kt
- src/es/pelisplushd/src/eu/kanade/tachiyomi/animeextension/es/pelisplushd/Pelisplusto.kt
Checklist:
Closes #1344, closes #1322
> Cuevana & PelisPlus: Fixes in video extractors

- src/pt/megaflix/build.gradle
- src/pt/megaflix/src/eu/kanade/tachiyomi/animeextension/pt/megaflix/Megaflix.kt
Closes #1497 
Checklist:
I forgot to consider series with multiple seasons xd
> fix(pt/megaflix): Show all episodes properly

- src/all/googledriveindex/build.gradle
- src/all/googledriveindex/src/eu/kanade/tachiyomi/animeextension/all/googledriveindex/GoogleDriveIndex.kt
> GDIndex: Fix stuff

- src/en/myanime/build.gradle
- src/en/myanime/src/eu/kanade/tachiyomi/animeextension/en/myanime/Myanime.kt
- src/en/myanime/src/eu/kanade/tachiyomi/animeextension/en/myanime/extractors/GdrivePlayerExtractor.kt
> Myanime: Add gdriveplayer

- lib/okru-extractor/src/main/java/eu/kanade/tachiyomi/lib/okruextractor/OkruExtractor.kt
- src/en/allanime/build.gradle
- src/en/allanime/src/eu/kanade/tachiyomi/animeextension/en/allanime/AllAnime.kt
- src/en/allanime/src/eu/kanade/tachiyomi/animeextension/en/allanime/extractors/AllAnimeExtractor.kt
- src/en/allanime/src/eu/kanade/tachiyomi/animeextension/en/allanime/extractors/StreamlareExtractor.kt
> AllAnime: New server

- src/en/kickassanime/build.gradle
- src/en/kickassanime/src/eu/kanade/tachiyomi/animeextension/en/kickassanime/KickAssAnime.kt
- src/en/kickassanime/src/eu/kanade/tachiyomi/animeextension/en/kickassanime/KickAssAnimeFilters.kt
- src/en/kickassanime/src/eu/kanade/tachiyomi/animeextension/en/kickassanime/dto/KickAssAnimeDto.kt
- src/en/kickassanime/src/eu/kanade/tachiyomi/animeextension/en/kickassanime/extractors/KickAssAnimeExtractor.kt
Checklist:
- Added server preference
- Added audio language preference
- Fixed dash video not having audio
- Added subpage to filters
> KickAssAnime: Fix stuff

- src/en/kayoanime/build.gradle
- src/en/kayoanime/src/eu/kanade/tachiyomi/animeextension/en/kayoanime/DriveIndexExtractor.kt
- src/en/kayoanime/src/eu/kanade/tachiyomi/animeextension/en/kayoanime/Kayoanime.kt
> Kayoanime - improve naming & add support for google drive index

- src/en/kayoanime/build.gradle
- src/en/kayoanime/src/eu/kanade/tachiyomi/animeextension/en/kayoanime/Kayoanime.kt
> Kayoanime: Replace scraper with a better one

- src/en/gogoanime/build.gradle
- src/en/gogoanime/src/eu/kanade/tachiyomi/animeextension/en/gogoanime/GogoAnime.kt
> Added new Gogoanime Domains

- src/en/kickassanime/build.gradle
- src/en/kickassanime/src/eu/kanade/tachiyomi/animeextension/en/kickassanime/KickAssAnime.kt
- src/en/kickassanime/src/eu/kanade/tachiyomi/animeextension/en/kickassanime/extractors/AESKeyExtractor.kt
- src/en/kickassanime/src/eu/kanade/tachiyomi/animeextension/en/kickassanime/extractors/KickAssAnimeExtractor.kt
Checklist:
Maybe God will forgive me for the atrocities i just have committed.
> feat(KAA): Implement dynamic AES key extractor

- src/en/nineanime/build.gradle
- src/en/nineanime/src/eu/kanade/tachiyomi/animeextension/en/nineanime/NineAnime.kt
> Added 9anime new domain & Removed Dead Domain

- src/pt/animesroll/build.gradle
- src/pt/animesroll/src/eu/kanade/tachiyomi/animeextension/pt/animesroll/AnimesROLL.kt
- src/pt/animesroll/src/eu/kanade/tachiyomi/animeextension/pt/animesroll/dto/AnimesROLLDto.kt
> fix(AnimesROLL): Solve serialization problems

- src/en/animepahe/build.gradle
- src/en/animepahe/src/eu/kanade/tachiyomi/animeextension/en/animepahe/AnimePahe.kt
> fix(AnimePahe): Fix problems with webview/sharing animes

- src/all/googledrive/build.gradle
- src/all/googledrive/src/eu/kanade/tachiyomi/animeextension/all/googledrive/GoogleDrive.kt
Checklist:
- Improve error handling
- Give more verbose errors if something goes wrong
- Fix webview not opening correctly
- Improve regex for more types of folder urls
> Google drive: Fix stuff

- src/en/kisskh/build.gradle
- src/en/kisskh/src/eu/kanade/tachiyomi/animeextension/en/kisskh/KissKH.kt
> KissKH: update domain and fix episode order

- src/en/bestdubbedanime/build.gradle
- src/en/bestdubbedanime/src/eu/kanade/tachiyomi/animeextension/en/bestdubbedanime/BestDubbedAnime.kt
> BestDubbedAnime: Change video extraction

- lib/streamsb-extractor/build.gradle.kts
- lib/streamsb-extractor/src/main/java/eu/kanade/tachiyomi/lib/streamsbextractor/StreamSBExtractor.kt
Cheating a bit with github actions
> feat(lib/StreamSB): Get API endpoint dynamically

- src/en/animeflix/build.gradle
- src/en/animeflix/src/eu/kanade/tachiyomi/animeextension/en/animeflix/AnimeFlix.kt
> AnimeFlix: Update domain

- src/en/hentaimama/build.gradle
- src/en/hentaimama/src/eu/kanade/tachiyomi/animeextension/en/hentaimama/HentaiMama.kt
> HentaiMama.to : Added support to all available Mirror.

- lib/unpacker/build.gradle.kts
- lib/unpacker/src/main/java/eu/kanade/tachiyomi/lib/unpacker/SubstringExtractor.kt
- lib/unpacker/src/main/java/eu/kanade/tachiyomi/lib/unpacker/Unpacker.kt
Imagine using dev.datlag.jsunpacker, couldn't be me
> feat(lib): Stole (Js)Unpacker lib from tachiyomi-extensions repo

- lib/mixdrop-extractor/build.gradle.kts
- lib/mixdrop-extractor/src/main/java/eu/kanade/tachiyomi/lib/mixdropextractor/MixDropExtractor.kt
Requires #1551 to compile and work
> [skip ci] feat(lib): Convert Mixdrop extractor into a shared lib

- src/tr/turkanime/build.gradle
- src/tr/turkanime/src/eu/kanade/tachiyomi/animeextension/tr/turkanime/TurkAnime.kt
- src/tr/turkanime/src/eu/kanade/tachiyomi/animeextension/tr/turkanime/extractors/AlucardExtractor.kt
- src/tr/turkanime/src/eu/kanade/tachiyomi/animeextension/tr/turkanime/extractors/EmbedgramExtractor.kt
- src/tr/turkanime/src/eu/kanade/tachiyomi/animeextension/tr/turkanime/extractors/FilemoonExtractor.kt
- src/tr/turkanime/src/eu/kanade/tachiyomi/animeextension/tr/turkanime/extractors/GoogleDriveExtractor.kt
- src/tr/turkanime/src/eu/kanade/tachiyomi/animeextension/tr/turkanime/extractors/MVidooExtractor.kt
- src/tr/turkanime/src/eu/kanade/tachiyomi/animeextension/tr/turkanime/extractors/MailRuExtractor.kt
- src/tr/turkanime/src/eu/kanade/tachiyomi/animeextension/tr/turkanime/extractors/Mp4uploadExtractor.kt
- src/tr/turkanime/src/eu/kanade/tachiyomi/animeextension/tr/turkanime/extractors/MytvExtractor.kt
- src/tr/turkanime/src/eu/kanade/tachiyomi/animeextension/tr/turkanime/extractors/SendvidExtractor.kt
- src/tr/turkanime/src/eu/kanade/tachiyomi/animeextension/tr/turkanime/extractors/SibnetExtractor.kt
- src/tr/turkanime/src/eu/kanade/tachiyomi/animeextension/tr/turkanime/extractors/StreamVidExtractor.kt
- src/tr/turkanime/src/eu/kanade/tachiyomi/animeextension/tr/turkanime/extractors/UqloadExtractor.kt
- src/tr/turkanime/src/eu/kanade/tachiyomi/animeextension/tr/turkanime/extractors/VTubeExtractor.kt
- src/tr/turkanime/src/eu/kanade/tachiyomi/animeextension/tr/turkanime/extractors/VkExtractor.kt
- src/tr/turkanime/src/eu/kanade/tachiyomi/animeextension/tr/turkanime/extractors/VudeoExtractor.kt
- src/tr/turkanime/src/eu/kanade/tachiyomi/animeextension/tr/turkanime/extractors/WolfstreamExtractor.kt
> Turkanime: Add some sources

- src/all/googledrive/build.gradle
- src/all/googledrive/src/eu/kanade/tachiyomi/animeextension/all/googledrive/GoogleDrive.kt
- src/all/googledrive/src/eu/kanade/tachiyomi/animeextension/all/googledrive/extractors/GoogleDriveExtractor.kt
- src/en/kayoanime/build.gradle
- src/en/kayoanime/src/eu/kanade/tachiyomi/animeextension/en/kayoanime/Kayoanime.kt
- src/en/kayoanime/src/eu/kanade/tachiyomi/animeextension/en/kayoanime/extractors/GoogleDriveExtractor.kt
- src/en/ripcrabbyanime/build.gradle
- src/en/ripcrabbyanime/src/eu/kanade/tachiyomi/animeextension/en/ripcrabbyanime/Ripcrabbyanime.kt
- src/en/ripcrabbyanime/src/eu/kanade/tachiyomi/animeextension/en/ripcrabbyanime/extractors/GoogleDriveExtractor.kt
> Update google drive extractor

- src/all/kamyroll/build.gradle
- src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/Yomiroll.kt
> fix(Yomiroll): Fix coroutine bug in episodes list

- src/en/ripcrabbyanime/build.gradle
- src/en/ripcrabbyanime/src/eu/kanade/tachiyomi/animeextension/en/ripcrabbyanime/Ripcrabbyanime.kt
> Ripcrabbyanime: Update url

- src/ar/animeblkom/build.gradle
- src/ar/animeblkom/src/eu/kanade/tachiyomi/animeextension/ar/animeblkom/AnimeBlkom.kt
- src/ar/animeblkom/src/eu/kanade/tachiyomi/animeextension/ar/animeblkom/extractors/Mp4uploadExtractor.kt
> fix(ar/animeblkom): Fix thumbnails & video extractor

- lib/gdriveplayer-extractor/build.gradle.kts
- lib/gdriveplayer-extractor/src/main/java/eu/kanade/tachiyomi/lib/gdriveplayerextractor/GdrivePlayerExtractor.kt
I tested it with, like, 5 links, but none of them had any subtitles, so i caaaant say with confidence that i didnt broke something.
> feat(lib): Convert GdrivePlayerExtractor to shared lib

- src/all/googledrive/build.gradle
- src/all/googledrive/src/eu/kanade/tachiyomi/animeextension/all/googledrive/GoogleDrive.kt
Checklist:
Replaces search function with "Add single folder" filter, which should be retrieved from the website's search function inside webview
> Google Drive: Replace search with better implementation

- lib/cloudflare-interceptor/src/main/java/eu/kanade/tachiyomi/lib/cloudflareinterceptor/CloudflareInterceptor.kt
- lib/cryptoaes/src/main/java/eu/kanade/tachiyomi/lib/cryptoaes/CryptoAES.kt
- lib/dataimage/src/main/java/eu/kanade/tachiyomi/lib/dataimage/DataImageInterceptor.kt
- lib/dood-extractor/src/main/java/eu/kanade/tachiyomi/lib/doodextractor/DoodExtractor.kt
- lib/fembed-extractor/build.gradle.kts
- lib/fembed-extractor/src/main/java/eu/kanade/tachiyomi/lib/fembedextractor/FembedExtractor.kt
- lib/fembed-extractor/src/main/java/eu/kanade/tachiyomi/lib/fembedextractor/FembedExtractorDto.kt
- lib/mixdrop-extractor/build.gradle.kts
- lib/okru-extractor/build.gradle.kts
- lib/okru-extractor/src/main/java/eu/kanade/tachiyomi/lib/okruextractor/OkruExtractor.kt
- lib/streamsb-extractor/src/main/java/eu/kanade/tachiyomi/lib/streamsbextractor/StreamSBExtractor.kt
- lib/streamsb-extractor/src/main/java/eu/kanade/tachiyomi/lib/streamsbextractor/StreamSBExtractorDto.kt
- lib/streamtape-extractor/src/main/java/eu/kanade/tachiyomi/lib/streamtapeextractor/StreamTapeExtractor.kt
- lib/synchrony/src/main/java/eu/kanade/tachiyomi/lib/synchrony/Deobfuscator.kt
- lib/yourupload-extractor/src/main/java/eu/kanade/tachiyomi/lib/youruploadextractor/YourUploadExtractor.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/dooplay/DooPlay.kt
I was bored and did this just to kill time, but now I'm bored again :pain:
> [skip ci] refactor(lib): General refactoration

- src/es/legionanime/build.gradle
- src/es/legionanime/src/eu/kanade/tachiyomi/animeextension/es/legionanime/LegionAnime.kt
- src/es/legionanime/src/eu/kanade/tachiyomi/animeextension/es/legionanime/extractors/UqloadExtractor.kt
> LegionAnime: Added more extractors and now the thumbnail is in hd

- src/es/fanpelis/build.gradle
- src/es/fanpelis/src/eu/kanade/tachiyomi/animeextension/es/fanpelis/FanPelis.kt
> FanPelis: Video extractor updates

- src/de/aniworld/build.gradle
- src/de/aniworld/src/eu/kanade/tachiyomi/animeextension/de/aniworld/JsInterceptor.kt
- src/de/serienstream/build.gradle
- src/de/serienstream/src/eu/kanade/tachiyomi/animeextension/de/serienstream/JsInterceptor.kt
- Prevents 404 status loop & small changes
- add to aniworld & serienstream
> Update ReCapBypass to v1.1

- src/es/legionanime/build.gradle
- src/es/legionanime/src/eu/kanade/tachiyomi/animeextension/es/legionanime/LegionAnime.kt
- src/es/legionanime/src/eu/kanade/tachiyomi/animeextension/es/legionanime/Utils.kt
- src/es/legionanime/src/eu/kanade/tachiyomi/animeextension/es/legionanime/extractors/JkanimeExtractor.kt
Checklist:
<:oogabooga:1101887273227796611>
> LegionAnime: small changes

- src/en/holamovies/build.gradle
- src/en/holamovies/src/eu/kanade/tachiyomi/animeextension/en/holamovies/extractors/GDBotExtractor.kt
- src/en/holamovies/src/eu/kanade/tachiyomi/animeextension/en/holamovies/extractors/GDFlixExtractor.kt
- src/en/holamovies/src/eu/kanade/tachiyomi/animeextension/en/holamovies/extractors/GDTotExtractor.kt
> Holamovies: Update video extraction

- src/es/animelatinohd/build.gradle
- src/es/animelatinohd/src/eu/kanade/tachiyomi/animeextension/es/animelatinohd/AnimeLatinoHD.kt
- src/es/animelatinohd/src/eu/kanade/tachiyomi/animeextension/es/animelatinohd/extractors/FilemoonExtractor.kt
- src/es/animelatinohd/src/eu/kanade/tachiyomi/animeextension/es/animelatinohd/extractors/JsUnpacker.kt
> AnimeLatinoHd: Update video extraction

- src/es/pelisplushd/build.gradle
- src/es/pelisplushd/src/eu/kanade/tachiyomi/animeextension/es/pelisplushd/Pelisplushd.kt
- src/es/pelisplushd/src/eu/kanade/tachiyomi/animeextension/es/pelisplushd/PelisplushdFactory.kt
- src/es/pelisplushd/src/eu/kanade/tachiyomi/animeextension/es/pelisplushd/Pelisplusph.kt
- src/es/pelisplushd/src/eu/kanade/tachiyomi/animeextension/es/pelisplushd/extractors/FilemoonExtractor.kt
- src/es/pelisplushd/src/eu/kanade/tachiyomi/animeextension/es/pelisplushd/extractors/JsUnpacker.kt
> Pelisplushd: New source added to Factory

- src/en/kayoanime/build.gradle
- src/en/kayoanime/src/eu/kanade/tachiyomi/animeextension/en/kayoanime/Kayoanime.kt
- src/en/ripcrabbyanime/build.gradle
- src/en/ripcrabbyanime/src/eu/kanade/tachiyomi/animeextension/en/ripcrabbyanime/Ripcrabbyanime.kt
> Improve error messages for sites using google drive

- src/en/allanime/build.gradle
- src/en/allanime/src/eu/kanade/tachiyomi/animeextension/en/allanime/AllAnime.kt
- src/en/allanime/src/eu/kanade/tachiyomi/animeextension/en/allanime/DataModel.kt
> AllAnime: Fix open in webview & add another internal host

- src/pt/animeszone/build.gradle
- src/pt/animeszone/src/eu/kanade/tachiyomi/animeextension/pt/animeszone/AnimesZone.kt
- src/pt/animeszone/src/eu/kanade/tachiyomi/animeextension/pt/animeszone/extractors/BloggerJWPlayerExtractor.kt
> AnimesZone: Update video extraction

- src/en/animekaizoku/build.gradle
- src/en/animekaizoku/src/eu/kanade/tachiyomi/animeextension/en/animekaizoku/AnimeKaizoku.kt
> AnimeKaizoku: Add proper search

- src/all/jellyfin/build.gradle
- src/all/jellyfin/src/eu/kanade/tachiyomi/animeextension/all/jellyfin/DataModel.kt
- src/all/jellyfin/src/eu/kanade/tachiyomi/animeextension/all/jellyfin/Jellyfin.kt
> Jellyfin: Add support for external subs

- multisrc/overrides/dooplay/cinevision/additional.gradle
- multisrc/overrides/dooplay/cinevision/src/CineVision.kt
- multisrc/overrides/dooplay/cinevision/src/extractors/EmbedflixExtractor.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/dooplay/DooPlayGenerator.kt
Checklist:
Unfortunately i had to use datlag jsunpacker, tachiyomi's unpacker betrayed me AAAAAAAAAAAAAAAAAAAA
> fix(pt/CineVision): Fix latest updates and video extractor

- multisrc/overrides/dooplay/animesfoxbr/src/AnimesFoxBR.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/dooplay/DooPlayGenerator.kt
> fix(pt/AnimesfoxBR): Fix video extractor

- src/en/zoro/build.gradle
- src/en/zoro/src/eu/kanade/tachiyomi/animeextension/en/zoro/Zoro.kt
> Zoro: Add alternative domains

- src/en/animepahe/build.gradle
- src/en/animepahe/src/eu/kanade/tachiyomi/animeextension/en/animepahe/AnimePahe.kt
> AnimePahe: New sorting stuff

- src/en/kickassanime/build.gradle
- src/en/kickassanime/src/eu/kanade/tachiyomi/animeextension/en/kickassanime/KickAssAnime.kt
- src/en/kickassanime/src/eu/kanade/tachiyomi/animeextension/en/kickassanime/dto/KickAssAnimeDto.kt
- src/en/kickassanime/src/eu/kanade/tachiyomi/animeextension/en/kickassanime/extractors/AESKeyExtractor.kt
- src/en/kickassanime/src/eu/kanade/tachiyomi/animeextension/en/kickassanime/extractors/KickAssAnimeExtractor.kt
Checklist:
Let's pray that `AESKeyExtractor` doesn't break soon...
> fix(en/KickAssAnime): Fix video extractor

- src/de/filmpalast/build.gradle
- src/de/filmpalast/src/eu/kanade/tachiyomi/animeextension/de/filmpalast/FilmPalast.kt
- src/de/filmpalast/src/eu/kanade/tachiyomi/animeextension/de/filmpalast/extractors/StreamHideVidExtractor.kt
> feat(de/FilmPalast): Add more video extractors

- src/pt/anitube/build.gradle
- src/pt/anitube/src/eu/kanade/tachiyomi/animeextension/pt/anitube/extractors/AnitubeExtractor.kt
> fix(pt/Anitube): Fix video links

- src/it/animeworld/build.gradle
- src/it/animeworld/src/eu/kanade/tachiyomi/animeextension/it/animeworld/ANIMEWORLD.kt
- src/it/animeworld/src/eu/kanade/tachiyomi/animeextension/it/animeworld/extractors/FilemoonExtractor.kt
- src/it/animeworld/src/eu/kanade/tachiyomi/animeextension/it/animeworld/extractors/StreamHideExtractor.kt
Checklist:
probably closes #446
> Animeworld: Add servers

- src/it/animeworld/build.gradle
- src/it/animeworld/src/eu/kanade/tachiyomi/animeextension/it/animeworld/ANIMEWORLD.kt
> Animeworld: Add server preference

- src/ar/faselhd/build.gradle
- src/ar/faselhd/src/eu/kanade/tachiyomi/animeextension/ar/faselhd/FASELHD.kt
- src/ar/tuktukcinema/build.gradle
- src/ar/tuktukcinema/src/eu/kanade/tachiyomi/animeextension/ar/tuktukcinema/Tuktukcinema.kt
> update base url for FASELHD, TukTukCinema

- src/ar/witanime/build.gradle
- src/ar/witanime/src/eu/kanade/tachiyomi/animeextension/ar/witanime/WitAnime.kt
- src/ar/witanime/src/eu/kanade/tachiyomi/animeextension/ar/witanime/extractors/DailymotionExtractor.kt
> [WitAnime] adding dailymotion extractor

- src/ar/tuktukcinema/build.gradle
- src/ar/tuktukcinema/src/eu/kanade/tachiyomi/animeextension/ar/tuktukcinema/Tuktukcinema.kt
it changes its base URL often due to some restrictions so this should help people not wait for update
Checklist:
> [TukTukCinema] Ability to override default baseURL

- src/en/gogoanime/build.gradle
- src/en/gogoanime/src/eu/kanade/tachiyomi/animeextension/en/gogoanime/GogoAnime.kt
- src/en/uhdmovies/build.gradle
- src/en/uhdmovies/src/eu/kanade/tachiyomi/animeextension/en/uhdmovies/UHDMovies.kt
- src/en/vidembed/build.gradle
- src/en/vidembed/src/eu/kanade/tachiyomi/animeextension/en/vidembed/Membed.kt
> Updated domain urls

- src/en/uhdmovies/build.gradle
- src/en/uhdmovies/src/eu/kanade/tachiyomi/animeextension/en/uhdmovies/UHDMovies.kt
> UHDMovies: update video extractor

- src/id/otakudesu/build.gradle
- src/id/otakudesu/src/eu/kanade/tachiyomi/animeextension/id/otakudesu/OtakuDesu.kt
Closes #954 
Closes #648 
Checklist:
> fix(id/OtakuDesu): Fix video extractor + refactor

- src/en/gogoanime/build.gradle
- src/en/gogoanime/src/eu/kanade/tachiyomi/animeextension/en/gogoanime/GogoAnime.kt
- src/en/gogoanime/src/eu/kanade/tachiyomi/animeextension/en/gogoanime/extractors/Mp4uploadExtractor.kt
> feat(gogoanime): add mp4upload + parallelize + hoster toggles, refactoring

- src/ar/witanime/build.gradle
- src/ar/witanime/src/eu/kanade/tachiyomi/animeextension/ar/witanime/WitAnime.kt
- src/ar/witanime/src/eu/kanade/tachiyomi/animeextension/ar/witanime/extractors/DailymotionExtractor.kt
- src/ar/witanime/src/eu/kanade/tachiyomi/animeextension/ar/witanime/extractors/SoraPlayExtractor.kt
> feat(ar/WitAnime): Add Okru extractor + general refactoration

- src/ar/arabseed/build.gradle
- src/ar/arabseed/src/eu/kanade/tachiyomi/animeextension/ar/arabseed/ArabSeed.kt
Checklist:
thankfully just updating the base url was enough to make the video extractor work 🛐
> fix(ar/Arabseed): Update baseUrl + refactor

- src/en/uhdmovies/build.gradle
- src/en/uhdmovies/src/eu/kanade/tachiyomi/animeextension/en/uhdmovies/UHDMovies.kt
> UHDMovies: update domain and add domain entry pref

- src/en/gogoanime/build.gradle
- src/en/gogoanime/src/eu/kanade/tachiyomi/animeextension/en/gogoanime/GogoAnime.kt
- src/en/tokuzilla/build.gradle
Checklist:
Gogo changes their domains a lot, so to save on frequent updates we'll let users update the domain whenever it changes
> Gogoanime: Add preference for domain

- src/en/animeflix/build.gradle
- src/en/animeflix/src/eu/kanade/tachiyomi/animeextension/en/animeflix/AnimeFlix.kt
- src/en/tokuzilla/build.gradle
> Animeflix: Add support for multiple seasons

- src/ar/witanime/build.gradle
- src/ar/witanime/src/eu/kanade/tachiyomi/animeextension/ar/witanime/WitAnime.kt
> fix(ar/WitAnime): Fix episode list when coming from latest updates page

- src/ar/egydead/build.gradle
- src/ar/egydead/src/eu/kanade/tachiyomi/animeextension/ar/egydead/EgyDead.kt
> fix(ar/Egydead): Use runCatching block on video extractor

- src/en/kawaiifu/build.gradle
- src/en/kawaiifu/src/eu/kanade/tachiyomi/animeextension/en/kawaiifu/Kawaiifu.kt
- src/en/tokuzilla/build.gradle
Checklist:
Refactor, improve episode extraction
Users with animes in library may have to refresh episode list for stuff to work
> feat(en/kawaiifu): Rework extension

- src/en/animeflix/build.gradle
- src/en/animeflix/src/eu/kanade/tachiyomi/animeextension/en/animeflix/AnimeFlix.kt
> fix(en/animeflix): Improve handling of multiple seasons

- src/en/animension/build.gradle
- src/en/animension/src/eu/kanade/tachiyomi/animeextension/en/animension/Animension.kt
- src/en/asianload/build.gradle
- src/en/asianload/src/eu/kanade/tachiyomi/animeextension/en/asianload/AsianLoad.kt
- src/en/dramacool/build.gradle
- src/en/dramacool/src/eu/kanade/tachiyomi/animeextension/en/dramacool/DramaCool.kt
> Animension, Asianload, Dramacool Updates

- .github/workflows/build_pull_request.yml
i have given up on branch protection rules
> [skip ci] fix(workflows): remove useless and broken status thing

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/report_issue.yml
- .github/ISSUE_TEMPLATE/request_feature.yml
- .github/ISSUE_TEMPLATE/request_meta.yml
- .github/ISSUE_TEMPLATE/request_source.yml
- .github/scripts/commit-repo.sh
- .github/workflows/build_push.yml
- CONTRIBUTING.md
- README.md
- src/en/animeflix/src/eu/kanade/tachiyomi/animeextension/en/animeflix/AnimeFlix.kt
OBS: Links related to extensions-lib were not updated, as it wasn't migrated to aniyomiorg(....yet?)
> chore: Update repo links to aniyomiorg

- src/all/googledrive/README.md
Update README.md to fix formatting and clear up a few things
Checklist:
> fix(all/googledrive): Update README.md

- src/es/animefenix/build.gradle
- src/es/animefenix/src/eu/kanade/tachiyomi/animeextension/es/animefenix/Animefenix.kt
> fix [AnimeFenix]

- src/en/dramacool/build.gradle
- src/en/dramacool/src/eu/kanade/tachiyomi/animeextension/en/dramacool/DramaCool.kt
Checklist:
Closes #895
Probably closes #576
> fix(en/dramacool): fix urls & refactor

- src/en/nineanime/build.gradle
- src/en/nineanime/src/eu/kanade/tachiyomi/animeextension/en/nineanime/NineAnime.kt
- src/en/nineanime/src/eu/kanade/tachiyomi/animeextension/en/nineanime/extractors/Mp4uploadExtractor.kt
> fix(en/nineanime): Update mp4upload extractor, add preference to toggle hosts, small refactor

- src/it/aniplay/build.gradle
- src/it/aniplay/src/eu/kanade/tachiyomi/animeextension/it/aniplay/AniPlay.kt
- src/it/aniplay/src/eu/kanade/tachiyomi/animeextension/it/aniplay/AniPlayDto.kt
Checklist:
Anime will now correctly open in webview
Closes #1755
> fix(it/aniplay): update baseurl, refactor, and fix open in webview

- src/en/nineanime/build.gradle
- src/en/nineanime/src/eu/kanade/tachiyomi/animeextension/en/nineanime/NineAnime.kt
> Update new 9Anime domains

- src/ko/aniweek/build.gradle
- src/ko/aniweek/src/eu/kanade/tachiyomi/animeextension/ko/aniweek/Aniweek.kt
> fix(ko/aniweek): fix iframe stuff, small code refactor

- multisrc/overrides/dooplay/multimovies/src/Multimovies.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/dooplay/DooPlayGenerator.kt
Checklist:
This site likes to update their domain quite often
Closes #1783
> fix(dooplay/multimovies): update url and make it overridable

- src/en/uhdmovies/build.gradle
- src/en/uhdmovies/src/eu/kanade/tachiyomi/animeextension/en/uhdmovies/UHDMovies.kt
> feat(en/uhdmovies): add redirect handler back for baseUrl

- src/en/allanime/build.gradle
- src/en/allanime/src/eu/kanade/tachiyomi/animeextension/en/allanime/AllAnime.kt
- src/en/allanime/src/eu/kanade/tachiyomi/animeextension/en/allanime/AllAnimeDecryptor.kt
- src/en/allanime/src/eu/kanade/tachiyomi/animeextension/en/allanime/extractors/AllAnimeExtractor.kt
> fix(en/allanime): fix allanime-extractor, update urls, and make the extension actually work

- src/all/animeworldindia/build.gradle
- src/all/animeworldindia/src/eu/kanade/tachiyomi/animeextension/all/animeworldindia/AnimeWorldIndia.kt
- src/all/animeworldindia/src/eu/kanade/tachiyomi/animeextension/all/animeworldindia/AnimeWorldIndiaFilters.kt
Changes
---
- Fixed search parameters not working
- Fixed an edge case issue wherein one of the seasons didn't support the language and thus threw a null pointer exception
Closes #1802 
Checklist:
> fix(AnimeWorldIndia/hi): fix search and edge case

- multisrc/overrides/dooplay/animesfoxbr/src/AnimesFoxBR.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/dooplay/DooPlayGenerator.kt
> fix(pt/animesfoxbr): Update baseUrl

- src/ar/animeblkom/build.gradle
- src/ar/animeblkom/src/eu/kanade/tachiyomi/animeextension/ar/animeblkom/AnimeBlkom.kt
> fix(ar/animeblkom): changed user-agent

- src/pt/anitube/build.gradle
- src/pt/anitube/src/eu/kanade/tachiyomi/animeextension/pt/anitube/Anitube.kt
- src/pt/anitube/src/eu/kanade/tachiyomi/animeextension/pt/anitube/AnitubeFilters.kt
- src/pt/anitube/src/eu/kanade/tachiyomi/animeextension/pt/anitube/extractors/AnitubeExtractor.kt
> fix(pt/anitube): Fix search filters + refactor

- src/ar/anime4up/build.gradle
- src/ar/anime4up/src/eu/kanade/tachiyomi/animeextension/ar/anime4up/Anime4Up.kt
- src/ar/anime4up/src/eu/kanade/tachiyomi/animeextension/ar/anime4up/extractors/SharedExtractor.kt
> fix(ar/Anime4Up): fix episodes not loading/adding more sources

- src/all/googledrive/build.gradle
- src/all/googledrive/src/eu/kanade/tachiyomi/animeextension/all/googledrive/GoogleDrive.kt
> fix(all/googledrive): fix file sizes

- multisrc/overrides/dooplay/animesgratis/src/AnimesGratis.kt
- multisrc/overrides/dooplay/animesgratis/src/VrfInterceptor.kt
- multisrc/overrides/dooplay/animesgratis/src/extractors/BloggerExtractor.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/dooplay/DooPlayGenerator.kt
> fix(pt/animesgratis): Add VrfInterceptor and parallelize video extractor

- src/ar/anime4up/build.gradle
- src/ar/anime4up/src/eu/kanade/tachiyomi/animeextension/ar/anime4up/Anime4Up.kt
- src/ar/anime4up/src/eu/kanade/tachiyomi/animeextension/ar/anime4up/extractors/StreamWishExtractor.kt
> fix(ar/Anime4Up): last update issues with Regex

- src/tr/turkanime/build.gradle
- src/tr/turkanime/src/eu/kanade/tachiyomi/animeextension/tr/turkanime/TurkAnime.kt
> fix(tr/turkanime): add runcatching on video extraction, add fix for single item search, and code refactor

- src/en/allanime/build.gradle
- src/en/allanime/src/eu/kanade/tachiyomi/animeextension/en/allanime/AllAnime.kt
- src/en/allanime/src/eu/kanade/tachiyomi/animeextension/en/allanime/extractors/VidstreamingExtractor.kt
> fix(en/allanime): fix vid-mp4 & player host

- lib/chillx-extractor/build.gradle.kts
- lib/chillx-extractor/src/main/java/eu/kanade/tachiyomi/lib/chillxextractor/ChillxExtractor.kt
Checklist:
If the key ever changes again, I'll add dynamic key extraction.
Closes #1867
> fix(lib/chillx-extractor): update key & small refactor

- src/pt/animesvision/build.gradle
- src/pt/animesvision/src/eu/kanade/tachiyomi/animeextension/pt/animesvision/AnimesVision.kt
> fix(pt/animesvision): Fix paginated episode list

- src/all/googledrive/build.gradle
- src/all/googledrive/src/eu/kanade/tachiyomi/animeextension/all/googledrive/GoogleDrive.kt
- src/en/kayoanime/build.gradle
- src/en/kayoanime/src/eu/kanade/tachiyomi/animeextension/en/kayoanime/Kayoanime.kt
- src/en/ripcrabbyanime/build.gradle
- src/en/ripcrabbyanime/src/eu/kanade/tachiyomi/animeextension/en/ripcrabbyanime/Ripcrabbyanime.kt
Checklist:
Closes #1901 , #1870 , and #1855
> fix(src): fix google drive based extensions.

- lib/filemoon-extractor/build.gradle.kts
- lib/filemoon-extractor/src/main/java/eu/kanade/tachiyomi/lib/filemoonextractor/FilemoonExtractor.kt
> feat(lib): Convert FilemoonExtractor into a shared lib

- lib/dood-extractor/src/main/java/eu/kanade/tachiyomi/lib/doodextractor/DoodExtractor.kt
extractor only accepted dood.* but now works with dooood.* and other hosts
Checklist:
> modify(lib/dood): makes extractor accepts all dood hosts

- lib/playlist-utils/src/main/java/eu/kanade/tachiyomi/lib/playlistutils/PlaylistUtils.kt
> [skip ci] docs(lib/playlist-utils): fix incorrect docs

- src/de/kool/build.gradle
- src/de/kool/src/eu/kanade/tachiyomi/animeextension/de/kool/Kool.kt
Should take some load of the search
> feat(de/kool): improve search

- src/all/javguru/build.gradle
- src/all/javguru/src/eu/kanade/tachiyomi/animeextension/all/javguru/JavGuru.kt
- src/all/javguru/src/eu/kanade/tachiyomi/animeextension/all/javguru/extractors/EmTurboExtractor.kt
- src/all/javguru/src/eu/kanade/tachiyomi/animeextension/all/javguru/extractors/MaxStreamExtractor.kt
> feat(all/javguru): parallelmap and new extractor

- src/es/jkanime/build.gradle
- src/es/jkanime/src/eu/kanade/tachiyomi/animeextension/es/jkanime/Jkanime.kt
> feat(es/jkanime): Add airing day filter

- src/de/aniworld/build.gradle
- src/de/aniworld/src/eu/kanade/tachiyomi/animeextension/de/aniworld/AniWorldInterceptor.kt
- src/de/serienstream/build.gradle
- src/de/serienstream/src/eu/kanade/tachiyomi/animeextension/de/serienstream/SerienstreamInterceptor.kt
Not needed anymore because recaptcha got removed
> feat(de/aniworld,serienstream)remove login need

- src/en/ask4movie/build.gradle
- src/en/ask4movie/src/eu/kanade/tachiyomi/animeextension/en/ask4movie/Ask4Movie.kt
> feat(en/ask4movie): update url & add preference to change it

- src/en/edytjedhgmdhm/build.gradle
- src/en/edytjedhgmdhm/src/eu/kanade/tachiyomi/animeextension/en/edytjedhgmdhm/Edytjedhgmdhm.kt
> fix(en/edytjedhgmdhm): fix extension

- src/en/gogoanime/build.gradle
- src/en/gogoanime/src/eu/kanade/tachiyomi/animeextension/en/gogoanime/GogoAnime.kt
- src/en/gogoanime/src/eu/kanade/tachiyomi/animeextension/en/gogoanime/GogoAnimeFilters.kt
- src/en/gogoanime/src/eu/kanade/tachiyomi/animeextension/en/gogoanime/extractors/StreamWishExtractor.kt
- Replaces streamsb with streamwish
- Adds new video hoster, filelions
- Adds advanced search filters
- Updated baseUrl and make preference temporary
- Small code cleanup
Checklist:
> feat(en/gogoanime): add advanced search, new video hoster, & more

- src/es/cuevana/build.gradle
- src/es/cuevana/src/eu/kanade/tachiyomi/animeextension/es/cuevana/Cuevana.kt
- src/es/cuevana/src/eu/kanade/tachiyomi/animeextension/es/cuevana/extractors/StreamWishExtractor.kt
Fixes and updates
Checklist:
Closes #1933
Closes #1846
> Cuevana: Domain changed

- multisrc/overrides/animestream/animeindo/src/AnimeIndoFilters.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/animestream/AnimeStreamGenerator.kt
> fix(id/animeindo): Ignore broken search filter

- src/en/dramacool/build.gradle
- src/en/dramacool/src/eu/kanade/tachiyomi/animeextension/en/dramacool/DramaCool.kt
- src/en/dramacool/src/eu/kanade/tachiyomi/animeextension/en/dramacool/extractors/StreamWishExtractor.kt
> feat(en/dramacool): added StreamWishExtractor

- lib/filemoon-extractor/src/main/java/eu/kanade/tachiyomi/lib/filemoonextractor/FilemoonExtractor.kt
- multisrc/overrides/dooplay/animeonlineninja/additional.gradle
- multisrc/overrides/dooplay/animeonlineninja/src/AnimeOnlineNinja.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/dooplay/DooPlay.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/dooplay/DooPlayGenerator.kt
Closes #2045 
Note: I've bumped-up the `overrideVersionCode`  but the autobump script will bump it again.
Checklist:
> feat(es/AnimeOnlineNinja): Use filemoon extractor + some fixes

- src/ar/witanime/build.gradle
- src/ar/witanime/src/eu/kanade/tachiyomi/animeextension/ar/witanime/WitAnime.kt
> fix(ar/witanime): Update baseUrl + add 2 extractors

- lib/googledrive-extractor/build.gradle.kts
- lib/googledrive-extractor/src/main/java/eu/kanade/tachiyomi/lib/googledriveextractor/GoogleDriveExtractor.kt
Tested with [all/GoogleDrive](https://github.com/aniyomiorg/aniyomi-extensions/tree/master/src/all/googledrive) 👍🏽
> feat(lib): Convert GoogleDriveExtractor to shared lib

- multisrc/overrides/animestream/animeindo/src/AnimeIndo.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/animestream/AnimeStreamGenerator.kt
> fix(id/animeindo): Fix http 404 error

- src/ar/animeblkom/build.gradle
- src/ar/animeblkom/src/eu/kanade/tachiyomi/animeextension/ar/animeblkom/AnimeBlkom.kt
> feat(ar/animeblkom): Add domain preference

- src/en/allmovies/build.gradle
- src/en/allmovies/src/eu/kanade/tachiyomi/animeextension/en/allmovies/AllMovies.kt
> AllMovies Popular page fix

- src/en/animeflix/build.gradle
- src/en/animeflix/src/eu/kanade/tachiyomi/animeextension/en/animeflix/AnimeFlix.kt
> fix(en/animeflix): Fix popular & latest animes page

- src/ar/animeblkom/build.gradle
- src/ar/animeblkom/src/eu/kanade/tachiyomi/animeextension/ar/animeblkom/AnimeBlkom.kt
> fix(ar/animeblkom): Fix thumbnail urls

- src/en/asianload/build.gradle
- src/en/asianload/src/eu/kanade/tachiyomi/animeextension/en/asianload/AsianLoad.kt
> feat(en/asianload): Add more extractors + refactor

- src/tr/tranimeizle/build.gradle
- src/tr/tranimeizle/src/eu/kanade/tachiyomi/animeextension/tr/tranimeizle/TRAnimeIzle.kt
Closes #2109
tee hee
Checklist:
> fix(tr/tranimeizle): Fix anime titles

- lib/mytv-extractor/src/main/java/eu/kanade/tachiyomi/lib/mytvextractor/MytvExtractor.kt
- src/tr/tranimeizle/build.gradle
- src/tr/tranimeizle/src/eu/kanade/tachiyomi/animeextension/tr/tranimeizle/TRAnimeIzle.kt
The extension will be bumped up twice thanks to the autobump script (and I think no one cares).
I'm **supposed** to do the same with some other turkish extensions but I'll leave this job to @Secozzi 👍🏽 
Checklist:
> feat(tr/tranimeizle): Add fansubs preference

- src/en/edytjedhgmdhm/build.gradle
- src/en/edytjedhgmdhm/src/eu/kanade/tachiyomi/animeextension/en/edytjedhgmdhm/Edytjedhgmdhm.kt
> fix(en/edytjedhgmdhm): fix urls, update selectors & episode counter

- lib/dailymotion-extractor/build.gradle.kts
- lib/dailymotion-extractor/src/main/java/eu/kanade/tachiyomi/lib/dailymotionextractor/DailymotionDto.kt
- lib/dailymotion-extractor/src/main/java/eu/kanade/tachiyomi/lib/dailymotionextractor/DailymotionExtractor.kt
Tested with all/lmanime, all/animexin and en/luciferdonghua.
.....didn't test with en/kissanime yet, i'll leave this job to [REDACTED]
> feat(lib): Convert DailymotionExtractor to a shared lib

- multisrc/overrides/animestream/rinecloud/additional.gradle
- multisrc/overrides/animestream/rinecloud/src/RineCloud.kt
- multisrc/overrides/animestream/rinecloud/src/extractors/RineCloudExtractor.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/animestream/AnimeStreamGenerator.kt
> fix(pt/rinecloud): Fix video extractor

- multisrc/overrides/dooplay/pobreflix/src/extractors/PainelfxExtractor.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/dooplay/DooPlayGenerator.kt
984842th bruhzillian extension with broken extractors
Checklist:
> fix(pt/pobreflix): Fix corner case in extractor

- src/pt/animeszone/build.gradle
- src/pt/animeszone/src/eu/kanade/tachiyomi/animeextension/pt/animeszone/AnimesZone.kt
- src/pt/animeszone/src/eu/kanade/tachiyomi/animeextension/pt/animeszone/extractors/BloggerJWPlayerExtractor.kt
> feat(pt/animeszone): Add newer extractor endpoints + refactor

- lib/okru-extractor/build.gradle.kts
- lib/okru-extractor/src/main/java/eu/kanade/tachiyomi/lib/okruextractor/OkruExtractor.kt
> feat(lib/okru-extractor): Add support to HLS/DASH playlists

- src/pt/flixei/build.gradle
- src/pt/flixei/src/eu/kanade/tachiyomi/animeextension/pt/flixei/Flixei.kt
I wish aniyomi's `network.client` included the CloudflareInterceptor like tachiyomi...
Checklist:
> fix(pt/flixei): Fix cloudflare issues

- src/all/animeworldindia/build.gradle
- src/all/animeworldindia/src/eu/kanade/tachiyomi/animeextension/all/animeworldindia/AnimeWorldIndia.kt
- src/all/animeworldindia/src/eu/kanade/tachiyomi/animeextension/all/animeworldindia/MyStreamExtractor.kt
> fix(all/animewordindia): Fix MyStream extractor + refactor

- lib/uqload-extractor/build.gradle.kts
- lib/uqload-extractor/src/main/java/eu/kanade/tachiyomi/lib/uqloadextractor/UqloadExtractor.kt
Btw, Uqload/upload are the same 👍🏽
> feat(lib): Convert UqloadExtractor to a shared lib

- lib/vudeo-extractor/build.gradle.kts
- lib/vudeo-extractor/src/main/java/eu/kanade/tachiyomi/lib/vudeoextractor/VudeoExtractor.kt
OST: [Antichrist hating chorus.flac](https://doujinstyle.com/?p=page&type=1&id=20692)
> feat(lib): Convert VudeoExtractor to a shared lib

- src/es/hentaila/build.gradle
- src/es/hentaila/src/eu/kanade/tachiyomi/animeextension/es/hentaila/Hentaila.kt
> fix(es/hentaila): Update domain and add servers

- src/pt/animestc/build.gradle
- src/pt/animestc/src/eu/kanade/tachiyomi/animeextension/pt/animestc/AnimesTC.kt
- src/pt/animestc/src/eu/kanade/tachiyomi/animeextension/pt/animestc/dto/AnimesTCDto.kt
> fix(pt/animestc): Fix popular & latest updates page

- src/tr/tranimeizle/build.gradle
- src/tr/tranimeizle/src/eu/kanade/tachiyomi/animeextension/tr/tranimeizle/TRAnimeIzle.kt
> feat(tr/tranimeizle): Add hosts selection preference

- src/tr/anizm/build.gradle
- src/tr/anizm/src/eu/kanade/tachiyomi/animeextension/tr/anizm/Anizm.kt
Closes #2137
FINALLY ^^^^
Checklist:
> feat(tr/anizm): Add hosts&fansub selection preferences + more extractors

- multisrc/overrides/dooplay/animeshouse/additional.gradle
- multisrc/overrides/dooplay/animeshouse/src/extractors/EdifierExtractor.kt
- multisrc/overrides/dooplay/animeshouse/src/extractors/GenericExtractor.kt
- multisrc/overrides/dooplay/animeshouse/src/extractors/McpExtractor.kt
- multisrc/overrides/dooplay/animeshouse/src/extractors/MpFourDooExtractor.kt
> refactor(pt/animeshouse): PlaylistUtils go BRRRRRRRRRRRRRRRRRRRRRRRRRRRR

- src/all/jellyfin/build.gradle
- src/all/jellyfin/src/eu/kanade/tachiyomi/animeextension/all/jellyfin/Jellyfin.kt
> fix(all/jellyfin): fix search & trust self signed certificates

- src/fr/franime/build.gradle
- src/fr/franime/src/eu/kanade/tachiyomi/animeextension/fr/franime/FrAnime.kt
> fix(fr/franime): Fix internal anime list 

- src/ar/witanime/build.gradle
- src/ar/witanime/src/eu/kanade/tachiyomi/animeextension/ar/witanime/WitAnime.kt
> fix(ar/witanime): Update baseUrl + fix episode & video list

- src/en/fmovies/build.gradle
- src/en/fmovies/src/eu/kanade/tachiyomi/animeextension/en/fmovies/FMovies.kt
- src/en/fmovies/src/eu/kanade/tachiyomi/animeextension/en/fmovies/FMoviesFilters.kt
- src/en/fmovies/src/eu/kanade/tachiyomi/animeextension/en/fmovies/FMoviesHelper.kt
> fix(en/fmovies): use correct action for mcloud and small tweak to filters

- src/de/animebase/build.gradle
- src/de/animebase/src/eu/kanade/tachiyomi/animeextension/de/animebase/AnimeBase.kt
- src/de/animebase/src/eu/kanade/tachiyomi/animeextension/de/animebase/AnimeBaseFilters.kt
- src/de/animebase/src/eu/kanade/tachiyomi/animeextension/de/animebase/extractors/VidGuardExtractor.kt
Related to #2236 (i mean, the TODOs).
Checklist:
> feat(de/animebase): Add VidGuard extractor + implement search filters

- src/all/animeworldindia/build.gradle
- src/all/animeworldindia/src/eu/kanade/tachiyomi/animeextension/all/animeworldindia/AnimeWorldIndia.kt
- src/all/animeworldindia/src/eu/kanade/tachiyomi/animeextension/all/animeworldindia/AnimeWorldIndiaFactory.kt
- src/all/animeworldindia/src/eu/kanade/tachiyomi/animeextension/all/animeworldindia/AnimeWorldIndiaFilters.kt
- src/all/animeworldindia/src/eu/kanade/tachiyomi/animeextension/all/animeworldindia/MyStreamExtractor.kt
> fix(all/animeworldindia): Fix episode list + add [all] language

- src/tr/anizm/build.gradle
- src/tr/anizm/src/eu/kanade/tachiyomi/animeextension/tr/anizm/Anizm.kt
- src/tr/anizm/src/eu/kanade/tachiyomi/animeextension/tr/anizm/extractors/AincradExtractor.kt
> feat(tr/anizm): Add Aincrab extractor

- src/all/missav/build.gradle
- src/all/missav/src/eu/kanade/tachiyomi/animeextension/all/missav/MissAV.kt
> feat(all/missav): Include more info in anime details page

- lib/fastream-extractor/build.gradle.kts
- lib/fastream-extractor/src/main/java/eu/kanade/tachiyomi/lib/fastreamextractor/FastreamExtractor.kt
- lib/fastream-extractor/src/main/java/eu/kanade/tachiyomi/lib/fastreamextractor/JsUnpacker.kt
- lib/filemoon-extractor/src/main/java/eu/kanade/tachiyomi/lib/filemoonextractor/FilemoonExtractor.kt
- src/es/mundodonghua/build.gradle
- src/es/mundodonghua/src/eu/kanade/tachiyomi/animeextension/es/mundodonghua/MundoDonghua.kt
> MundoDonghua fixes

- src/en/rule34video/build.gradle
- src/en/rule34video/src/eu/kanade/tachiyomi/animeextension/en/rule34video/DdosGuardInterceptor.kt
- src/en/rule34video/src/eu/kanade/tachiyomi/animeextension/en/rule34video/Rule34Video.kt
> fix(en/rule34video): Fix http 403 error

- src/fr/animesama/build.gradle
- src/fr/animesama/src/eu/kanade/tachiyomi/animeextension/fr/animesama/AnimeSama.kt
> fix(fr/animesama): Fix anime sama

- src/es/mundodonghua/build.gradle
- src/es/mundodonghua/src/eu/kanade/tachiyomi/animeextension/es/mundodonghua/MundoDonghua.kt
Closes #2293 
Note: i'll leave the complete refactoration of this amalgamation of satanic choices to @Secozzi 👍🏽 
Checklist:
> feat(es/mundodonghua): Implement latest anime page

- lib/chillx-extractor/src/main/java/eu/kanade/tachiyomi/lib/chillxextractor/ChillxExtractor.kt
- src/en/tokuzilla/build.gradle
- src/en/tokuzilla/src/eu/kanade/tachiyomi/animeextension/en/tokuzilla/Tokuzilla.kt
Closes #2265 
please DON'T READ the new regex 👍🏽 
Checklist:
> fix(lib): Fix chillx-extractor + refactorate tokuzilla

- multisrc/overrides/animestream/luciferdonghua/additional.gradle
- multisrc/overrides/animestream/luciferdonghua/src/LuciferDonghua.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/animestream/AnimeStreamGenerator.kt
> fix(en/luciferdonghua): fix video urls and add filelions

- src/es/legionanime/build.gradle
- src/es/legionanime/src/eu/kanade/tachiyomi/animeextension/es/legionanime/LegionAnime.kt
- src/es/legionanime/src/eu/kanade/tachiyomi/animeextension/es/legionanime/extractors/JkanimeExtractor.kt
> fix(es/legionanime)

- src/all/googledrive/README.md
- src/all/googledrive/build.gradle
- src/en/kayoanime/README.md
- src/en/kayoanime/build.gradle
- src/en/ripcrabbyanime/README.md
- src/en/ripcrabbyanime/build.gradle
Just in case
I think version bumps are needed for the `hasReadMe` attribute to update? but ¯\\\_(ツ)\_/¯
> feat: add disclaimers for google drive based extensions

- multisrc/overrides/animestream/chineseanime/additional.gradle
- multisrc/overrides/animestream/chineseanime/src/ChineseAnime.kt
- multisrc/overrides/animestream/chineseanime/src/extractors/VatchusExtractor.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/animestream/AnimeStreamGenerator.kt
> feat(all/chineseanime): Add VatchusExtractor

- src/en/tokuzilla/build.gradle
- src/en/tokuzilla/src/eu/kanade/tachiyomi/animeextension/en/tokuzilla/Tokuzilla.kt
> fix(en/tokuzilla): Fix search selector

- lib/gogostream-extractor/build.gradle.kts
- lib/gogostream-extractor/src/main/java/eu/kanade/tachiyomi/lib/gogostreamextractor/GogoStreamExtractor.kt
- lib/gogostream-extractor/src/main/java/eu/kanade/tachiyomi/lib/gogostreamextractor/GogoStreamExtractorDto.kt
> feat(lib): Convert GogoCdn/Vidstreaming extractor to shared lib

- src/en/fmovies/build.gradle
- src/en/fmovies/src/eu/kanade/tachiyomi/animeextension/en/fmovies/FMovies.kt
- src/en/fmovies/src/eu/kanade/tachiyomi/animeextension/en/fmovies/FMoviesHelper.kt
- src/en/fmovies/src/eu/kanade/tachiyomi/animeextension/en/fmovies/extractors/VidsrcExtractor.kt
- src/en/seez/build.gradle
- src/en/seez/src/eu/kanade/tachiyomi/animeextension/en/seez/VrfHelper.kt
- src/en/seez/src/eu/kanade/tachiyomi/animeextension/en/seez/extractors/VidsrcExtractor.kt
> fix(en): fix vidsrc extractor + vrf helper

- src/pt/hinatasoul/build.gradle
- src/pt/hinatasoul/src/eu/kanade/tachiyomi/animeextension/pt/hinatasoul/HinataSoul.kt
- src/pt/hinatasoul/src/eu/kanade/tachiyomi/animeextension/pt/hinatasoul/extractors/HinataSoulExtractor.kt
> fix(pt/hinatasoul): Fix video extractor

- src/all/animeonsen/build.gradle
- src/all/animeonsen/src/eu/kanade/tachiyomi/animeextension/all/animeonsen/AnimeOnsen.kt
- src/all/animeonsen/src/eu/kanade/tachiyomi/animeextension/all/animeonsen/dto/AnimeOnsenDto.kt
> fix(all/animeonsen): Fix anime serializer

- src/de/moflixstream/build.gradle
- src/de/moflixstream/src/eu/kanade/tachiyomi/animeextension/de/moflixstream/MoflixStream.kt
- src/de/moflixstream/src/eu/kanade/tachiyomi/animeextension/de/moflixstream/dto/MoflixStreamDto.kt
> fix(de/moflixstream): Fix NPE + general refactoration

- src/en/aniwave/build.gradle
- src/en/aniwave/src/eu/kanade/tachiyomi/animeextension/en/nineanime/Aniwave.kt
- src/en/aniwave/src/eu/kanade/tachiyomi/animeextension/en/nineanime/AniwaveUtils.kt
- src/en/fmovies/build.gradle
- src/en/fmovies/src/eu/kanade/tachiyomi/animeextension/en/fmovies/FMoviesHelper.kt
* Adds descriptive user-agent for enimax
* Aniwave
* Don't spam preferences when loading episode list
* Make lang preference take precedence, helpful for the (very few) cases where sub and dub have different resolutions available
* Fix video name for filemoon
Checklist:
> feat(en): some minor stuff

- src/en/wcofun/build.gradle
- src/en/wcofun/src/eu/kanade/tachiyomi/animeextension/en/wcofun/Wcofun.kt
> fix(en/wcofun): baseUrl(search) fix

- multisrc/overrides/dooplay/animeplayer/src/AnimePlayer.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/dooplay/DooPlayGenerator.kt
> fix(pt/animeplayer): Fix video extractor

- src/pt/animesgames/AndroidManifest.xml
- src/pt/animesgames/build.gradle
- src/pt/animesgames/src/eu/kanade/tachiyomi/animeextension/pt/animesgames/AnimesGames.kt
- src/pt/animesgames/src/eu/kanade/tachiyomi/animeextension/pt/animesgames/AnimesGamesUrlActivity.kt
> fix(pt/animesgames): Update baseUrl

- src/id/otakudesu/build.gradle
- src/id/otakudesu/src/eu/kanade/tachiyomi/animeextension/id/otakudesu/OtakuDesu.kt
> feat(id/otakudesu): Add FileLions extractor + fix video sorting

- src/ar/asia2tv/build.gradle
- src/ar/asia2tv/src/eu/kanade/tachiyomi/animeextension/ar/asia2tv/Asia2TV.kt
> fix(ar/asia2tv): Fix video extractor + add more extractors

- src/ar/arabseed/build.gradle
- src/ar/arabseed/src/eu/kanade/tachiyomi/animeextension/ar/arabseed/ArabSeed.kt
> fix(ar/arabseed): Fix default video extractor + more extractors

- src/ar/anime4up/build.gradle
- src/ar/anime4up/src/eu/kanade/tachiyomi/animeextension/ar/anime4up/Anime4Up.kt
- src/ar/anime4up/src/eu/kanade/tachiyomi/animeextension/ar/anime4up/Anime4UpFilters.kt
- src/ar/anime4up/src/eu/kanade/tachiyomi/animeextension/ar/anime4up/extractors/VidYardExtractor.kt
> fix(ar/anime4up): Update baseUrl + more extractors

- lib/chillx-extractor/src/main/java/eu/kanade/tachiyomi/lib/chillxextractor/ChillxExtractor.kt
> fix(lib/chillx-extractor): Update encrypted data regex

- src/tr/animeler/build.gradle
- src/tr/animeler/src/eu/kanade/tachiyomi/animeextension/tr/animeler/Animeler.kt
> fix(tr/animeler): Fix video extractor

- src/ko/aniweek/build.gradle
- src/ko/aniweek/src/eu/kanade/tachiyomi/animeextension/ko/aniweek/Aniweek.kt
> fix(ko/aniweek): fix video extraction

- src/de/kiste/build.gradle
- src/de/kiste/src/eu/kanade/tachiyomi/animeextension/de/kiste/Kiste.kt
> fix(de/kiste): Fix episode list

- multisrc/overrides/dooplay/kinoking/src/Kinoking.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/dooplay/DooPlayGenerator.kt
> fix(de/kinoking): Fix video extractor

- src/id/oploverz/build.gradle
- src/id/oploverz/src/eu/kanade/tachiyomi/animeextension/id/oploverz/Oploverz.kt
- src/id/oploverz/src/eu/kanade/tachiyomi/animeextension/id/oploverz/OploverzFilters.kt
> feat(id/oploverz): Add search filters

- src/id/samehadaku/build.gradle
- src/id/samehadaku/src/eu/kanade/tachiyomi/animeextension/id/samehadaku/Samehadaku.kt
- src/id/samehadaku/src/eu/kanade/tachiyomi/animeextension/id/samehadaku/SamehadakuFilters.kt
> feat(id/samehadaku): Add search filters

- lib/chillx-extractor/src/main/java/eu/kanade/tachiyomi/lib/chillxextractor/ChillxExtractor.kt
> fix(lib/chillx-extractor): Fix http 403 - forbidden

- lib/megacloud-extractor/src/main/java/eu/kanade/tachiyomi/lib/megacloudextractor/MegaCloudExtractor.kt
> feat(lib/megacloud-extractor): Address TODO, fetch indexes only when needed

- src/tr/hdfilmcehennemi/AndroidManifest.xml
- src/tr/hdfilmcehennemi/build.gradle
- src/tr/hdfilmcehennemi/src/eu/kanade/tachiyomi/animeextension/tr/hdfilmcehennemi/HDFilmCehennemi.kt
- src/tr/hdfilmcehennemi/src/eu/kanade/tachiyomi/animeextension/tr/hdfilmcehennemi/HDFilmCehennemiUrlActivity.kt
- src/tr/hdfilmcehennemi/src/eu/kanade/tachiyomi/animeextension/tr/hdfilmcehennemi/extractors/XBetExtractor.kt
> fix(tr/hdfilmcehennemi): Update baseUrl + add another extractor

- multisrc/overrides/animestream/luciferdonghua/src/LuciferDonghua.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/animestream/AnimeStreamGenerator.kt
> fix(en/luciferdonghua): Fix episode list selector

- src/en/aniwave/build.gradle
- src/en/aniwave/src/eu/kanade/tachiyomi/animeextension/en/nineanime/AniwaveUtils.kt
> fix(en/aniwave): Fix VRF encrypt/decrypt

- src/en/hahomoe/build.gradle
- src/en/hahomoe/src/eu/kanade/tachiyomi/animeextension/en/hahomoe/HahoMoe.kt
> fix(en/hahomoe): Fix episode list in some entries

- src/ar/witanime/build.gradle
- src/ar/witanime/src/eu/kanade/tachiyomi/animeextension/ar/witanime/WitAnime.kt
Updating the baseUrl also fixes thumbnails.
Checklist:
> fix(ar/witanime): Update baseUrl + fix latest anime page + fix video extractor

- src/tr/hdfilmcehennemi/build.gradle
- src/tr/hdfilmcehennemi/src/eu/kanade/tachiyomi/animeextension/tr/hdfilmcehennemi/HDFilmCehennemi.kt
> fix(tr/hdfilmcehennemi): Fix urls on search + add support for series

- src/tr/anizm/build.gradle
- src/tr/anizm/src/eu/kanade/tachiyomi/animeextension/tr/anizm/Anizm.kt
> fix(tr/anizm): Fix cloudflare issues

- src/tr/animeler/build.gradle
- src/tr/animeler/src/eu/kanade/tachiyomi/animeextension/tr/animeler/Animeler.kt
- src/tr/animeler/src/eu/kanade/tachiyomi/animeextension/tr/animeler/dto/AnimelerDto.kt
> fix(tr/animeler): Fix Json serialization in search, anime details and episode list pages

- multisrc/overrides/animestream/tranimeci/src/TRAnimeCI.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/animestream/AnimeStreamGenerator.kt
> fix(tr/tranimeci): Update baseUrl

- src/tr/hdfilmcehennemi/build.gradle
- src/tr/hdfilmcehennemi/src/eu/kanade/tachiyomi/animeextension/tr/hdfilmcehennemi/HDFilmCehennemi.kt
- src/tr/hdfilmcehennemi/src/eu/kanade/tachiyomi/animeextension/tr/hdfilmcehennemi/HDFilmCehennemiFilters.kt
> feat(tr/hdfilmcehennemi): Implement search filters

- src/tr/hdfilmcehennemi/build.gradle
- src/tr/hdfilmcehennemi/src/eu/kanade/tachiyomi/animeextension/tr/hdfilmcehennemi/HDFilmCehennemi.kt
- src/tr/hdfilmcehennemi/src/eu/kanade/tachiyomi/animeextension/tr/hdfilmcehennemi/HDFilmCehennemiFilters.kt
- src/tr/hdfilmcehennemi/src/eu/kanade/tachiyomi/animeextension/tr/hdfilmcehennemi/extractors/RapidrameExtractor.kt
> feat(tr/hdfilmcehennemi): Add subtitles support to a extractor + fix translation

- src/en/hstream/build.gradle
- src/en/hstream/src/eu/kanade/tachiyomi/animeextension/en/hstream/Hstream.kt
> fix(en/hstream): Fix subtitles

- src/id/kuramanime/build.gradle
- src/id/kuramanime/src/eu/kanade/tachiyomi/animeextension/id/kuramanime/Kuramanime.kt
> fix(id/kuramanime): Fix video list again

- src/en/aniwave/build.gradle
- src/en/aniwave/src/eu/kanade/tachiyomi/animeextension/en/nineanime/Aniwave.kt
> Add aniwave.vc domain

- src/id/samehadaku/build.gradle
- src/id/samehadaku/src/eu/kanade/tachiyomi/animeextension/id/samehadaku/Samehadaku.kt
> [Samehadaku extension] Update baseUrl

- src/ar/animeblkom/build.gradle
- src/ar/animeblkom/src/eu/kanade/tachiyomi/animeextension/ar/animeblkom/AnimeBlkom.kt
Fixes #2625
Closes #2627 
Fixes #2567
Checklist:
> fix(ar/animeblkom): Fix video extractor + add new domain

- src/id/kuramanime/build.gradle
- src/id/kuramanime/src/eu/kanade/tachiyomi/animeextension/id/kuramanime/Kuramanime.kt
Closes #2603 
The code is slowly becoming a complete mess xD
Checklist:
> fix(id/kuramanime): Fix episode list in long series + fix video list

- src/en/kisskh/build.gradle
- src/en/kisskh/src/eu/kanade/tachiyomi/animeextension/en/kisskh/KissKH.kt
- src/en/kisskh/src/eu/kanade/tachiyomi/animeextension/en/kisskh/SubDecryptor.kt
> feat(en/kisskh): decrypt encrypted subtitles

- src/ar/egydead/build.gradle
- src/ar/egydead/src/eu/kanade/tachiyomi/animeextension/ar/egydead/EgyDead.kt
> fix(ar/egydead): fix streamwish extractor and dood

- src/all/googledrive/build.gradle
- src/all/googledrive/src/eu/kanade/tachiyomi/animeextension/all/googledrive/GoogleDrive.kt
> Fix nextPageToken

- src/it/animesaturn/build.gradle
- src/it/animesaturn/src/eu/kanade/tachiyomi/animeextension/it/animesaturn/AnimeSaturn.kt
> Added missing years to filter

- src/it/animeunity/build.gradle
- src/it/animeunity/src/eu/kanade/tachiyomi/animeextension/it/animeunity/AnimeUnity.kt
> fix(it/animeunity):  Update playlist name, remove no longer existent URL

- src/id/oploverz/build.gradle
- src/id/oploverz/src/eu/kanade/tachiyomi/animeextension/id/oploverz/Oploverz.kt
- src/id/oploverz/src/eu/kanade/tachiyomi/animeextension/id/oploverz/OploverzFilters.kt
> fix(id/oploverz): Update baseUrl

- src/pt/anitube/build.gradle
- src/pt/anitube/src/eu/kanade/tachiyomi/animeextension/pt/anitube/AnitubeFilters.kt
> fix(pt/anitube): Update year filter

- src/en/animetake/build.gradle
- src/en/animetake/src/eu/kanade/tachiyomi/animeextension/en/animetake/AnimeTakeFilters.kt
> fix(en/animetake): Update year filter

- src/pt/animestc/build.gradle
- src/pt/animestc/src/eu/kanade/tachiyomi/animeextension/pt/animestc/ATCFilters.kt
- src/pt/animestc/src/eu/kanade/tachiyomi/animeextension/pt/animestc/AnimesTC.kt
- src/pt/animestc/src/eu/kanade/tachiyomi/animeextension/pt/animestc/extractors/AnonFilesExtractor.kt
- src/pt/animestc/src/eu/kanade/tachiyomi/animeextension/pt/animestc/extractors/SendcmExtractor.kt
> fix(pt/animestc): Fix search & extractor

- multisrc/overrides/animestream/rinecloud/src/extractors/RineCloudExtractor.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/animestream/AnimeStreamGenerator.kt
> fix(pt/rinecloud): Fix rinecloud extractor

- src/all/kamyroll/build.gradle
- src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/Yomiroll.kt
Hopefully there's no more issues
Checklist:
> fix(all/yomiroll): update anilist query for better results

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/01_report_issue.yml
- .github/ISSUE_TEMPLATE/05_request_feature.yml
- .github/ISSUE_TEMPLATE/06_request_meta.yml
update app version on issue template
> update app version on issue template

- src/id/oploverz/build.gradle
- src/id/oploverz/src/eu/kanade/tachiyomi/animeextension/id/oploverz/Oploverz.kt
> fix(id/oploverz): Update baseUrl 

- src/en/putlocker/build.gradle
- src/en/putlocker/src/eu/kanade/tachiyomi/animeextension/en/putlocker/PutLocker.kt
- src/en/putlocker/src/eu/kanade/tachiyomi/animeextension/en/putlocker/PutLockerDto.kt
- src/en/putlocker/src/eu/kanade/tachiyomi/animeextension/en/putlocker/extractors/PutServerExtractor.kt
> fix(en/putlocker): update episode list extraction and refactor

- lib/sendvid-extractor/build.gradle.kts
- lib/sendvid-extractor/src/main/java/eu/kanade/tachiyomi/lib/sendvidextractor/SendvidExtractor.kt
Affects: animesama, animeytes, anizm, franime, otakufr, tranimeizle and turkanime.
> fix(lib/sendvid-extractor): Don't try parsing a .mp4 as a .m3u8 file

- src/en/wcofun/build.gradle
- src/en/wcofun/src/eu/kanade/tachiyomi/animeextension/en/wcofun/Wcofun.kt
> fix(en/Wcofun): Domain changed

- src/tr/hdfilmcehennemi/build.gradle
- src/tr/hdfilmcehennemi/src/eu/kanade/tachiyomi/animeextension/tr/hdfilmcehennemi/HDFilmCehennemi.kt
> fix(tr/HDFilmCehennemi): Domain changed

- src/es/monoschinos/build.gradle
- src/es/monoschinos/src/eu/kanade/tachiyomi/animeextension/es/monoschinos/MonosChinos.kt
> Feat(es/monos chinos) add extractors

- src/en/fmovies/build.gradle
- src/en/fmovies/src/eu/kanade/tachiyomi/animeextension/en/fmovies/FMovies.kt
- src/en/fmovies/src/eu/kanade/tachiyomi/animeextension/en/fmovies/FmoviesUtils.kt
> feat(en/fmovies): add status and next episode air date using title

- src/pt/betteranime/build.gradle
- src/pt/betteranime/src/eu/kanade/tachiyomi/animeextension/pt/betteranime/BAFilters.kt
- src/pt/betteranime/src/eu/kanade/tachiyomi/animeextension/pt/betteranime/BetterAnime.kt
- src/pt/betteranime/src/eu/kanade/tachiyomi/animeextension/pt/betteranime/LoginInterceptor.kt
- src/pt/betteranime/src/eu/kanade/tachiyomi/animeextension/pt/betteranime/RecaptchaV3Bypasser.kt
- src/pt/betteranime/src/eu/kanade/tachiyomi/animeextension/pt/betteranime/dto/BetterAnimeDto.kt
Closes #2811 
Closes #2767 
Checklist:
> fix(pt/betteranime): Fix http 405 on search + add automatic login

- multisrc/overrides/dooplay/goanimes/src/GoAnimes.kt
- multisrc/overrides/dooplay/goanimes/src/extractors/GoAnimesExtractor.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/dooplay/DooPlayGenerator.kt
> fix(pt/goanimes): Fix extractor and quality name

- src/pt/animestc/AndroidManifest.xml
- src/pt/animestc/build.gradle
- src/pt/animestc/src/eu/kanade/tachiyomi/animeextension/pt/animestc/AnimesTC.kt
> fix(pt/animestc): Fix IllegalStateException (close #2859)

- src/pt/animesdigital/build.gradle
- src/pt/animesdigital/src/eu/kanade/tachiyomi/animeextension/pt/animesdigital/AnimesDigital.kt
- src/pt/animesdigital/src/eu/kanade/tachiyomi/animeextension/pt/animesdigital/extractors/ProtectorExtractor.kt
- src/pt/animesdigital/src/eu/kanade/tachiyomi/animeextension/pt/animesdigital/extractors/ScriptExtractor.kt
> fix(pt/animesdigital): Fix video extractor

- src/es/hackstore/build.gradle
- src/es/hackstore/src/eu/kanade/tachiyomi/animeextension/es/hackstore/Hackstore.kt
> fix(src/es/Hackstore) Video empty

- .github/ISSUE_TEMPLATE/01_report_issue.yml
- .github/ISSUE_TEMPLATE/03_report_url_change.yml
- .github/ISSUE_TEMPLATE/05_request_feature.yml
- .github/ISSUE_TEMPLATE/06_request_meta.yml
- .github/pull_request_template.md
> [skip ci] chore: Minor changes to PR & issue templates

- src/en/hanime/build.gradle
- src/en/hanime/src/eu/kanade/tachiyomi/animeextension/en/hanime/DataModel.kt
- src/en/hanime/src/eu/kanade/tachiyomi/animeextension/en/hanime/Hanime.kt
> feat(en/hanime): Episode grouping 

- lib/javcoverfetcher/src/main/java/eu/kanade/tachiyomi/lib/javcoverfetcher/JavCoverFetcher.kt
- src/all/javguru/src/eu/kanade/tachiyomi/animeextension/all/javguru/JavGuru.kt
- src/all/missav/src/eu/kanade/tachiyomi/animeextension/all/missav/MissAV.kt
> fix(all): fixes for MissAv & javGuru

- lib/streamhidevid-extractor/build.gradle.kts
- lib/streamhidevid-extractor/src/main/java/eu/kanade/tachiyomi/lib/streamhidevidextractor/StreamHideVidExtractor.kt
> fix: streamhidevid try to get playlist url from the page if unpack fails

- src/pt/goanimes/build.gradle
- src/pt/goanimes/src/eu/kanade/tachiyomi/animeextension/pt/goanimes/GoAnimes.kt
- src/pt/goanimes/src/eu/kanade/tachiyomi/animeextension/pt/goanimes/extractors/GoAnimesExtractor.kt
- src/pt/goanimes/src/eu/kanade/tachiyomi/animeextension/pt/goanimes/extractors/PlaylistExtractor.kt
> fix(pt/goanimes): Fix video extraction (close #2926)

- src/all/torrentioanime/build.gradle
- src/all/torrentioanime/src/eu/kanade/tachiyomi/animeextension/all/torrentioanime/Torrentio.kt
> Torrentio: Added "Show Upcoming Episodes"

- src/en/slothanime/build.gradle
- src/en/slothanime/src/eu/kanade/tachiyomi/animeextension/en/slothanime/SlothAnime.kt
> fix(en/slothanime): fix npe

- src/en/gogoanime/build.gradle
- src/en/gogoanime/src/eu/kanade/tachiyomi/animeextension/en/gogoanime/GogoAnime.kt
- src/en/gogoanime/src/eu/kanade/tachiyomi/animeextension/en/gogoanime/GogoAnimeFilters.kt
> Fix(en/gogoanime): Filter, Description fix

- lib/vidsrc-extractor/src/main/java/eu/kanade/tachiyomi/lib/vidsrcextractor/VidSrcExtractor.kt
- src/en/nineanime/build.gradle
- src/en/nineanime/src/eu/kanade/tachiyomi/animeextension/en/nineanime/AniwaveUtils.kt
> fix(en/nineanime): Fix keys and encryption algorithm

- src/es/locopelis/build.gradle
- src/es/locopelis/src/eu/kanade/tachiyomi/animeextension/es/locopelis/LocoPelis.kt
> fix(src/es): LocoPelis fixes

- src/pt/vizer/build.gradle
- src/pt/vizer/src/eu/kanade/tachiyomi/animeextension/pt/vizer/Vizer.kt
- src/pt/vizer/src/eu/kanade/tachiyomi/animeextension/pt/vizer/dto/VizerDto.kt
> fix(pt/vizer): Fix crashes in episode list and video list

- src/pt/hentaistube/build.gradle
- src/pt/hentaistube/src/eu/kanade/tachiyomi/animeextension/pt/hentaistube/HentaisTube.kt
> fix(pt/hentaistube): Update episode list selector + minor refactoration

- src/all/hikari/build.gradle
- src/all/hikari/src/eu/kanade/tachiyomi/animeextension/all/hikari/Hikari.kt
> add streamwish to hikari

- lib/vidhide-extractor/build.gradle.kts
- lib/vidhide-extractor/src/main/java/eu/kanade/tachiyomi/lib/vidhideextractor/VidHideExtractor.kt
- src/all/hikari/build.gradle
- src/all/hikari/src/eu/kanade/tachiyomi/animeextension/all/hikari/Hikari.kt
> feat(all/hikari): replace streamwish with vidhide

- src/all/jellyfin/build.gradle
- src/all/jellyfin/src/eu/kanade/tachiyomi/animeextension/all/jellyfin/Jellyfin.kt
- src/all/jellyfin/src/eu/kanade/tachiyomi/animeextension/all/jellyfin/JellyfinDto.kt
> feat(all/jellyfin): add support for collections

- src/en/edytjedhgmdhm/build.gradle
- src/en/edytjedhgmdhm/src/eu/kanade/tachiyomi/animeextension/en/edytjedhgmdhm/Edytjedhgmdhm.kt
> feat(en/edytjedhgmdhm): update url(s)

- src/es/latanime/build.gradle
- src/es/latanime/src/eu/kanade/tachiyomi/animeextension/es/latanime/Latanime.kt
> feat(scr/es/Latanime): Fix error servers not found

- src/all/jellyfin/build.gradle
- src/all/jellyfin/src/eu/kanade/tachiyomi/animeextension/all/jellyfin/JellyfinDto.kt
> Jellyfin: mark status as completed for movies

- src/es/pelisforte/build.gradle
- src/es/pelisforte/src/eu/kanade/tachiyomi/animeextension/es/pelisforte/PelisForte.kt
> chore(src/es/pelisforte) change domain and fix http 404 error

- src/es/hackstore/build.gradle
- src/es/hackstore/src/eu/kanade/tachiyomi/animeextension/es/hackstore/Hackstore.kt
> chore(src/es/hackstore): Change Domain

- src/ar/faselhd/build.gradle
- src/ar/faselhd/src/eu/kanade/tachiyomi/animeextension/ar/faselhd/FASELHD.kt
- src/ar/faselhd/src/eu/kanade/tachiyomi/animeextension/ar/faselhd/WebViewResolver.kt
> chore(src/ar/faselhd): refactor + add more filters

- src/pt/betteranime/build.gradle
- src/pt/betteranime/src/eu/kanade/tachiyomi/animeextension/pt/betteranime/RecaptchaV3Bypasser.kt
It took a while because i'm lazy, but who cares anyway? there's no one using this extension, right? :clueless:
Closes #3252
^ As their domain didn't actually change
Checklist:
> fix(pt/betteranime): Fix crashes + fix auto-login

- src/fr/animesama/build.gradle
- src/fr/animesama/src/eu/kanade/tachiyomi/animeextension/fr/animesama/AnimeSama.kt
Closes absolutely no issue :3
Checklist:
> fix(fr/animesama): latest page

- src/fr/anisama/build.gradle
- src/fr/anisama/src/eu/kanade/tachiyomi/animeextension/fr/anisama/AniSama.kt
> fix(fr/anisama): update domain
