aniyomiorg/aniyomi-extensions

- src/en/gogoanime/build.gradle
- src/en/gogoanime/src/eu/kanade/tachiyomi/animeextension/en/gogoanime/GogoAnime.kt
Gogo animes are mostly written in its japanese titles. Adding other names to the description makes it visible when searching anime that is in library.
> Gogoanime: added other names

- src/ar/mycima/build.gradle
- src/ar/mycima/src/eu/kanade/tachiyomi/animeextension/ar/mycima/MyCima.kt
remove episode_number due to errors because the episode number is associated with a lot of strings  that needs to be replaced
> mycima: remove episode_number

- src/en/vidembed/build.gradle
- src/en/vidembed/src/eu/kanade/tachiyomi/animeextension/en/vidembed/Vidembed.kt
Fixed next/prev not working in the Video player in Vidembed extension. 
Cause: Wrong episode number while parsing episodes.
> vidembed: fix next/prev not working

- src/en/dopebox/build.gradle
- src/en/dopebox/src/eu/kanade/tachiyomi/animeextension/en/dopebox/DopeBox.kt
- src/en/sflix/build.gradle
- src/en/sflix/src/eu/kanade/tachiyomi/animeextension/en/sflix/SFlix.kt
As both of the extensions are basically the same, I will just refer to DopeBox
DopeBox had an episode listing error, wherein the episode list would show up in a reverse order than what we are used to. This caused problems in the episode loaders of the player as well. 
It would move up an episode and a season at the same time.
So from Season 1 Episode 5, next would become Season 2 Episode 6, with no previous episode existing.
A simple reversing of the episode list ,before pushing to the user, fixed both the problems!
> Fixing DopeBox and Sflix

- src/en/gogoanime/src/eu/kanade/tachiyomi/animeextension/en/gogoanime/GogoAnime.kt
Combines the gogo video list and dood video list into one.
That way if any problems occur in one, its much easier for users to switch to the mirror and continue watching. The extension can be fixed in the background while users dont get affected as much
Reason:- Shingeki no Kyojin season 4 part 2, latest ep 12 seems to not work when using the gogocdn link
It shows up as a link, but gives an error 404. so it gets stuck without returning an empty list
(Unless there is a specific reason that dood hasn't been added to the main list before? does it rate limit? )
> Combine gogo and dood videos to one list

- src/pt/animesvision/build.gradle
- src/pt/animesvision/src/eu/kanade/tachiyomi/animeextension/pt/animesvision/extractors/GlobalVisionExtractor.kt
It was returning the same url in all videos/qualities xD
> AnimesVision: Fix GlobalVision urls

- src/en/nineanime/build.gradle
- src/en/nineanime/src/eu/kanade/tachiyomi/animeextension/en/nineanime/NineAnime.kt
Fixed selectors: 
- genre
- description
- statusString
Added: 
- author (anime studio)
> 9anime: fix `animeDetailsParse` selectors

- src/en/nineanime/build.gradle
- src/en/nineanime/src/eu/kanade/tachiyomi/animeextension/en/nineanime/NineAnime.kt
Changed search anime selector to only gets immediate div descendants of div with search results, rather than recursively. Should get rid of spurious search results.
I ran into the issue myself, but also checked later and noticed it is an open issue, thus it closes #702
> 9anime: fix search anime selector

- src/en/nineanime/build.gradle
- src/en/nineanime/src/eu/kanade/tachiyomi/animeextension/en/nineanime/NineAnime.kt
Fix `latestUpdates*` url path
Reuse `popularAnime*` functions for search and latestUpdates
> 9anime: more fixes

- src/en/nineanime/build.gradle
- src/en/nineanime/src/eu/kanade/tachiyomi/animeextension/en/nineanime/NineAnime.kt
Instead of opening the episode and check for sub/dub in the video quality, episodes should be tagged with available language.
Currently episode name is the option but for future update, `SEpisode` should have an optional `sub` and `dub` flags that can be set by extensions and the app could show this flag appropriately. I can open a tracker(issue) in the app repo if this is acceptable?
And sorry for the flood of updates.
> 9anime: Tag episodes with Sub/Dub

- src/en/kickassanime/build.gradle
- src/en/kickassanime/src/eu/kanade/tachiyomi/animeextension/en/kickassanime/KickAssAnime.kt
Checklist:
`animeDetailsParse` loop while erroring when alternative name is returned as empty string instead empty array from the server.
> 9anime: Fix endless loading

- src/ar/anime4up/build.gradle
- src/ar/anime4up/src/eu/kanade/tachiyomi/animeextension/ar/anime4up/Anime4Up.kt
- src/ar/xsanime/build.gradle
- src/ar/xsanime/src/eu/kanade/tachiyomi/animeextension/ar/xsanime/XsAnime.kt
- src/ar/xsmovie/build.gradle
- src/ar/xsmovie/src/eu/kanade/tachiyomi/animeextension/ar/xsmovie/XsMovie.kt
anime4up: update site BaseUrl
xsanime, xsmovies: fix thumbnail_url  selectors
Checklist:
> anime4up, xsanime, xsmovies: some fixes

- src/it/animeworld/build.gradle
- src/it/animeworld/src/eu/kanade/tachiyomi/animeextension/it/animeworld/ANIMEWORLD.kt
closes #735
And throw a clear error message when video's are taken down due to copyright.
Checklist:
> AnimeWorld: handle streamingaw.online server 

- src/en/kickassanime/build.gradle
- src/en/kickassanime/src/eu/kanade/tachiyomi/animeextension/en/kickassanime/KickAssAnime.kt
trim search query for better result
ignore dead servers for faster videolist parsing
handle betaplayer links early if available
Checklist:
> KickAssAnime: Add Uploaded date

- src/all/onepace/build.gradle
- src/all/onepace/src/eu/kanade/tachiyomi/animeextension/all/onepace/Onepace.kt
> fix [OnePace]

- src/es/animefenix/build.gradle
- src/es/animefenix/src/eu/kanade/tachiyomi/animeextension/es/animefenix/extractors/FembedExtractor.kt
- src/es/animeflv/build.gradle
- src/es/animeflv/src/eu/kanade/tachiyomi/animeextension/es/animeflv/extractors/FembedExtractor.kt
- src/es/animelatinohd/build.gradle
- src/es/animelatinohd/src/eu/kanade/tachiyomi/animeextension/es/animelatinohd/extractors/FembedExtractor.kt
- src/es/animeonlineninja/src/eu/kanade/tachiyomi/animeextension/es/animeonlineninja/extractors/FembedExtractor.kt
- src/es/asialiveaction/build.gradle
- src/es/asialiveaction/src/eu/kanade/tachiyomi/animeextension/es/asialiveaction/extractors/FembedExtractor.kt
- src/es/doramasyt/build.gradle
- src/es/doramasyt/src/eu/kanade/tachiyomi/animeextension/es/doramasyt/extractors/FembedExtractor.kt
- src/es/hentaijk/build.gradle
- src/es/hentaijk/src/eu/kanade/tachiyomi/animeextension/es/hentaijk/extractors/FembedExtractor.kt
- src/es/hentaila/build.gradle
- src/es/hentaila/src/eu/kanade/tachiyomi/animeextension/es/hentaila/extractors/FembedExtractor.kt
- src/es/jkanime/build.gradle
- src/es/jkanime/src/eu/kanade/tachiyomi/animeextension/es/jkanime/extractors/FembedExtractor.kt
- src/es/jkhentai/build.gradle
- src/es/jkhentai/src/eu/kanade/tachiyomi/animeextension/es/jkhentai/extractors/FembedExtractor.kt
- src/es/monoschinos/build.gradle
- src/es/monoschinos/src/eu/kanade/tachiyomi/animeextension/es/monoschinos/extractors/FembedExtractor.kt
- src/es/mundodonghua/build.gradle
- src/es/mundodonghua/src/eu/kanade/tachiyomi/animeextension/es/mundodonghua/extractors/FembedExtractor.kt
- src/es/pelisflix/build.gradle
- src/es/pelisflix/src/eu/kanade/tachiyomi/animeextension/es/pelisflix/extractors/FembedExtractor.kt
- src/es/pelisplushd/build.gradle
- src/es/pelisplushd/src/eu/kanade/tachiyomi/animeextension/es/pelisplushd/extractors/FembedExtractor.kt
- src/es/tioanime/build.gradle
- src/es/tioanime/src/eu/kanade/tachiyomi/animeextension/es/tioanimeh/extractors/FembedExtractor.kt
in some videos it gives an error and everything goes to shit. 
ex:
https://fembed.com/v/05nw4sljdyn2nly
Checklist:
> Change `IOException` to `Exception` in FembedExtractor 

- src/en/dopebox/build.gradle
- src/en/dopebox/src/eu/kanade/tachiyomi/animeextension/en/dopebox/DopeBox.kt
> Dopebox: fix URL error

- src/en/zoro/build.gradle
- src/en/zoro/src/eu/kanade/tachiyomi/animeextension/en/zoro/Zoro.kt
Individual episodes are not tagged with language status
Checklist:
> Zoro: Add Sub/Dub status to description

- src/en/dopebox/build.gradle
- src/en/dopebox/src/eu/kanade/tachiyomi/animeextension/en/dopebox/DopeBox.kt
- src/en/sflix/build.gradle
- src/en/sflix/src/eu/kanade/tachiyomi/animeextension/en/sflix/SFlix.kt
This fixes an error detected at #914 review, and another error reported on discord.
Checklist:
> SFlix/Dopebox: fix error 404 and default url

- lib/streamsb-extractor/build.gradle.kts
- lib/streamsb-extractor/src/main/AndroidManifest.xml
- lib/streamsb-extractor/src/main/java/eu/kanade/tachiyomi/lib/streamsbextractor/StreamSBExtractor.kt
- settings.gradle.kts
I just did the conversion and didn't touch the extensions that use this extractor: the idea is that in their next update, the maintainer should remove the old extractor file and start using the shared lib.
I have a commit that does the same as the last conversion PR (= puts the lib in all extensions that use the extractor), but I didn't submit it because that would update several extensions unnecessarily, since this is closer to a refactor than to a bugfix.
BUT if that is not considered a problem, I can send it as soon as possible 👍
> Convert StreamSBExtractor to shared lib

- lib/fembed-extractor/src/main/java/eu/kanade/tachiyomi/lib/fembedextractor/FembedExtractor.kt
- src/pt/vizer/src/eu/kanade/tachiyomi/animeextension/pt/vizer/Vizer.kt
FembedExtractor can throw exceptions if cloudflare wants to ruin everything or if the url is invalid (= http 403 forbidden), and this has the potential to break extensions that may use it when trying to get the video list.
WitAnime and Vizer.tv are going to be bumped by the autobump script on workflow, this time it's not an unnecessary update xD
> FembedExtractor: Prevent exceptions

- src/en/vidembed/build.gradle
- src/en/vidembed/src/eu/kanade/tachiyomi/animeextension/en/vidembed/extractors/MixDropExtractor.kt
> Vidembed: add referer to mixdrop extractor to fix 403

- src/en/vidembed/build.gradle
- src/en/vidembed/src/eu/kanade/tachiyomi/animeextension/en/vidembed/Membed.kt
Hope this is the right way to rename an extension.
Checklist:
> Rename Vidembed to Membed

- src/en/superstream/build.gradle
- src/en/superstream/src/eu/kanade/tachiyomi/animeextension/en/superstream/SuperStream.kt
- src/en/superstream/src/eu/kanade/tachiyomi/animeextension/en/superstream/SuperStreamAPI.kt
Also increase read timeout to 70 seconds
closes #1028 
Checklist:
> SuperStream: Fix search pagination

- src/en/zoro/src/eu/kanade/tachiyomi/animeextension/en/zoro/extractors/ZoroExtractor.kt
- src/en/zoro/src/eu/kanade/tachiyomi/animeextension/en/zoro/utils/Decryptor.kt
Getting the key from Consumet's repository.
Checklist:
> Fixed #1027

- src/en/dopebox/build.gradle
- src/en/dopebox/src/eu/kanade/tachiyomi/animeextension/en/dopebox/DopeBox.kt
- src/en/dopebox/src/eu/kanade/tachiyomi/animeextension/en/dopebox/extractors/DopeBoxExtractor.kt
- src/en/dopebox/src/eu/kanade/tachiyomi/animeextension/en/dopebox/utils/Decryptor.kt
> Fixed #919

- src/en/dopebox/build.gradle
- src/en/dopebox/src/eu/kanade/tachiyomi/animeextension/en/dopebox/DopeBoxFilters.kt
- src/en/sflix/build.gradle
- src/en/sflix/src/eu/kanade/tachiyomi/animeextension/en/sflix/SFlixFilters.kt
- src/en/zoro/build.gradle
- src/en/zoro/src/eu/kanade/tachiyomi/animeextension/en/zoro/ZoroFilters.kt
- src/pt/animesvision/build.gradle
- src/pt/animesvision/src/eu/kanade/tachiyomi/animeextension/pt/animesvision/AVFilters.kt
- src/pt/betteranime/build.gradle
- src/pt/betteranime/src/eu/kanade/tachiyomi/animeextension/pt/betteranime/BAFilters.kt
- src/pt/sukianimes/src/eu/kanade/tachiyomi/animeextension/pt/sukianimes/SKFilters.kt
- src/pt/sukianimes/src/eu/kanade/tachiyomi/animeextension/pt/sukianimes/SukiAnimes.kt
Checklist:
Modified extensions: Zoro.to, SukiAnimes, SFlix, Dopebox, BetterAnime and AnimesVision.
Note: I didn't bump the SukiAnimes version, because I only made a tiny refactor.
The problematic files were found using the following commands:
```bash
$ cd aniyomi-extensions/src
$ grep -R getSearchParameters -l | grep Filters.kt | xargs grep CheckBoxVal -l
```
> [Multiple sources] Fix "List is empty" error on search

- src/en/superstream/build.gradle
- src/en/superstream/src/eu/kanade/tachiyomi/animeextension/en/superstream/DataModel.kt
- src/en/superstream/src/eu/kanade/tachiyomi/animeextension/en/superstream/SuperStream.kt
- src/en/superstream/src/eu/kanade/tachiyomi/animeextension/en/superstream/SuperStreamAPI.kt
Move detail fetching to second api url to avoid hammering one api end all the time
Closes #1111
Closes #1106 
Checklist:
> SuperStream: Add third api url

- lib/fembed-extractor/src/main/java/eu/kanade/tachiyomi/lib/fembedextractor/FembedExtractor.kt
- src/es/locopelis/build.gradle
- src/es/locopelis/src/eu/kanade/tachiyomi/animeextension/es/locopelis/LocoPelis.kt
- Functionality for the Fembed extractor to redirect to a mirror link and then extract the videos.
Checklist:
> Fembed extractor updated & LocoPelis updates

- src/all/kamyroll/build.gradle
- src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/AccessTokenInterceptor.kt
Use token for kamyroll requests only
Use original chain request when new token is fetched
Closes #1147 
Checklist:
> Kamyroll: Fix token request

- src/it/aniplay/build.gradle
- src/it/aniplay/src/eu/kanade/tachiyomi/animeextension/it/aniplay/AniPlay.kt
Checklist:
Prevents some videos from crashing when running aniyomi stable
> Fix crash on stable

- src/en/uhdmovies/build.gradle
- src/en/uhdmovies/src/eu/kanade/tachiyomi/animeextension/en/uhdmovies/UHDMovies.kt
> UHDMovies: Fix search empty entry and list collection movies as episodes

- src/en/marinmoe/build.gradle
- src/en/marinmoe/src/eu/kanade/tachiyomi/animeextension/en/marinmoe/MarinMoe.kt
Checklist:
Fixes video links not loading sometimes (such as running on vpn) & fixes seeking beyond whats buffered
> MarinMoe: Fix seeking & cookies

- src/all/jellyfin/build.gradle
- src/all/jellyfin/src/eu/kanade/tachiyomi/animeextension/all/jellyfin/DataModel.kt
- src/all/jellyfin/src/eu/kanade/tachiyomi/animeextension/all/jellyfin/Jellyfin.kt
Checklist:
Add support for collections
Add toggle in preference to grab metadata from series instead of seasons
Search can now search through more than one series at a time
> Jellyfin: Rewrite, add support for collection, and preference for metadata grabber

- src/en/uhdmovies/build.gradle
- src/en/uhdmovies/src/eu/kanade/tachiyomi/animeextension/en/uhdmovies/UHDMovies.kt
> UHDMovies: fix selector & remove hardcoded url

- src/all/kamyroll/build.gradle
- src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/Consumyroll.kt
- src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/DataModel.kt
Checklist:
Add null check to some fields of seasons, fixing the issue of episodes not being loaded for some series
> Consumyroll: Add null check

- src/en/uhdmovies/build.gradle
- src/en/uhdmovies/src/eu/kanade/tachiyomi/animeextension/en/uhdmovies/UHDMovies.kt
> UHDMovies: Fallback to index if episode number is not available

- src/en/animepahe/build.gradle
- src/en/animepahe/src/eu/kanade/tachiyomi/animeextension/en/animepahe/AnimePahe.kt
Checklist:
Animepahe now works with old entries in library
> Fix animepahe again

- src/en/dopebox/build.gradle
- src/en/dopebox/src/eu/kanade/tachiyomi/animeextension/en/dopebox/extractors/DopeBoxExtractor.kt
- src/en/sflix/build.gradle
- src/en/sflix/src/eu/kanade/tachiyomi/animeextension/en/sflix/extractors/SFlixExtractor.kt
- src/en/zoro/build.gradle
- src/en/zoro/src/eu/kanade/tachiyomi/animeextension/en/zoro/extractors/ZoroExtractor.kt
Checklist:
https://github.com/consumet/rapidclown isn't actively maintained anymore, since Consumet has switched to https://github.com/enimax-anime/key, which is more reliable than rapidclown.
> Changed keys' URL

- src/pt/animesup/build.gradle
- src/pt/animesup/src/eu/kanade/tachiyomi/animeextension/pt/animesup/AnimesUp.kt
- src/pt/animesup/src/eu/kanade/tachiyomi/animeextension/pt/animesup/extractors/LegacyFunExtractor.kt
> fix(AnimesUp): Prevent edge-case error on video extractor

- src/en/uhdmovies/build.gradle
- src/en/uhdmovies/src/eu/kanade/tachiyomi/animeextension/en/uhdmovies/UHDMovies.kt
> UHDMovies: Add size sorting pref, fix quality extractor

- src/en/nineanime/build.gradle
- src/en/nineanime/src/eu/kanade/tachiyomi/animeextension/en/nineanime/JsVrfInterceptor.kt
- src/en/nineanime/src/eu/kanade/tachiyomi/animeextension/en/nineanime/NineAnime.kt
- src/en/nineanime/src/eu/kanade/tachiyomi/animeextension/en/nineanime/extractors/FilemoonExtractor.kt
- src/en/nineanime/src/eu/kanade/tachiyomi/animeextension/en/nineanime/extractors/Mp4uploadExtractor.kt
use consumet to get vizcloud playlist link and other servers embed links
fix filter not working when search query is empty
Checklist:
> Nine: reorganize the code

- src/en/nineanime/build.gradle
- src/en/nineanime/src/eu/kanade/tachiyomi/animeextension/en/nineanime/JsInterceptor.kt
- src/en/nineanime/src/eu/kanade/tachiyomi/animeextension/en/nineanime/JsVrfInterceptor.kt
- src/en/nineanime/src/eu/kanade/tachiyomi/animeextension/en/nineanime/NineAnime.kt
as different vrf is being used from search
Checklist:
> Nine: move episode list to consumet 

- src/en/animepahe/build.gradle
- src/en/animepahe/src/eu/kanade/tachiyomi/animeextension/en/animepahe/AnimePahe.kt
- src/en/animepahe/src/eu/kanade/tachiyomi/animeextension/en/animepahe/dto/AnimePaheDto.kt
Checklist:
The problem that was causing the lags on the popular anime page was the fact that the extension was going crazy and sending almost endless requests, even when you just opened it without scrolling down.
<details>
<summary>Http logs of the extension before</summary>
OBS: it kept growing up
</details>
<details>
<summary>Http logs of the extension now</summary>
</details>
> AnimePahe: Fix lags and reduce DDoS to the server

- src/en/animepahe/build.gradle
- src/en/animepahe/src/eu/kanade/tachiyomi/animeextension/en/animepahe/AnimePahe.kt
Checklist:
I forgot to add support to the old anime URLs (that don't have the sessionId in them), so the last update i sent broke lots of things xD
> AnimePahe: Fix broken library URLs

- src/en/animepahe/build.gradle
- src/en/animepahe/src/eu/kanade/tachiyomi/animeextension/en/animepahe/AnimePahe.kt
- src/en/animepahe/src/eu/kanade/tachiyomi/animeextension/en/animepahe/dto/AnimePaheDto.kt
Checklist:
I thought that the `session` returned by the API could be used in URLs permanently, absolute bruh moment.
> AnimePahe: Revert my mistakes, fix library errors

- src/all/kamyroll/build.gradle
- src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/Yomiroll.kt
Checklist:
Basically adds another comparison and puts `en-US` locale at the top if prefered subs locale is missing. Without this fix, aniyomi would pick the first sub according to `videoList` which more often than not isn't English or a second best choice
> Yomiroll: Added second preference locale set to `en-US`

- src/all/kamyroll/build.gradle
- src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/AccessTokenInterceptor.kt
- src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/Yomiroll.kt
Convert local sub option to be used everywhere when proxy dies, can enable access to us and other catalogs through user's vpn
Example, one punch man can be access using local token by connecting to vpn that has one punch man like France (only country that has it I think)
Checklist:
> Yomiroll: fix no episode error when free episodes are available

- src/all/animexin/build.gradle
- src/all/animexin/src/eu/kanade/tachiyomi/animeextension/all/animexin/AnimeXin.kt
Checklist:
Never noticed until now that i accidentally set the wrong lang
> Animexin: Update lang

- src/all/kamyroll/build.gradle
- src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/Yomiroll.kt
and add option to disable parallel season request
~~Draft until tested on mi device~~
Checklist:
> Yomiroll: fix settings screen stuck on mi devices

- src/en/animedao/build.gradle
- src/en/animedao/src/eu/kanade/tachiyomi/animeextension/en/animedao/AnimeDao.kt
- src/en/nineanime/build.gradle
- src/en/nineanime/src/eu/kanade/tachiyomi/animeextension/en/nineanime/NineAnime.kt
- src/en/zoro/build.gradle
- src/en/zoro/src/eu/kanade/tachiyomi/animeextension/en/zoro/Zoro.kt
Checklist:
Add filler markings for animedao, 9anime, and zoro
> Add filler markings

- src/en/fmovies/build.gradle
- src/en/fmovies/src/eu/kanade/tachiyomi/animeextension/en/fmovies/FMovies.kt
- src/en/fmovies/src/eu/kanade/tachiyomi/animeextension/en/fmovies/FMoviesDto.kt
- src/en/nineanime/build.gradle
- src/en/nineanime/src/eu/kanade/tachiyomi/animeextension/en/nineanime/NineAnime.kt
Consumet will be shutting down in a few months, so this is necessary to make sure the extension keeps working. Fixes [#1618](https://github.com/jmir1/aniyomi-extensions/issues/1618)
Checklist:
> fix(en/9anime): Switch from Consumet's 9anime API

- lib/mp4upload-extractor/build.gradle.kts
- lib/mp4upload-extractor/src/main/java/eu/kanade/tachiyomi/lib/mp4uploadextractor/Mp4uploadExtractor.kt
Looks like mp4upload isn't using jspacker anymore, so the jsunpacker part may be useless, but to prevent future headache it will not be removed (yet).
> feat(lib): New lib: Mp4uploadExtractor

- multisrc/overrides/animestream/animenosub/src/Animenosub.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/animestream/AnimeStream.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/animestream/AnimeStreamFilters.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/animestream/AnimeStreamGenerator.kt
Now it provides a slightly better compatibility with `moviestream` and `hstream` themes, and now **WE** can convert id/minioppai, en/hstream and ar/animetitans to multisrc
.... it still can't auto-parse well filters from other themes >:(
I stole some ideas from the [MangaThemesia multisrc](https://github.com/tachiyomiorg/tachiyomi-extensions/tree/master/multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangathemesia), thanks tachibros!!!
Checklist:
> refactor(multisrc/animestream): Make multisrc a bit more generic and customizable

- src/all/googledriveindex/build.gradle
- src/all/googledriveindex/src/eu/kanade/tachiyomi/animeextension/all/googledriveindex/GoogleDriveIndex.kt
> fix(all/googledriveindex): fix file sizes & use parseAs function

- src/en/wcofun/build.gradle
- src/en/wcofun/src/eu/kanade/tachiyomi/animeextension/en/wcofun/Wcofun.kt
- src/en/wcostream/build.gradle
- src/en/wcostream/src/eu/kanade/tachiyomi/animeextension/en/wcostream/WCOStream.kt
Fixed #1765 and #1784
Checklist:
> fix(en/wcofun,wcostream): Update domains and fix search

- src/en/aniwatch/build.gradle
- src/en/aniwatch/src/eu/kanade/tachiyomi/animeextension/en/zoro/AniWatch.kt
- src/en/aniwatch/src/eu/kanade/tachiyomi/animeextension/en/zoro/extractors/AniWatchExtractor.kt
Added the option to switch to `kaido.to`, since it doesn't run into cloudflare issues.
Checklist:
> feat(en/aniwatch): Update domains

- src/tr/turkanime/build.gradle
- src/tr/turkanime/src/eu/kanade/tachiyomi/animeextension/tr/turkanime/TurkAnime.kt
Moves key extraction from inside the `init` to whenever the key gets oudated. Will most likely solve the issues people in the discord have been reporting where aniyomi crashes if the key extraction fails due to timeouts.
Credit goes to Claudemirovsky, our favorite brazilian cloudflare enjoyer.
> fix(tr/turkanime): fix key extraction

- src/en/rule34video/AndroidManifest.xml
- src/en/rule34video/build.gradle
- src/en/rule34video/src/eu/kanade/tachiyomi/animeextension/en/rule34video/Rule34Video.kt
- src/en/rule34video/src/eu/kanade/tachiyomi/animeextension/en/rule34video/Rule34VideoUrlActivity.kt
Fixed Search
Added support Url Activity. Now user can open rule34video.com links in aniyomi.
Checklist:
> fix(en/rule34video): Fix search and add URL activity

- src/fr/franime/AndroidManifest.xml
- src/fr/franime/build.gradle
- src/fr/franime/src/eu/kanade/tachiyomi/animeextension/fr/franime/FrAnime.kt
- src/fr/franime/src/eu/kanade/tachiyomi/animeextension/fr/franime/FrAnimeUrlActivity.kt
Checklist:
Also fixes:
- Anime diffusion status is always "Completed"
- Swiping down to refresh an anime page shows an error toast
> feat(fr/franime): Add activity intent

- src/it/animeworld/build.gradle
- src/it/animeworld/src/eu/kanade/tachiyomi/animeextension/it/animeworld/ANIMEWORLD.kt
> fix(it/animeworld): update url

- src/ar/animeblkom/build.gradle
- src/ar/animeblkom/src/eu/kanade/tachiyomi/animeextension/ar/animeblkom/AnimeBlkom.kt
> fix(ar/animeblkom): adding runcatching to avoid player errors

- src/en/kickassanime/build.gradle
- src/en/kickassanime/src/eu/kanade/tachiyomi/animeextension/en/kickassanime/dto/KickAssAnimeDto.kt
> fix(en/kickassanime): fix for episodes without titles

- lib/fusevideo-extractor/build.gradle.kts
- lib/fusevideo-extractor/src/main/java/eu/kanade/tachiyomi/lib/fusevideoextractor/FusevideoExtractor.kt
- src/fr/nekosama/build.gradle
- src/fr/nekosama/src/eu/kanade/tachiyomi/animeextension/fr/nekosama/NekoSama.kt
- Fixes and makes Fusevideo extractor lib
- Removed veestream/pstream stuff, hoster closed
- Set containsNsfw to `true`, they have a "Hentai" genre filter
Closes #1821
Closes #2006
Checklist:
> fix(fr/nekosama): Fix video extraction

- src/en/gogoanime/build.gradle
- src/en/gogoanime/src/eu/kanade/tachiyomi/animeextension/en/gogoanime/GogoAnime.kt
The order of recently updated wasn't the same as the website so I did a small fix. Also I changed the baseUrl as the old one didn't have an ssl certificate anymore so I felt that they might change that domain soon.
Checklist:
> Fixes order of latest updates (Gogoanime)

- src/en/oppaistream/build.gradle
- src/en/oppaistream/src/eu/kanade/tachiyomi/animeextension/en/oppaistream/OppaiStream.kt
This functionality retrieves covers from AniList by matching titles and studio names, specifically within the anime details page. This approach is taken to avoid timeout errors resulting from the AniList API limits that would occur if attempting to fetch covers in the searchAnimeFromElement.
Default cover image are just screenshot thumbnails thats why using AniList covers
Checklist:
> Fetch Anilist Cover (OppaiStream)

- src/en/wcofun/build.gradle
- src/en/wcofun/src/eu/kanade/tachiyomi/animeextension/en/wcofun/Wcofun.kt
Tee hee, i forgot the headers
In my defense, for some reason it was working without them when i tested it >:(
Closes #2065 
Checklist:
> fix(en/Wcofun): Fix video extractor AGAIN

- multisrc/src/main/java/generator/ThemeSourceGenerator.kt
- src/all/javguru/build.gradle
- src/ar/okanime/build.gradle
- src/en/oppaistream/build.gradle
- src/id/nimegami/build.gradle
- src/pt/anidong/build.gradle
- src/pt/animesaria/build.gradle
- src/pt/animesdigital/build.gradle
- src/pt/animesgames/build.gradle
- src/pt/animesorion/build.gradle
- src/pt/animestc/build.gradle
- src/pt/donghuanosekai/build.gradle
- src/pt/flixei/build.gradle
- src/pt/hentaistube/build.gradle
- src/pt/listadeanimes/build.gradle
- src/pt/megaflix/build.gradle
- src/pt/meusanimes/build.gradle
- src/sr/animesrbija/build.gradle
Just to prevent some issues when upgrading to future versions of the `extensions-lib`.
Hmmmm, i wonder who made most of those sources without the `libVersion` parameter.....
> refactor: Specify the libVersion parameter in some extensions

- src/fr/nekosama/build.gradle
- src/fr/nekosama/src/eu/kanade/tachiyomi/animeextension/fr/nekosama/NekoSama.kt
Closes #2141 
The old domain seems to be working well, so instead of removing it and replacing with the newer one, it'll become optional (just in case the new domain is somehow worse or something, so users can go back).
Checklist:
> feat(fr/nekosama): Add domain preference

- src/tr/anizm/build.gradle
- src/tr/anizm/src/eu/kanade/tachiyomi/animeextension/tr/anizm/extractors/UQLoadExtractor.kt
> fix(tr/anizm): Fix UQLoad extractor

- src/de/animebase/build.gradle
- src/de/animebase/src/eu/kanade/tachiyomi/animeextension/de/animebase/AnimeBase.kt
Checklist:
They added cloudflare, but even with the cloudflare client it's currently not working.
- [ x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ x] Have not changed source names
- [x ] Have explicitly kept the `id` if a source's name or language were changed
- [ x] Have tested the modifications by compiling and running the extension through Android Studio
> Added Cloudflare to AnimeBase

- src/en/gogoanime/build.gradle
- src/en/gogoanime/src/eu/kanade/tachiyomi/animeextension/en/gogoanime/GogoAnime.kt
The issue was when browsing anime in the latest section and then clicking the Webview of  the anime, instead of navigating to the anime details page it navigates to the latest episode page.
Checklist:
> Fixes webview url of gogoanime for latest updates

- src/en/kickassanime/build.gradle
- src/en/kickassanime/src/eu/kanade/tachiyomi/animeextension/en/kickassanime/KickAssAnime.kt
Checklist:
@Programmer-0-0 the problem is that WebView calls the `animeDetailsRequest` function to get the url, and the extension needed that to be the api url. The solution is simple, albeit hacky, just override `fetchAnimeDetails` to use another function to get the url, and let `animeDetailsRequest` retrieve the url to show in webview
> fix(en/kickassanime): open correct page on webview

- multisrc/overrides/dopeflix/default/additional.gradle
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/dopeflix/DopeFlix.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/dopeflix/DopeFlixGenerator.kt
> fix(multisrc/dopeflix): Fix DopeFlix filters

- src/pt/animesdigital/build.gradle
- src/pt/animesdigital/src/eu/kanade/tachiyomi/animeextension/pt/animesdigital/AnimesDigital.kt
AnimesDigital shows multiples pages of episodes of the anime when there's more than 25 episodes. The extension was only fetching the first page.
Checklist:
> fix(pt/animesdigital): Fetch all episodes on multi-page animes

- src/hi/yomovies/build.gradle
- src/hi/yomovies/src/eu/kanade/tachiyomi/animeextension/hi/yomovies/YoMovies.kt
- src/hi/yomovies/src/eu/kanade/tachiyomi/animeextension/hi/yomovies/extractors/MinoplresExtractor.kt
- src/hi/yomovies/src/eu/kanade/tachiyomi/animeextension/hi/yomovies/extractors/MovembedExtractor.kt
Closes #2254
^ Because now most episodes only have Minoplres and Netu as video hosters, and i'll leave the Netu extractor to Secozzi 👍🏽 
Checklist:
> feat(hi/yomovies): Add Minoplres extractor

- src/en/animeowl/build.gradle
- src/en/animeowl/src/eu/kanade/tachiyomi/animeextension/en/animeowl/AnimeOwl.kt
Closes https://github.com/aniyomiorg/aniyomi-extensions/issues/2189
Checklist:
> fix(en/animeowl): Update baseUrl

- lib/mp4upload-extractor/src/main/java/eu/kanade/tachiyomi/lib/mp4uploadextractor/Mp4uploadExtractor.kt
- src/ar/witanime/build.gradle
- src/ar/witanime/src/eu/kanade/tachiyomi/animeextension/ar/witanime/WitAnime.kt
- src/ar/witanime/src/eu/kanade/tachiyomi/animeextension/ar/witanime/extractors/SoraPlayExtractor.kt
> fix(ar/witanime): Fix soraplay & mp4upload extractors + update baseUrl

- src/all/jellyfin/build.gradle
- src/all/jellyfin/src/eu/kanade/tachiyomi/animeextension/all/jellyfin/DataModel.kt
- src/all/jellyfin/src/eu/kanade/tachiyomi/animeextension/all/jellyfin/JellyfinAuthenticator.kt
> fix(all/jellyfin): fix login + small code touch-up

- lib/googledrive-extractor/src/main/java/eu/kanade/tachiyomi/lib/googledriveextractor/GoogleDriveExtractor.kt
Hopefully fixes the "unrecognized file format" bug, but due to its very nature its not really possible to test it.
Checklist:
> feat(lib/googledrive-extractor): (hopefully) improve extraction

- src/en/aniwave/build.gradle
- src/en/aniwave/src/eu/kanade/tachiyomi/animeextension/en/nineanime/Aniwave.kt
> fix(en/aniwave): Upload date parsing

- multisrc/overrides/animestream/lmanime/src/LMAnime.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/animestream/AnimeStreamGenerator.kt
> fix(all/lmanime): Fix video extractor

- common.gradle
- multisrc/overrides/dooplay/multimovies/src/Multimovies.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/dooplay/DooPlayGenerator.kt
- src/en/aniwave/build.gradle
- src/en/aniwave/src/eu/kanade/tachiyomi/animeextension/en/nineanime/AniwaveUtils.kt
- src/en/ask4movie/build.gradle
- src/en/ask4movie/src/eu/kanade/tachiyomi/animeextension/en/ask4movie/Ask4Movie.kt
- src/en/dramacool/build.gradle
- src/en/dramacool/src/eu/kanade/tachiyomi/animeextension/en/dramacool/DramaCool.kt
- src/en/fmovies/build.gradle
- src/en/fmovies/src/eu/kanade/tachiyomi/animeextension/en/fmovies/FMoviesHelper.kt
- src/en/gogoanime/build.gradle
- src/en/gogoanime/src/eu/kanade/tachiyomi/animeextension/en/gogoanime/GogoAnime.kt
- src/en/ripcrabbyanime/build.gradle
- src/en/ripcrabbyanime/src/eu/kanade/tachiyomi/animeextension/en/ripcrabbyanime/Ripcrabbyanime.kt
- src/hi/yomovies/build.gradle
- src/hi/yomovies/src/eu/kanade/tachiyomi/animeextension/hi/yomovies/YoMovies.kt
- src/it/animeunity/build.gradle
- src/it/animeunity/src/eu/kanade/tachiyomi/animeextension/it/animeunity/AnimeUnity.kt
- src/it/animeworld/build.gradle
- src/it/animeworld/src/eu/kanade/tachiyomi/animeextension/it/animeworld/ANIMEWORLD.kt
- src/it/aniplay/build.gradle
- src/it/aniplay/src/eu/kanade/tachiyomi/animeextension/it/aniplay/AniPlay.kt
- src/it/streamingcommunity/build.gradle
- src/it/streamingcommunity/src/eu/kanade/tachiyomi/animeextension/it/streamingcommunity/StreamingCommunity.kt
> chore: fix pref key for overridable baseurls

- src/fr/franime/build.gradle
- src/fr/franime/src/eu/kanade/tachiyomi/animeextension/fr/franime/FrAnime.kt
- src/fr/franime/src/eu/kanade/tachiyomi/animeextension/fr/franime/dto/FrAnimeDto.kt
> fix(fr/franime): Removed myvi, added vido and vk players

- multisrc/overrides/animestream/minioppai/src/extractors/MiniOppaiExtractor.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/animestream/AnimeStream.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/animestream/AnimeStreamGenerator.kt
> fix(multisrc/animestream): Make getHosterUrl function less error-prone + small fix to id/minioppai

- multisrc/overrides/dooplay/pobreflix/additional.gradle
- multisrc/overrides/dooplay/pobreflix/src/Pobreflix.kt
- multisrc/overrides/dooplay/pobreflix/src/extractors/EplayerExtractor.kt
- multisrc/overrides/dooplay/pobreflix/src/extractors/MyStreamExtractor.kt
- multisrc/overrides/dooplay/pobreflix/src/extractors/PainelfxExtractor.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/dooplay/DooPlayGenerator.kt
> fix(pt/pobreflix): Fix video extractor + Add more extractors

- src/fr/animesama/build.gradle
- src/fr/animesama/src/eu/kanade/tachiyomi/animeextension/fr/animesama/AnimeSama.kt
- src/fr/animesama/src/eu/kanade/tachiyomi/animeextension/fr/animesama/AnimeSamaFilters.kt
> feat(fr/animesama): Add search filters

- src/de/streamcloud/build.gradle
- src/de/streamcloud/src/eu/kanade/tachiyomi/animeextension/de/streamcloud/StreamCloud.kt
> fix(de/streamcloud): Fix video extractor

- src/en/superstream/build.gradle
- src/en/superstream/src/eu/kanade/tachiyomi/animeextension/en/superstream/SuperStream.kt
- src/en/superstream/src/eu/kanade/tachiyomi/animeextension/en/superstream/SuperStreamAPI.kt
> fix(en/superstream): remove alt urls to fix search

- src/en/dramacool/build.gradle
- src/en/dramacool/src/eu/kanade/tachiyomi/animeextension/en/dramacool/DramaCool.kt
> fix(en/dramacool): Put a runCatching block on video extractor to prevent issues

- src/id/kuramanime/build.gradle
- src/id/kuramanime/src/eu/kanade/tachiyomi/animeextension/id/kuramanime/Kuramanime.kt
> fix(id/kuramanime): Fix video extractor + refactor

- src/en/aniwave/build.gradle
- src/en/aniwave/src/eu/kanade/tachiyomi/animeextension/en/nineanime/Aniwave.kt
- src/en/aniwave/src/eu/kanade/tachiyomi/animeextension/en/nineanime/AniwaveDto.kt
- src/en/aniwave/src/eu/kanade/tachiyomi/animeextension/en/nineanime/AniwaveUtils.kt
- src/en/aniwave/src/eu/kanade/tachiyomi/animeextension/en/nineanime/extractors/VidsrcExtractor.kt
> fix(en/aniwave): fix vidsrcextractor

- src/en/gogoanime/build.gradle
- src/en/gogoanime/src/eu/kanade/tachiyomi/animeextension/en/gogoanime/GogoAnime.kt
Note: For now, this PR **ISN'T** related to #2554.
Checklist:
> fix(en/gogoanime): Prevent low-IQ users from using a blank baseURL

- src/en/allanimechi/build.gradle
- src/en/allanimechi/src/eu/kanade/tachiyomi/animeextension/en/allanimechi/AllAnimeChi.kt
- src/en/allanimechi/src/eu/kanade/tachiyomi/animeextension/en/allanimechi/extractors/InternalExtractor.kt
> feat(en/allanimechi): Add option to use hoster names & fix gogo

- src/en/uhdmovies/build.gradle
- src/en/uhdmovies/src/eu/kanade/tachiyomi/animeextension/en/uhdmovies/UHDMovies.kt
yet again another reason to hate cloudflare
Checklist:
> fix(en/uhdmovies): Fix crashes when fetching the current baseUrl

- multisrc/overrides/animestream/animeytes/src/AnimeYTES.kt
- multisrc/overrides/animestream/tiodonghua/src/Tiodonghua.kt
- multisrc/overrides/dooplay/animeshouse/src/AnimesHouse.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/dooplay/DooPlayGenerator.kt
> fix(pt/animeshouse): Fix video extractors

- common.gradle
- settings.gradle.kts
Note: it'll still show a single warning, that happens due to the current Android Gradle Plugin version (8.0.2):
`The BuildIdentifier.getName() method has been deprecated. This is scheduled to be removed in Gradle 9.0. Use getBuildPath() to get a unique identifier for the build. Consult the upgrading guide for further information: https://docs.gradle.org/8.5/userguide/upgrading_version_8.html#build_identifier_name_and_current_deprecation`
Upgrading the AGP to 8.2.0 addresses this, but this requires a bump of the gradle version (8.1.1 -> 8.2), so I'll leave it in the current state to prevent breaking dev environments(Outdated IDEs moment).
> [skip ci] chore: Address deprecation warnings from gradle 8.5+

- src/ar/akwam/build.gradle
- src/ar/akwam/src/eu/kanade/tachiyomi/animeextension/ar/akwam/Akwam.kt
- src/ar/egydead/build.gradle
- src/ar/egydead/src/eu/kanade/tachiyomi/animeextension/ar/egydead/EgyDead.kt
- src/ar/faselhd/build.gradle
- src/ar/faselhd/src/eu/kanade/tachiyomi/animeextension/ar/faselhd/FASELHD.kt
- src/ar/tuktukcinema/build.gradle
- src/ar/tuktukcinema/src/eu/kanade/tachiyomi/animeextension/ar/tuktukcinema/Tuktukcinema.kt
add new extractor in tuktukcinema
fix baseurl in faselhd , egydead and akwam
closes #2195
closes #992
Checklist:
> fix(ar/akwam/faselhd/egydead/tuktukcinema): Mass fix for some arabic extensions

- src/ar/tuktukcinema/build.gradle
- src/ar/tuktukcinema/src/eu/kanade/tachiyomi/animeextension/ar/tuktukcinema/Tuktukcinema.kt
> fix(ar/Tuktukcinema): use streamwish lib for extractor

- src/es/pelisflix/build.gradle
- src/es/pelisflix/src/eu/kanade/tachiyomi/animeextension/es/pelisflix/PelisflixFactory.kt
- src/id/kuronime/build.gradle
- src/id/kuronime/src/eu/kanade/tachiyomi/animeextension/id/kuronime/Kuronime.kt
- src/id/neonime/build.gradle
- src/id/neonime/src/eu/kanade/tachiyomi/animeextension/id/neonime/NeoNime.kt
Changed domain:
- NeoNime (https://neonime.fun) -> (https://neonime.ink)
- Kuronime (https://45.12.2.26) -> (https://tv1.kuronime.vip)
- Closes #2451 (https://pelisflix.gratis) -> (https://pelisflix2.green)
Checklist:
> Update domain for some sources

- src/ar/egydead/build.gradle
- src/ar/egydead/src/eu/kanade/tachiyomi/animeextension/ar/egydead/EgyDead.kt
- src/ar/tuktukcinema/build.gradle
- src/ar/tuktukcinema/src/eu/kanade/tachiyomi/animeextension/ar/tuktukcinema/Tuktukcinema.kt
fix regex for streamwish
Checklist:
> Fix(src/ar): fix regex for streamwish links

- lib/fastream-extractor/src/main/java/eu/kanade/tachiyomi/lib/fastreamextractor/FastreamExtractor.kt
- src/es/metroseries/build.gradle
- src/es/metroseries/src/eu/kanade/tachiyomi/animeextension/es/metroseries/MetroSeries.kt
- src/es/tioanime/build.gradle
- src/es/tioanime/src/eu/kanade/tachiyomi/animeextension/es/tioanimeh/TioanimeH.kt
- src/es/tioanime/src/eu/kanade/tachiyomi/animeextension/es/tioanimeh/extractors/VidGuardExtractor.kt
Checklist:
Closes #2410
Closes #2362
Closes #2392
Closes #2647
> Fix(src/es): Metroseries and TioAnime fixed

- lib/megacloud-extractor/src/main/java/eu/kanade/tachiyomi/lib/megacloudextractor/MegaCloudExtractor.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/zorotheme/ZoroThemeGenerator.kt
Fixes https://github.com/aniyomiorg/aniyomi-extensions/issues/2568
Alternate to: https://github.com/aniyomiorg/aniyomi-extensions/pull/2711
Tested on both Kaido and AniWatch
Uses regex to find the keys in the obfuscated js file.
This is slightly slower than pulling the key straight from GitHub, but not nearly as bad as de-obfuscating the JavaScript  (not noticeable in daily use).
Obvious benefit of having always up to date keys.
Checklist:
> built in key finder for multisrc/aniwatch/kaido

- src/all/kamyroll/build.gradle
- src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/Yomiroll.kt
Fixed by removing a thread
Pros :
- Doesn't crash anymore
- Freezes whole UI until switch is updated
- 2 lines fix
Cons :
- Absolutely none
Checklist:
> Fix yomiroll crash on Local Token toggle

- multisrc/overrides/dooplay/goanimes/src/extractors/LinkfunBypasser.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/dooplay/DooPlayGenerator.kt
> fix(pt/goanimes): Fix linkfun bypasser

- src/all/kamyroll/build.gradle
- src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/DataModel.kt
- src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/Yomiroll.kt
Closes #2326 
Uses API provided by Anilist.co (https://anilist.github.io/ApiV2-GraphQL-Docs/) to fetch series status as CR won't track for itself. Inspired by https://github.com/aniyomiorg/aniyomi-extensions/pull/2055/files
Checklist:
> fix(all/yomiroll): Fetch anime status from AniList.co

- src/all/kamyroll/build.gradle
- src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/Yomiroll.kt
Fixes status for multi season anime (eg. Classroom of Elite) that were considered completed instead of ongoing etc.
Checklist:
> fix(all/yomiroll): Fix multi season anime status incorrectly retrieved

- src/en/aniwave/build.gradle
- src/en/aniwave/src/eu/kanade/tachiyomi/animeextension/en/nineanime/extractors/VidsrcExtractor.kt
Closes #2602 (why was it even open)
Checklist:
> feat(en/aniwave): use ugly webview hack for vidsrc

- src/es/hackstore/build.gradle
- src/es/hackstore/src/eu/kanade/tachiyomi/animeextension/es/hackstore/Hackstore.kt
> fix(es/Hackstore): Fix orden ep and not found description

- src/all/kamyroll/build.gradle
- src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/Yomiroll.kt
And remove duplicate locale as CR is using the other also sub preference index will be shuffled, users gotta re-select preference
Closes #2846
Checklist:
> fix(all/yomiroll): Make pref subtitle show up first in case app can't determine locale

- src/pt/animefire/AndroidManifest.xml
- src/pt/animefire/build.gradle
- src/pt/animefire/src/eu/kanade/tachiyomi/animeextension/pt/animefire/AnimeFire.kt
- src/pt/animefire/src/eu/kanade/tachiyomi/animeextension/pt/animefire/extractors/AnimeFireExtractor.kt
> fix(pt/animefire): Fix http 401 + update domain (#2861)

- src/id/oploverz/build.gradle
- src/id/oploverz/src/eu/kanade/tachiyomi/animeextension/id/oploverz/Oploverz.kt
Video list is empty cause baseUrl was changed and getEmbedLinks use old baseUrl
Checklist:
> fix(id/oploverz): Video list is empty

- src/all/torrentioanime/build.gradle
- src/all/torrentioanime/src/eu/kanade/tachiyomi/animeextension/all/torrentioanime/Torrentio.kt
Checklist:
Now users will not report in support for getting Token message for using extension for first time.
> fix(all/torrentio): Fix default provider

- src/id/samehadaku/build.gradle
- src/id/samehadaku/src/eu/kanade/tachiyomi/animeextension/id/samehadaku/Samehadaku.kt
> fix(id/samehadaku): Video list is empty

- src/all/jellyfin/build.gradle
- src/all/jellyfin/src/eu/kanade/tachiyomi/animeextension/all/jellyfin/Jellyfin.kt
- src/all/jellyfin/src/eu/kanade/tachiyomi/animeextension/all/jellyfin/JellyfinFactory.kt
* Adds preference to customize name
* Adds preference for number of sources
* Makes jellyfin an unmetered source
Checklist:
> Jellyfin: add custom labels + number of sources

- lib/streamtape-extractor/src/main/java/eu/kanade/tachiyomi/lib/streamtapeextractor/StreamTapeExtractor.kt
- src/es/animeflv/build.gradle
- src/es/animeflv/src/eu/kanade/tachiyomi/animeextension/es/animeflv/AnimeFlv.kt
Checklist:
Changes:
- Removed DoodStream as it isn't available anymore as a server option
- Added StreamWish to the SERVER_LIST array (why it wasn't there?)
- Ordered as like on the website the SERVER_LIST array (optional)
- Changed PREF_QUALITY_DEFAULT to 480, as no server provides 1080p, and the only providing 480p and works well is StreamWish (Okru I think too)
- Changed PREF_SERVER_DEFAULT to StreamWish, as it's usually the best that works without that many ads, after MEGA
- Updated extension version to 53
---
- Removed maru server (doesn't even have a backend)
- Added a blank space to the SW extractor output
Non-related:
- Update Stape wording from StreamTape to Streamtape (lib)
> fix(es/AnimeFLV): change servers info

- src/all/torrentioanime/build.gradle
- src/all/torrentioanime/src/eu/kanade/tachiyomi/animeextension/all/torrentioanime/Torrentio.kt
> Torrentio: Fix Videolist empty for Movies.

- src/tr/animeler/build.gradle
- src/tr/animeler/src/eu/kanade/tachiyomi/animeextension/tr/animeler/Animeler.kt
- src/tr/animeler/src/eu/kanade/tachiyomi/animeextension/tr/animeler/dto/AnimelerDto.kt
Related with #2931 
Note: The extractor is now geo-blocked to turkey, and I'm too lazy to install a VPN, so I had to ask @EfeDevirgen to test it.
Checklist:
> fix(tr/animeler): Fix anime pages + fix extractor

- src/en/fmovies/build.gradle
- src/en/fmovies/src/eu/kanade/tachiyomi/animeextension/en/fmovies/FmoviesUtils.kt
> fix(en/fmovies): update vrf encryption key & algorithm

- src/en/kickassanime/build.gradle
- src/en/kickassanime/src/eu/kanade/tachiyomi/animeextension/en/kickassanime/KickAssAnime.kt
- src/en/kickassanime/src/eu/kanade/tachiyomi/animeextension/en/kickassanime/extractors/KickAssAnimeExtractor.kt
Closes #2259
Hard codes for now, might look at other alternatives if they changes the keys
Checklist:
> Fix KickAssAnime extractor & update urls

- lib/vidsrc-extractor/src/main/java/eu/kanade/tachiyomi/lib/vidsrcextractor/VidSrcExtractor.kt
- src/en/fmovies/src/eu/kanade/tachiyomi/animeextension/en/fmovies/FMovies.kt
> fix(en/fmovies): update subtitle fetching

- src/en/putlocker/build.gradle
- src/en/putlocker/src/eu/kanade/tachiyomi/animeextension/en/putlocker/PutLocker.kt
- src/en/putlocker/src/eu/kanade/tachiyomi/animeextension/en/putlocker/extractors/PutServerExtractor.kt
Closes #2990
Closes #2991
Checklist:
> fix(en/putlocker): fix empty title and add pref

- src/id/otakudesu/build.gradle
- src/id/otakudesu/src/eu/kanade/tachiyomi/animeextension/id/otakudesu/OtakuDesu.kt
Closes https://github.com/aniyomiorg/aniyomi-extensions/issues/2964
Checklist:
> fix(id/otakudesu): Video list is empty

- src/en/fmovies/build.gradle
the action was cancelled before the version bump due to another pr merge
Checklist:
> fix(en/fmovies): bump version

- src/ar/arabseed/build.gradle
- src/ar/arabseed/src/eu/kanade/tachiyomi/animeextension/ar/arabseed/ArabSeed.kt
- src/ar/egydead/build.gradle
- src/ar/egydead/src/eu/kanade/tachiyomi/animeextension/ar/egydead/EgyDead.kt
- src/ar/tuktukcinema/build.gradle
- src/ar/tuktukcinema/src/eu/kanade/tachiyomi/animeextension/ar/tuktukcinema/Tuktukcinema.kt
- src/en/ask4movie/build.gradle
- src/en/ask4movie/src/eu/kanade/tachiyomi/animeextension/en/ask4movie/Ask4Movie.kt
- src/en/dramacool/build.gradle
- src/en/dramacool/src/eu/kanade/tachiyomi/animeextension/en/dramacool/DramaCool.kt
- src/en/gogoanime/build.gradle
- src/en/gogoanime/src/eu/kanade/tachiyomi/animeextension/en/gogoanime/GogoAnime.kt
- src/en/multimovies/build.gradle
- src/en/multimovies/src/eu/kanade/tachiyomi/animeextension/en/multimovies/Multimovies.kt
- src/en/ripcrabbyanime/build.gradle
- src/en/ripcrabbyanime/src/eu/kanade/tachiyomi/animeextension/en/ripcrabbyanime/Ripcrabbyanime.kt
- src/hi/yomovies/build.gradle
- src/hi/yomovies/src/eu/kanade/tachiyomi/animeextension/hi/yomovies/YoMovies.kt
- src/it/animeunity/build.gradle
- src/it/animeunity/src/eu/kanade/tachiyomi/animeextension/it/animeunity/AnimeUnity.kt
- src/it/animeworld/build.gradle
- src/it/animeworld/src/eu/kanade/tachiyomi/animeextension/it/animeworld/ANIMEWORLD.kt
- src/it/streamingcommunity/build.gradle
- src/it/streamingcommunity/src/eu/kanade/tachiyomi/animeextension/it/streamingcommunity/StreamingCommunity.kt
Using the version number as the key will leave a trail of obsolete preferences, which should be avoided. I don't mean to prevent overridable baseurls with this pr, it's just that they should be implemented in such a way that doesn't create unnecessary preference items. I also don't want to convert all to a new system, since a lot of extension appears to not have changed urls in a long time.
> refactor: remove BuildConfig from preference keys

- lib/playlist-utils/src/main/java/eu/kanade/tachiyomi/lib/playlistutils/PlaylistUtils.kt
Preserves query parameters for each m3u8 url in the master m3u8
Checklist:
> fix(lib/playlistutils): keep query for m3u8 requests

- lib/playlist-utils/src/main/java/eu/kanade/tachiyomi/lib/playlistutils/PlaylistUtils.kt
This reverts commit 0bed9f97e5b9005816d9f2ec299b672607fd101f.
turns out that the only extension that needed this change, actually didn't need it
we live in a society
> fix(lib/playlist-utils): Revert #3032

- src/pt/vizer/build.gradle
- src/pt/vizer/src/eu/kanade/tachiyomi/animeextension/pt/vizer/Vizer.kt
- src/pt/vizer/src/eu/kanade/tachiyomi/animeextension/pt/vizer/dto/VizerDto.kt
- src/pt/vizer/src/eu/kanade/tachiyomi/animeextension/pt/vizer/extractors/WarezExtractor.kt
> fix(pt/vizer): Update baseURL + fix episode list + add WarezCDN extractor

- src/all/chineseanime/build.gradle
- src/all/chineseanime/src/eu/kanade/tachiyomi/animeextension/all/chineseanime/ChineseAnime.kt
Closes #2977
^ Actually it doesn't, because `playlist-utils` got slightly _trolled_ recently, but everything should work well after _un-trolling_ `playlist-utils` :+1:
Checklist:
> fix(all/chineseanime): Update baseUrl + add StreamVid extractor

- src/en/animepahe/build.gradle
- src/en/animepahe/src/eu/kanade/tachiyomi/animeextension/en/animepahe/AnimePahe.kt
- src/en/animepahe/src/eu/kanade/tachiyomi/animeextension/en/animepahe/DdosGuardInterceptor.kt
No need to open webview to bypass check anymore
Checklist:
> fix(en/animepahe): use ddosguardinterceptor

- lib-multisrc/zorotheme/build.gradle.kts
- lib-multisrc/zorotheme/src/eu/kanade/tachiyomi/multisrc/zorotheme/ZoroTheme.kt
- src/en/kaido/src/eu/kanade/tachiyomi/animeextension/en/kaido/Kaido.kt
- src/en/zoro/src/eu/kanade/tachiyomi/animeextension/en/zoro/HiAnime.kt
> feat(multisrc/zorotheme): force clear outdated hosts

- src/all/kamyroll/build.gradle
- src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/DataModel.kt
- src/all/kamyroll/src/eu/kanade/tachiyomi/animeextension/all/kamyroll/Yomiroll.kt
as pl.crunchyroll.com is returning 403
Closes #3049 
Checklist:
> fix(all/yomiroll): switch to vrv links

- src/en/animeflixlive/build.gradle
- src/en/animeflixlive/src/eu/kanade/tachiyomi/animeextension/en/animeflixlive/AnimeflixLive.kt
> fix(en/animeflix.live): fix video extraction

- lib/googledrive-extractor/src/main/java/eu/kanade/tachiyomi/lib/googledriveextractor/GoogleDriveExtractor.kt
- src/all/googledrive/src/eu/kanade/tachiyomi/animeextension/all/googledrive/GoogleDrive.kt
- src/en/kayoanime/src/eu/kanade/tachiyomi/animeextension/en/kayoanime/Kayoanime.kt
- src/en/ripcrabbyanime/src/eu/kanade/tachiyomi/animeextension/en/ripcrabbyanime/Ripcrabbyanime.kt
Autobump script will bump the ext versions
Closes #2635
Closes #2723
Checklist:
> Fix google drive based extensions

- src/es/animeflv/build.gradle
- src/es/animeflv/src/eu/kanade/tachiyomi/animeextension/es/animeflv/AnimeFlv.kt
- src/es/gnula/build.gradle
- src/es/gnula/src/eu/kanade/tachiyomi/animeextension/es/gnula/DataModel.kt
- src/es/gnula/src/eu/kanade/tachiyomi/animeextension/es/gnula/Gnula.kt
- src/es/hackstore/build.gradle
- src/es/hackstore/src/eu/kanade/tachiyomi/animeextension/es/hackstore/Hackstore.kt
- src/es/hentaila/build.gradle
- src/es/hentaila/src/eu/kanade/tachiyomi/animeextension/es/hentaila/Hentaila.kt
> fix(src/es): Some fixes for Spanish extensions

- src/it/streamingcommunity/build.gradle
- src/it/streamingcommunity/src/eu/kanade/tachiyomi/animeextension/it/streamingcommunity/StreamingCommunity.kt
This has been fixed by this guy about 3 months ago or so, I've only changed the domain and other little things.
Closes #3071
Closes #2477
Checklist:
> Fix(It/StreamingCommunity): Fix empty videolist and change base domain

- src/en/oppaistream/build.gradle
- src/en/oppaistream/src/eu/kanade/tachiyomi/animeextension/en/oppaistream/OppaiStream.kt
- Handled url with special characters.
Checklist:
> OppaiStream: Fix url problem with some animes.

- src/es/doramasflix/build.gradle
- src/es/doramasflix/src/eu/kanade/tachiyomi/animeextension/es/doramasflix/DataModel.kt
- src/es/jkanime/build.gradle
- src/es/jkanime/src/eu/kanade/tachiyomi/animeextension/es/jkanime/Jkanime.kt
- src/es/jkanime/src/eu/kanade/tachiyomi/animeextension/es/jkanime/extractors/JkanimeExtractor.kt
Checklist:
Closes #3099
Closes #3136
> fix(src/es): Fix video extraction and fix json parsing

- lib/voe-extractor/src/main/java/eu/kanade/tachiyomi/lib/voeextractor/VoeExtractor.kt
> fix(lib/voe-extractor): Voe extractor fixed

- src/all/torrentioanime/build.gradle
- src/all/torrentioanime/src/eu/kanade/tachiyomi/animeextension/all/torrentioanime/Torrentio.kt
> Torrentio: Fixed reverse sort order of quality.

- src/pt/animeplayer/build.gradle
- src/pt/animeplayer/src/eu/kanade/tachiyomi/animeextension/pt/animeplayer/AnimePlayer.kt
> fix(pt/animeplayer): Fix popular anime, anime details and episode list pages

- src/all/sudatchi/build.gradle
- src/all/sudatchi/src/eu/kanade/tachiyomi/animeextension/all/sudatchi/Sudatchi.kt
- src/all/sudatchi/src/eu/kanade/tachiyomi/animeextension/all/sudatchi/dto/SudatchiDto.kt
> fix(all/sudatchi): replaced api calls with NEXT json

- src/all/jellyfin/build.gradle
- src/all/jellyfin/src/eu/kanade/tachiyomi/animeextension/all/jellyfin/Jellyfin.kt
- src/all/jellyfin/src/eu/kanade/tachiyomi/animeextension/all/jellyfin/JellyfinDto.kt
> preference(jellyfin): Add option to hide extension affixes
